### ISSUE TITLE
OpenQA.Selenium.WebDriverException: Access is denied when Mouse.MouseMove

### ISSUE THREAD

**Issue by alex1yaremchuk** [microsoft/WinAppDriver#1009]
Hi, 

I used session.Mouse.MouseMove to move mouse to the control I wasn't able to locate with ids. 

It worked fine as I was running it, but on night run it failed as 

> Error Message:
   Test method UiTests.ScenarioCreateNewDb.CreateNewDb threw exception: 
OpenQA.Selenium.WebDriverException: Access is denied
Stack Trace:
    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteMouse.MouseMove(ICoordinates where, Int32 offsetX, Int32 offsetY)

**Comment by alex1yaremchuk** [comment]
Help myself
https://github.com/Microsoft/WinAppDriver/issues/477

It seems to be as designed. 

Open question - how to set up CI, nightly builds with this limitation?

**Comment by hassanuz** [comment]
What service are you using for CI? On Azure DevOps it is recommended to use an [interactive agent ](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#choose-interactive-or-service-mode) for UI automation scenarios. DevOps should automatically take care of the logging in process for the agent. 

You'd want to make sure whatever CI service you have is able to bypass the lock screen.

**Comment by alex1yaremchuk** [comment]
Hi, thanks for the reply!

We're using TFS Builds.

**Comment by alex1yaremchuk** [comment]
Our admins say that any auto-login is unsafe. 
Is there some resource about security of using interactive agents (whatever it is)?

**Comment by naeemakram** [comment]
Windows automation scripts need to interact with the desktop, an active session is a prerequisite since the dawn of times. You will need an active, unlocked machine. There's no way around it.
