### ISSUE TITLE
Code not working after opening WinAppDriver.exe programmatically .

### ISSUE THREAD

**Issue by angad16** [microsoft/WinAppDriver#1059]
Hi i have automated a Windows application suing WinAppDriver and it is working absolutely fine. Now i am trying to open WinAppDriver.exe from my java code by using ProcessBuilder class here is the code :
ProcessBuilder p = new ProcessBuilder();
p.command("C:\\Users\\Administrator\\WinAppDriver\\WinAppDriverTool\\WinAppDriver.exe");
Process process = p.start();

it is also working good and launches the winappdriver.exe, and i am also able to open the application but after that it is no working, neither it is failing nor working.

**Comment by vineetgulati** [comment]
Hi, I am using the exactly same code but I am getting this below error.
What I am missing here? Any idea



java.lang.NoClassDefFoundError: org/openqa/selenium/remote/internal/JsonToWebElementConverter

	at demoTest.setup(demoTest.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.internal.JsonToWebElementConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 28 more

**Comment by angad16** [comment]
Hi @vineetgulati  please can you please share your code?

**Comment by anshul1goel** [comment]
Is the WinAppDriver process launching with administrator privileges?

**Comment by erohinalexey** [comment]
Hi! I faced with the same issue.

My code is: 
`private void setupEnvironment() throws IOException, InterruptedException {
        ProcessBuilder builder = new ProcessBuilder(pathToApplication);
        final Process process = builder.start();

        // WinDriver for defining window
        DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
        desktopCapabilities.setCapability("platformName", "Windows");
        desktopCapabilities.setCapability("app", "Root");
        WindowsDriver desktopDriver = new WindowsDriver(new URL(winAppDriverServer), desktopCapabilities);
        desktopDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

        // Window HEX defining
        WebElement projectWindow = desktopDriver.findElementByAccessibilityId(mainProjectWindow);
        String nativeWindowHandle = projectWindow.getAttribute("NativeWindowHandle");
        Integer intNativeWindowHandle = Integer.parseInt(nativeWindowHandle);
        String hexNativeWindowHandle = Integer.toHexString(intNativeWindowHandle);

        //Attach it to session
        DesiredCapabilities appCapabilities = new DesiredCapabilities();
        appCapabilities.setCapability("platformName", "Windows");
        appCapabilities.setCapability("deviceName", "WindowsPC");
        appCapabilities.setCapability("appTopLevelWindow", hexNativeWindowHandle);
        winDriver = new WindowsDriver(new URL(winAppDriverServer), appCapabilities);
        winDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
}`

I get error: 
`POST /session/5F69DF68-A9BD-440D-BB50-34692CAE8926/element HTTP/1.1
Accept-Encoding: gzip
Connection: Keep-Alive
Content-Length: 60
Content-Type: application/json; charset=utf-8
Host: localhost:4723
User-Agent: selenium/3.141.59 (java windows)

{
  "using": "accessibility id",
  "value": "#ProjectName"
}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}`

But, when application run manual, this code works well. 
Is there a way to run application from code and use it with WinDriver?

**Comment by MoatazFarid** [comment]
@angad16 Can you explain how it is not working?!
also, You can try this way 
```
            String command = "C:\\Program Files (x86)\\Windows Application Driver\\WinAppDriver.exe";
            ProcessBuilder builder = new ProcessBuilder(command).inheritIO();
            try {
                builder.start();
            } catch (IOException e) {
                e.printStackTrace();
            }
```
