### ISSUE TITLE
window getsize returns null

### ISSUE THREAD

**Issue by jsa34** [microsoft/WinAppDriver#1104]
WinAppDriver version: 1.2-RC
Java-client (Appium): 7.3.0
Appium: 1.7.0

Trying to help with implementing the appium command findByImage, when trying to get window size, it returns null.

Using java-client for appium, the following code returns null:
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("platformName", "Windows");
            capabilities.setCapability("deviceName", "WindowsPC");
            capabilities.setCapability("ms:experimental-webdriver", true);
            capabilities.setCapability("appTopLevelWindow", desiredWindowHandle);
            WindowsDriver<WindowsElement> d = new WindowsDriver<>(getDriver().getRemoteAddress(), capabilities);

d.manage().window().getSize(); <-- returns null

It lists end point GET /window/size as a valid endpoint on the documentation, but this doesn't seem to be working.

**Comment by neuxioz** [comment]
I have the same issue

> C:\Users\kgorb>c:\Python38\python.exe
> Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> import requests

> requests.get("http://127.0.0.1:4723/wd/hub/session/F5C889B5-0EF3-4402-BB79-79A4F85CABE7/window/0x00010010/size")

> <Response [200]>

> requests.get("http://127.0.0.1:4723/wd/hub/session/F5C889B5-0EF3-4402-BB79-79A4F85CABE7/window/0x00010010/size").json()

> {'sessionId': 'F5C889B5-0EF3-4402-BB79-79A4F85CABE7', 'status': 0}

**Comment by bbeaupain** [comment]
I'm also having the same issue, `getSize()` itself is throwing a `NullPointerException` on the following line:

```
int width = ((Number) rawSize.get("width")).intValue();
```

**Comment by pdisser8** [comment]
Having this same issue, it appears that something has updated incongruously, appium is looking for the endpoint 
`GET: /session/<sessionid>/window/rect`
while winappdriver only has the endpoint
`GET: /session/<sessionid>/window/size`

appium 1.21.0
winappdriver 1.1
python

**Comment by dtopuzov** [comment]
I encounter following with `appium@2.0.0-beta.23` and latest WinAppDriver
```
2021-11-28 16:06:08:795 [WinAppDriver] {"sessionId":"CC62C390-207D-418F-8198-0B41F1593632","status":0}
2021-11-28 16:06:08:796 [WD Proxy] Got response with status 200: {"sessionId":"CC62C390-207D-418F-8198-0B41F1593632","status":0}
2021-11-28 16:06:08:796 [WinAppDriver] Cannot retrieve window size from WinAppDriver
2021-11-28 16:06:08:796 [WinAppDriver] Falling back to Windows Forms to calculate dimensions
2021-11-28 16:06:08:805 [W3C (1025ce65)] Encountered internal error running command: TypeError: Cannot read property 'execPowerShell' of undefined
2021-11-28 16:06:08:805 [W3C (1025ce65)]     at getScreenSize (C:\Users\topuzov\.appium\appium-windows-driver\node_modules\appium-windows-driver\lib\commands\general.js:5:33)
2021-11-28 16:06:08:805 [W3C (1025ce65)]     at WindowsDriver.getWindowSize (C:\Users\topuzov\.appium\appium-windows-driver\node_modules\appium-windows-driver\lib\commands\general.js:31:16)
2021-11-28 16:06:08:805 [W3C (1025ce65)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-11-28 16:06:08:805 [W3C (1025ce65)]     at WindowsDriver.getWindowRect (C:\Users\topuzov\.appium\appium-windows-driver\node_modules\appium-windows-driver\lib\commands\general.js:36:27)
2021-11-28 16:06:08:840 [HTTP] <-- GET /wd/hub/session/1025ce65-f161-43ae-b3a8-dc72c2a93b9e/window/rect 500 98 ms - 693
2021-11-28 16:06:08:840 [HTTP] 
```
