### ISSUE TITLE
The text associated with this error code could not be found while launching UWP app using WinAppdriver with appium

### ISSUE THREAD

**Issue by krevathi1912** [microsoft/WinAppDriver#1195]
Hi,
At times, I am receiving "The text associated with this error code could not be found"  while launching UWP app using appium+winappdriver. Below are the details. Request any help

Appium version: v1.16.0
WinAppdriver version : WinAppDriver version 1.2-RC
Type of app: UWP

Below is the appium server log
`2020-06-11 16:11:19:475 - [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
2020-06-11 16:11:19:476 - [35m[HTTP][39m [90m{"capabilities":{"firstMatch":[{"platformName":"Windows","appium:deviceName":"WindowsPC","appium:app":".......!App","ms:waitForAppLaunch":10}]},"desiredCapabilities":{"platformName":"Windows","deviceName":"WindowsPC","app":".......!App","ms:waitForAppLaunch":10}}[39m
2020-06-11 16:11:19:476 - [debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"platformName":"Windows","deviceName":"WindowsPC","app":".......!App","ms:waitForAppLaunch":10},null,{"firstMatch":[{"platformName":"Windows","appium:deviceName":"WindowsPC","appium:app":".......!App","ms:waitForAppLaunch":10}]}]
2020-06-11 16:11:19:477 - [debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1591872079477 (16:11:19 GMT+0530 (India Standard Time))
2020-06-11 16:11:19:533 - [35m[Appium][39m Appium v1.16.0 creating new WindowsDriver (v1.8.0) session
2020-06-11 16:11:19:534 - [debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
2020-06-11 16:11:19:535 - [debug] [35m[BaseDriver][39m   "platformName": "Windows",
2020-06-11 16:11:19:535 - [debug] [35m[BaseDriver][39m   "deviceName": "WindowsPC",
2020-06-11 16:11:19:535 - [debug] [35m[BaseDriver][39m   "app": ".......!App",
2020-06-11 16:11:19:535 - [debug] [35m[BaseDriver][39m   "waitForAppLaunch": 10
2020-06-11 16:11:19:535 - [debug] [35m[BaseDriver][39m }
2020-06-11 16:11:19:536 - [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
2020-06-11 16:11:19:536 - [35m[BaseDriver][39m   waitForAppLaunch
2020-06-11 16:11:19:537 - [35m[BaseDriver][39m Session created with session id: 69611cd8-75a9-462b-994a-aee52f53d442
2020-06-11 16:11:19:537 - [35m[WinAppDriver][39m You must use WinAppDriver version 1.2-RC
2020-06-11 16:11:19:538 - [35m[WinAppDriver][39m Verifying WinAppDriver version 1.2-RC is installed via comparing the checksum.
2020-06-11 16:11:19:542 - [debug] [35m[WinAppDriver][39m WinAppDriver changed state to 'starting'
2020-06-11 16:11:19:542 - [35m[WinAppDriver][39m Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
2020-06-11 16:11:19:669 - [35m[WinAppDriver][39m No old WinAppDrivers seemed to exist
2020-06-11 16:11:19:670 - [35m[WinAppDriver][39m Spawning WinAppDriver with: 4724/wd/hub
2020-06-11 16:11:19:719 - [35m[WinAppDriver][39m [STDOUT] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
2020-06-11 16:11:19:722 - [debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
2020-06-11 16:11:19:730 - [35m[WinAppDriver][39m [STDOUT] Press ENTER to exit.
2020-06-11 16:11:19:738 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:19:739 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:19:739 - [35m[WinAppDriver][39m [STDOUT] ==========================================
2020-06-11 16:11:19:739 - [35m[WinAppDriver][39m [STDOUT] GET /wd/hub/status HTTP/1.1
2020-06-11 16:11:19:739 - [35m[WinAppDriver][39m [STDOUT] Accept: application/json, */*
2020-06-11 16:11:19:740 - [35m[WinAppDriver][39m [STDOUT] Connection: close
2020-06-11 16:11:19:740 - [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json; charset=utf-8
2020-06-11 16:11:19:740 - [35m[WinAppDriver][39m [STDOUT] Host: 127.0.0.1:4724
2020-06-11 16:11:19:740 - [35m[WinAppDriver][39m [STDOUT] User-Agent: appium
2020-06-11 16:11:19:740 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:19:740 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:19:744 - [35m[WinAppDriver][39m [STDOUT] HTTP/1.1 200 OK
2020-06-11 16:11:19:744 - [35m[WinAppDriver][39m [STDOUT] Content-Length: 146
2020-06-11 16:11:19:744 - [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json
2020-06-11 16:11:19:744 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:19:744 - [35m[WinAppDriver][39m [STDOUT] {"build":{"revision":"2002","time":"Wed Oct  2 21:08:40 2019","version":"1.2.1910"},"os":{"arch":"amd64","name":"windows","version":"10.0.18362"}}
2020-06-11 16:11:19:745 - [debug] [35m[WD Proxy][39m Got response with status 200: {"build":{"revision":"2002","time":"Wed Oct  2 21:08:40 2019","version":"1.2.1910"},"os":{"arch":"amd64","name":"windows","version":"10.0.18362"}}
2020-06-11 16:11:19:745 - [35m[WinAppDriver][39m Status call returned 200. we're online and ready to run tests
2020-06-11 16:11:19:746 - [debug] [35m[WinAppDriver][39m WinAppDriver changed state to 'online'
2020-06-11 16:11:19:746 - [debug] [35m[WinAppDriver][39m Starting WinAppDriver session. Will timeout in '20000' ms.
2020-06-11 16:11:19:747 - [debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
2020-06-11 16:11:19:748 - [debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"Windows","deviceName":"WindowsPC","app":".......!App","waitForAppLaunch":10}}
2020-06-11 16:11:19:753 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:19:754 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:19:754 - [35m[WinAppDriver][39m [STDOUT] ==========================================
2020-06-11 16:11:19:754 - [35m[WinAppDriver][39m [STDOUT] POST /wd/hub/session HTTP/1.1
2020-06-11 16:11:19:754 - [35m[WinAppDriver][39m [STDOUT] Accept: application/json, */*
2020-06-11 16:11:19:755 - [35m[WinAppDriver][39m [STDOUT] Connection: close
2020-06-11 16:11:19:755 - [35m[WinAppDriver][39m [STDOUT] Content-Length: 136
2020-06-11 16:11:19:755 - [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json; charset=utf-8
2020-06-11 16:11:19:755 - [35m[WinAppDriver][39m [STDOUT] Host: 127.0.0.1:4724
2020-06-11 16:11:19:755 - [35m[WinAppDriver][39m [STDOUT] User-Agent: appium
2020-06-11 16:11:19:755 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:19:756 - [35m[WinAppDriver][39m [STDOUT] {"desiredCapabilities":{"platformName":"Windows","deviceName":"WindowsPC","app":".......!App","waitForAppLaunch":10}}
2020-06-11 16:11:34:744 - [35m[WinAppDriver][39m [STDOUT] HTTP/1.1 500 Internal Error
2020-06-11 16:11:34:745 - [35m[WinAppDriver][39m [STDOUT] Content-Length: 192
2020-06-11 16:11:34:745 - [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json
2020-06-11 16:11:34:745 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:34:746 - [35m[WinAppDriver][39m [STDOUT] {"status":13,"value":{"error":"unknown error","message":"The text associated with this error code could not be found.\r\n\r\nThe text associated with this error code could not be found.\r\n"}}
2020-06-11 16:11:34:753 - [35m[WD Proxy][39m Got an unexpected response with status 500: {"status":13,"value":{"error":"unknown error","message":"The text associated with this error code could not be found.\r\n\r\nThe text associated with this error code could not be found.\r\n"}}
2020-06-11 16:11:34:757 - [debug] [35m[W3C][39m Matched W3C error code 'unknown error' to UnknownError
2020-06-11 16:11:34:758 - [35m[WinAppDriver][39m Could not start WinAppDriver session error = 'An unknown server-side error occurred while processing the command. Original error: The text associated with this error code could not be found.

2020-06-11 16:11:34:759 - [35m[WinAppDriver][39m 

2020-06-11 16:11:34:759 - [35m[WinAppDriver][39m The text associated with this error code could not be found.

2020-06-11 16:11:34:759 - [35m[WinAppDriver][39m ', attempt = '1' from 'undefined'
2020-06-11 16:11:35:272 - [debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
2020-06-11 16:11:35:273 - [debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"Windows","deviceName":"WindowsPC","app":".......!App","waitForAppLaunch":10}}
2020-06-11 16:11:35:282 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:35:283 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:35:283 - [35m[WinAppDriver][39m [STDOUT] ==========================================
2020-06-11 16:11:35:284 - [35m[WinAppDriver][39m [STDOUT] POST /wd/hub/session HTTP/1.1
2020-06-11 16:11:35:284 - [35m[WinAppDriver][39m [STDOUT] Accept: application/json, */*
2020-06-11 16:11:35:284 - [35m[WinAppDriver][39m [STDOUT] Connection: close
2020-06-11 16:11:35:285 - [35m[WinAppDriver][39m [STDOUT] Content-Length: 136
2020-06-11 16:11:35:285 - [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json; charset=utf-8
2020-06-11 16:11:35:286 - [35m[WinAppDriver][39m [STDOUT] Host: 127.0.0.1:4724
2020-06-11 16:11:35:286 - [35m[WinAppDriver][39m [STDOUT] User-Agent: appium
2020-06-11 16:11:35:286 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:35:287 - [35m[WinAppDriver][39m [STDOUT] {"desiredCapabilities":{"platformName":"Windows","deviceName":"WindowsPC","app":".......!App","waitForAppLaunch":10}}
2020-06-11 16:11:47:156 - [35m[WinAppDriver][39m [STDOUT] HTTP/1.1 500 Internal Error
2020-06-11 16:11:47:157 - [35m[WinAppDriver][39m [STDOUT] Content-Length: 192
2020-06-11 16:11:47:157 - [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json
2020-06-11 16:11:47:158 - [35m[WinAppDriver][39m [STDOUT] 
2020-06-11 16:11:47:158 - [35m[WinAppDriver][39m [STDOUT] {"status":13,"value":{"error":"unknown error","message":"The text associated with this error code could not be found.\r\n\r\nThe text associated with this error code could not be found.\r\n"}}
2020-06-11 16:11:47:160 - [35m[WD Proxy][39m Got an unexpected response with status 500: {"status":13,"value":{"error":"unknown error","message":"The text associated with this error code could not be found.\r\n\r\nThe text associated with this error code could not be found.\r\n"}}
2020-06-11 16:11:47:161 - [debug] [35m[W3C][39m Matched W3C error code 'unknown error' to UnknownError
2020-06-11 16:11:47:161 - [35m[WinAppDriver][39m Could not start WinAppDriver session error = 'An unknown server-side error occurred while processing the command. Original error: The text associated with this error code could not be found.

2020-06-11 16:11:47:161 - [35m[WinAppDriver][39m 

2020-06-11 16:11:47:161 - [35m[WinAppDriver][39m The text associated with this error code could not be found.

2020-06-11 16:11:47:162 - [35m[WinAppDriver][39m ', attempt = '2' from 'undefined'
2020-06-11 16:11:47:162 - [debug] [35m[WinAppDriver][39m timeoutError was Condition unmet after 27416 ms. Timing out.
2020-06-11 16:11:47:162 - [debug] [35m[WinAppDriver][39m Deleting WinAppDriver session
2020-06-11 16:11:47:164 - [debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1591872107164 (16:11:47 GMT+0530 (India Standard Time))
2020-06-11 16:11:47:273 - [debug] [35m[W3C][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: The text associated with this error code could not be found.

2020-06-11 16:11:47:274 - [debug] [35m[W3C][39m 

2020-06-11 16:11:47:274 - [debug] [35m[W3C][39m The text associated with this error code could not be found.

2020-06-11 16:11:47:274 - [debug] [35m[W3C][39m 
2020-06-11 16:11:47:274 - [debug] [35m[W3C][39m     at errorFromW3CJsonCode (C:\Users\rkanakachalam\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:780:25)
2020-06-11 16:11:47:275 - [debug] [35m[W3C][39m     at ProxyRequestError.getActualError (C:\Users\rkanakachalam\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:663:14)
2020-06-11 16:11:47:275 - [debug] [35m[W3C][39m     at JWProxy.command (C:\Users\rkanakachalam\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:268:19)
2020-06-11 16:11:47:279 - [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m27801 ms - 1024[39m
2020-06-11 16:11:47:279 - [35m[HTTP][39m [90m[39m`

**Comment by krevathi1912** [comment]
Appreciate any help

**Comment by anunay1** [comment]
We're you able to solve this?

**Comment by anunay1** [comment]
Can you share the code? For me it appears like a timing issue.

**Comment by arvinkx** [comment]
No the OP but I'm running into this issue as well. It occurs if I add any `appArguments` to the session. If I comment out the line adding the additional capability for appArguments, it works. I believe I've included all relevant info below: 

UnitTest.cs
```
var options = new AppiumOptions();
options.AddAdditionalCapability("app", "d7a79968-15e7-4af8-a4e8-653aca4fee24_vg8b7pdx2916g!App");
options.AddAdditionalCapability("appArguments", "authtest");
var session = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), options);
Assert.IsNotNull(session, "Session is null");
var signinButton = session.FindElementByAccessibilityId("SignInButton");
Assert.IsNotNull(signinButton, "SignIn MIssing");
```

Logs
```
==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Cache-Control: no-cache
Connection: Keep-Alive
Content-Length: 198
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{"desiredCapabilities":{"app":"d7a79968-15e7-4af8-a4e8-653aca4fee24_vg8b7pdx2916g!App","appArguments":"authtest","platformName":"Windows"},"capabilities":{"firstMatch":[{"platformName":"Windows"}]}}
HTTP/1.1 500 Internal Error
Content-Length: 192
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"The text associated with this error code could not be found.\r\n\r\nThe text associated with this error code could not be found.\r\n"}}
```
Unit Test Error
```
 Message: 
    Test method TestUnitTest.UnitTest1.TestMethod1 threw exception: 
    OpenQA.Selenium.WebDriverException: The text associated with this error code could not be found.
    
    The text associated with this error code could not be found.
    
  Stack Trace: 
    RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
    RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
    RemoteWebDriver.ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
    AppiumDriver`1.ctor(Uri remoteAddress, ICapabilities appiumOptions)
    UnitTest1.TestMethod1()
```

**Comment by anunay1** [comment]
And what does this app arguments authtest do, have you tried running the application with Process.Start and then creating a session with the opened window.

**Comment by arvinkx** [comment]
I'm trying to pass a string (authtest) to the UWP app I'm testing using `appArguments` like mentioned in the `Authoring Your Own Test Script` (https://github.com/microsoft/WinAppDriver/blob/master/Docs/AuthoringTestScripts.md). 

I am running the tests using Visual Studio's Test Explorer by clicking on the button "Run all Tests In View". 

If I remove the line attempting to add the appArguments to the `AppiumOptions`, everything works as I would expect (the app launches and the tests actually run) but when I add that line, the tests aren't able to init a session and the error that's thrown is the one I posted above. 

I appreciate the help and please let me know if I can provide any other information.

**Comment by calmshot** [comment]
im getting  the same issue, anyone have resolved this?>
