### ISSUE TITLE
Window Handles not returning child window ID in WinAppDriver and throws Unknown error exception

### ISSUE THREAD

**Issue by yatheesh1989** [microsoft/WinAppDriver#1272]
When our application launches, child window overlaps on the parent window.  Refer attached screenshot
We are trying to find the child window id by using  "var handles = ApplicationSession.WindowHandles; "

and trying to switch to the child window before interacting with it but the winappdriver always returning parent window handle and we facing below exception,
07:54:57 OpenQA.Selenium.WebDriverException: An unknown error occurred in the remote end while processing the command.
07:54:57 Stack Trace:
07:54:57     at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
07:54:57    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
07:54:57    at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
07:54:57    at OpenQA.Selenium.Remote.RemoteTargetLocator.Window(String windowHandleOrName)
07:54:57    at API.Healthcare.Testing.UI.ScheduleGrid.ObjectRepository.WindowObjects.Base.BaseWindow.SwitchToWindow()

a. Is switching to child window needed?

b. Can you know why this exception throws with winappdriver?

We also tried without switching to window, By directly interacting with the elements of child window but here we are seeing inconsistent results and above unknown error exception occurs some time.

Note: The tests are running remotely among the test agents 
<img width="957" alt="windowhandle" src="https://user-images.githubusercontent.com/37588949/90621675-abb0ff80-e231-11ea-9365-66177b2299ce.png">
using jenkins job

**Comment by anunay1** [comment]
No necessary you need to switch to the child window, if it is part of the same UI tree,

**Comment by yatheesh1989** [comment]
> Not necessary you need to switch to the child window, if it is part of the same UI tree,

Even we tried without switching window and getting below Unknown error exception while executing as batch run in remotely.

07:54:57 OpenQA.Selenium.WebDriverException: An unknown error occurred in the remote end while processing the command.
07:54:57 Stack Trace:
07:54:57 at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
07:54:57 at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary2 parameters) 07:54:57 at OpenQA.Selenium.Appium.AppiumDriver1.Execute(String driverCommandToExecute, Dictionary`2 parameters)

Do you know why this unknown error throws by finding the element?

**Comment by anunay1** [comment]
I always get the response if the UI is not ready, also can you share the code

**Comment by yatheesh1989** [comment]
Yes we are first getting elements then we are trying to enter text on that below is the example what we are using and we are facing unknow error execption,

private WindowsElement FacilityTextBox
		{
			get { return (WindowsElement)this.openScheduleTabItem.FindElementByAccessibilityId("txtFacility"); }
		}
		private WindowsElement DepartmentTextBox
		{
			get { return (WindowsElement)this.openScheduleTabItem.FindElementByAccessibilityId("txtCostCenter"); }
		}
		
		public void EnterValueInFacilityAndDepartment(OpenScheduleDataSet openScheduleDataSet)
		{
			this.FacilityTextBox.Clear();
			this.FacilityTextBox.CustomSendKeys(openScheduleDataSet.Trunk);

			this.DepartmentTextBox.Clear();
			this.DepartmentTextBox.SendKeys(openScheduleDataSet.Branch);

		}

**Comment by yatheesh1989** [comment]
> I always get the response if the UI is not ready, also can you share the code

Here we are first getting elements then we are trying to enter text on that below is the example what we are using and we are facing unknown error exception on remote end

And we able to execute the same code local without issue but while testing remotely the unknown error throws. here we are using 6 test machine and executing tests parallel and we are launching local default ip and port of winappdriver.

Is the unknown exception on remote end is due to using default IP and port in remote machine?

If yes how we can manage multiple remote machine to use winappdriver for parallel tests in remote?

Sample Code:

private WindowsElement FacilityTextBox
{
get { return (WindowsElement)this.openScheduleTabItem.FindElementByAccessibilityId("txtFacility"); }
}
private WindowsElement DepartmentTextBox
{
get { return (WindowsElement)this.openScheduleTabItem.FindElementByAccessibilityId("txtCostCenter"); }
}

	public void EnterValueInFacilityAndDepartment(OpenScheduleDataSet openScheduleDataSet)
	{
		this.FacilityTextBox.Clear();
		this.FacilityTextBox.CustomSendKeys(openScheduleDataSet.Trunk);

		this.DepartmentTextBox.Clear();
		this.DepartmentTextBox.SendKeys(openScheduleDataSet.Branch);

	}

**Comment by anunay1** [comment]
> > I always get the response if the UI is not ready, also can you share the code
> 
> Here we are first getting elements then we are trying to enter text on that below is the example what we are using and we are facing unknown error exception on remote end
> 
> And we able to execute the same code local without issue but while testing remotely the unknown error throws. here we are using 6 test machine and executing tests parallel and we are launching local default ip and port of winappdriver.
> 
> Is the unknown exception on remote end is due to using default IP and port in remote machine?
> 
> If yes how we can manage multiple remote machine to use winappdriver for parallel tests in remote?
> 
> Sample Code:
> 
> private WindowsElement FacilityTextBox
> {
> get { return (WindowsElement)this.openScheduleTabItem.FindElementByAccessibilityId("txtFacility"); }
> }
> private WindowsElement DepartmentTextBox
> {
> get { return (WindowsElement)this.openScheduleTabItem.FindElementByAccessibilityId("txtCostCenter"); }
> }
> 
> ```
> public void EnterValueInFacilityAndDepartment(OpenScheduleDataSet openScheduleDataSet)
> {
> 	this.FacilityTextBox.Clear();
> 	this.FacilityTextBox.CustomSendKeys(openScheduleDataSet.Trunk);
> 
> 	this.DepartmentTextBox.Clear();
> 	this.DepartmentTextBox.SendKeys(openScheduleDataSet.Branch);
> 
> }
> ```

ok, I how many machines they are failing, can you check if the text size is same is 100% in all the machines

**Comment by yatheesh1989** [comment]
> > > I always get the response if the UI is not ready, also can you share the code
> > 
> > 
> > Here we are first getting elements then we are trying to enter text on that below is the example what we are using and we are facing unknown error exception on remote end
> > And we able to execute the same code local without issue but while testing remotely the unknown error throws. here we are using 6 test machine and executing tests parallel and we are launching local default ip and port of winappdriver.
> > Is the unknown exception on remote end is due to using default IP and port in remote machine?
> > If yes how we can manage multiple remote machine to use winappdriver for parallel tests in remote?
> > Sample Code:
> > private WindowsElement FacilityTextBox
> > {
> > get { return (WindowsElement)this.openScheduleTabItem.FindElementByAccessibilityId("txtFacility"); }
> > }
> > private WindowsElement DepartmentTextBox
> > {
> > get { return (WindowsElement)this.openScheduleTabItem.FindElementByAccessibilityId("txtCostCenter"); }
> > }
> > ```
> > public void EnterValueInFacilityAndDepartment(OpenScheduleDataSet openScheduleDataSet)
> > {
> > 	this.FacilityTextBox.Clear();
> > 	this.FacilityTextBox.CustomSendKeys(openScheduleDataSet.Trunk);
> > 
> > 	this.DepartmentTextBox.Clear();
> > 	this.DepartmentTextBox.SendKeys(openScheduleDataSet.Branch);
> > 
> > }
> > ```
> 
> ok, I how many machines they are failing, can you check if the text size is 100% in all the machines

@anunay1 in all machines we are getting the same error
