### ISSUE TITLE
Can't run UI tests on virtual machine from Pipeline Azure Devops

### ISSUE THREAD

**Issue by leticiafer** [microsoft/WinAppDriver#1279]
I was trying to run several tests from Azure pipeline on machine that isn't connected to a monitor (virtual machine in Azure Portal). When a session tries to start and you aren't connected to the computer with a remote desktop connection then an error is produced. If the same code runs and you are connected at the time with a remote desktop connection then there is no error.

My guess would be that WinAppDriver can't launch an app when a PC is inactive. Below is what the console shows.

I've also reproduced this when code runs and tries to open a new session on my laptop (a non-remote machine) while it's locked (windows key + L).

I configured this machine with interactive mode but it doesn't work.

testCalculatorPlus1(testcases.LicenceInvalidTest): Unable to create a new remote session. Please check the server log for more details. Original error: Failed to locate opened application window with appId: Microsoft.WindowsCalculator_8wekyb3d8bbwe!App, and processId: 7148 (WARNING: The server did not provide any stacktrace information)(..)

Caused by: org.openqa.selenium.WebDriverException: Failed to locate opened application window with appId: Microsoft.WindowsCalculator_8wekyb3d8bbwe!App, and processId: 7148 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5.10 seconds
uild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
 System info: host: 'launcher-automa', ip: '10.X.X.X', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
 Driver info: driver.version: WindowsDriver
 sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)

**Comment by anunay1** [comment]
You need to have an interactive session to run test cases with azure, the system cannot be in locked state, and that holds true for any desktop application automation.

**Comment by leticiafer** [comment]
yes, I was in interactive session but I didn't take in count this  
"If you use Remote Desktop to access the computer on which an agent is running with auto-logon, simply closing the Remote Desktop causes the computer to be locked and any UI tests that run on this agent may fail. To avoid this, use the tscon command to disconnect from Remote Desktop. For example:

%windir%\System32\tscon.exe 1 /dest:console"

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#interactive-or-service

Now, it's working 👍 , your comment made me find this solution because I come back searched about interactive mode.

Thanks @anunay1
