### ISSUE TITLE
ms:waitForAppLaunch doesn't take effect, if the server window is in foreground

### ISSUE THREAD

**Issue by krevathi1912** [microsoft/WinAppDriver#1296]
I am automating uwp app using appium + winappdriver.  Elements in our app is taking time to load. So i am using ms:waitForAppLauch capability. This capability does not take effect when the server window is in foreground. Below are the cases

Working Case:

1. Started appium/winappdriver in cmd. Minimized the cmd.

2. Executed the test script with ms:waitForAppLaunch=50

3. App opens. Server takes 50 secs to attach the App session. All elements in the page are loaded and available

Not Working Case:

1. Started appium/winappdriver in cmd.

2. Executed the test script with ms:waitForAppLaunch=50

3. By the time execution begins, brought the server cmd of step-1 to foreground

4. App opens and server attaches the app session immediately, as a result, some elements in the page are not available

Automation tests fails because of this issue. I have to start the server automatically before test execution starts. We are using python programming language

Solutions tried, none helped

1. Started the appium/winappdriver in cmd automatically using subprocess module in python and minimized the cmd window using pygetwindow module in python.

2. Sent the server cmd window to back, by bringing a different window on the desktop foreground.

3. Appium package in python has methods to start() and stop() the appium server. This starts the appium process in the background

I have been banging my head for several days with this issue. Appreciate any help

Ideally the solution1 should work, but it is not working. What is the different in minimizing the window manually and programatically?

What could be the reason for this issue?

**Comment by anunay1** [comment]
WinAppDriver.exe is just a server which listens to https request its does not matter whether the cmd runs in the foreground or in the background. 

1) Does your application have a splash screen?
2) Have you tried with explicit wait?
3) Please share some piece of code? 
4) Also please share the server logs when the test fails.

**Comment by naeemakram** [comment]
Revathi, 
Have you tried to start the WinAppDriver through a PowerShell session instead of other ways you described? 
It is possible to keep the WinAppDriver window minimized. PowerShell script is given below. 

`Start-Process -FilePath "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe" -WindowStyle Minimized`

The idea just came to my mind when I saw your question here. Otherwise I would have responded in the [course](https://www.udemy.com/course/appium-winappdriver-automation-testing/?referralCode=ED22C3A4CE5BB5E22E53) discussion :)

**Comment by krevathi1912** [comment]
@anunay1  and @naeemakram  Really thanks for your response. Tried starting winappdriver/appium server in the powershell session in minimized window, issue continues.
1. Yes, our application have splash screen
2. Yes, I have tried explicit wait, but the driver did not wait and search for element visibility. Below is the code and server log
**Code**
              ```
 import subprocess
		from appium import webdriver
		from selenium.webdriver.support.ui import WebDriverWait
		from selenium.webdriver.support import expected_conditions as EC
		subprocess.Popen(['powershell.exe', 'Start-Process appium.cmd -WindowStyle Minimized'])
		time.sleep(5)
		desired_caps = {}
		desired_caps['platformName'] = 'Windows'
		desired_caps['deviceName'] = 'WindowsPC'
		desired_caps['app'] = '............!App'
		desired_caps['appium:ms:waitForAppLaunch'] = 50
		driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
		wdv = WebDriverWait(driver, 50)
		wdv.until(EC.visibility_of(driver.find_element_by_accessibility_id('LoginPage_Username')))
		driver.find_element_by_accessibility_id('LoginPage_Username').send_keys('testusername')
		time.sleep(5)
		driver.quit()
```

**Server log**
```
[Appium] Welcome to Appium v1.16.0
		[Appium] Appium REST http interface listener started on 0.0.0.0:4723
		[HTTP] --> POST /wd/hub/session
		[HTTP] {"capabilities":{"firstMatch":[{"platformName":"Windows","appium:deviceName":"WindowsPC","appium:app":"...........!App","appium:ms:waitForAppLaunch":50}]},"desiredCapabilities":{"platformName":"Windows","deviceName":"WindowsPC","app":"...........!App","appium:ms:waitForAppLaunch":50}}
		[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Windows","deviceName":"WindowsPC","app":".......!App","appium:ms:waitForAppLaunch":50},null,{"firstMatch":[{"platformName":"Windows","appium:deviceName":"WindowsPC","appium:app":".......!App","appium:ms:waitForAppLaunch":50}]}]
		[debug] [BaseDriver] Event 'newSessionRequested' logged at 1599325708952 (22:38:28 GMT+0530 (India Standard Time))
		[Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["ms:waitForAppLaunch"]
		[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
		[BaseDriver] The capabilities ["deviceName","app"] are not standard capabilities and should have an extension prefix
		[Appium] Appium v1.16.0 creating new WindowsDriver (v1.8.0) session
		[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
		[debug] [BaseDriver]   "platformName": "Windows",
		[debug] [BaseDriver]   "deviceName": "WindowsPC",
		[debug] [BaseDriver]   "app": ".......!App",
		[debug] [BaseDriver]   "ms:waitForAppLaunch": 50
		[debug] [BaseDriver] }
		[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
		[BaseDriver]   ms:waitForAppLaunch
		[BaseDriver] Session created with session id: 2c1f4fb9-6c00-4ad8-80cf-f4381a8c0ad2
		[WinAppDriver] You must use WinAppDriver version 1.2-RC
		[WinAppDriver] Verifying WinAppDriver version 1.2-RC is installed via comparing the checksum.
		[debug] [WinAppDriver] WinAppDriver changed state to 'starting'
		[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
		[WinAppDriver] No old WinAppDrivers seemed to exist
		[WinAppDriver] Spawning WinAppDriver with: 4724/wd/hub
		[WinAppDriver] [STDOUT] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
		[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
		[WinAppDriver] [STDOUT] Press ENTER to exit.
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT] ==========================================
		[WinAppDriver] [STDOUT] GET /wd/hub/status HTTP/1.1
		[WinAppDriver] [STDOUT] Accept: application/json, */*
		[WinAppDriver] [STDOUT] Connection: close
		[WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
		[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
		[WinAppDriver] [STDOUT] User-Agent: appium
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
		[WinAppDriver] [STDOUT] Content-Length: 146
		[WinAppDriver] [STDOUT] Content-Type: application/json
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT] {"build":{"revision":"2002","time":"Wed Oct  2 21:08:40 2019","version":"1.2.1910"},"os":{"arch":"amd64","name":"windows","version":"10.0.18362"}}
		[debug] [WD Proxy] Got response with status 200: {"build":{"revision":"2002","time":"Wed Oct  2 21:08:40 2019","version":"1.2.1910"},"os":{"arch":"amd64","name":"windows","version":"10.0.18362"}}
		[WinAppDriver] Status call returned 200. we're online and ready to run tests
		[debug] [WinAppDriver] WinAppDriver changed state to 'online'
		[debug] [WinAppDriver] Starting WinAppDriver session. Will timeout in '20000' ms.
		[debug] [WD Proxy] Matched '/session' to command name 'createSession'
		[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"Windows","deviceName":"WindowsPC","app":".......!App","ms:waitForAppLaunch":50}}
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT] ==========================================
		[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
		[WinAppDriver] [STDOUT] Accept: application/json, */*
		[WinAppDriver] [STDOUT] Connection: close
		[WinAppDriver] [STDOUT] Content-Length: 139
		[WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
		[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
		[WinAppDriver] [STDOUT] User-Agent: appium
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT] {"desiredCapabilities":{"platformName":"Windows","deviceName":"WindowsPC","app":".......!App","ms:waitForAppLaunch":50}}
		[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
		[WinAppDriver] [STDOUT] Content-Length: 162
		[WinAppDriver] [STDOUT] Content-Type: application/json
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT] {"sessionId":"83806B86-14AF-49F9-9AEC-567C5E5EAB27","status":0,"value":{"app":".......!App","ms:waitForAppLaunch":50,"platformName":"Windows"}}
		[debug] [WD Proxy] Got response with status 200: {"sessionId":"83806B86-14AF-49F9-9AEC-567C5E5EAB27","status":0,"value":{"app":".......!App","ms:waitForAppLaunch":50,"platformName":"Windows"}}
		[WD Proxy] Determined the downstream protocol as 'MJSONWP'
		[Appium] New WindowsDriver session created successfully, session 2c1f4fb9-6c00-4ad8-80cf-f4381a8c0ad2 added to master session list
		[debug] [BaseDriver] Event 'newSessionStarted' logged at 1599325726765 (22:38:46 GMT+0530 (India Standard Time))
		[debug] [MJSONWP (2c1f4fb9)] Cached the protocol value 'MJSONWP' for the new session 2c1f4fb9-6c00-4ad8-80cf-f4381a8c0ad2
		[debug] [MJSONWP (2c1f4fb9)] Responding to client with driver.createSession() result: {"platformName":"Windows","deviceName":"WindowsPC","app":".......!App","ms:waitForAppLaunch":50}
		[HTTP] <-- POST /wd/hub/session 200 17828 ms - 187
		[HTTP]
		[HTTP] --> POST /wd/hub/session/2c1f4fb9-6c00-4ad8-80cf-f4381a8c0ad2/element
		[HTTP] {"using":"accessibility id","value":"LoginPage_Username","sessionId":"2c1f4fb9-6c00-4ad8-80cf-f4381a8c0ad2"}
		[MJSONWP (2c1f4fb9)] Driver proxy active, passing request on via HTTP proxy
		[debug] [WD Proxy] Matched '/wd/hub/session/2c1f4fb9-6c00-4ad8-80cf-f4381a8c0ad2/element' to command name 'findElement'
		[debug] [WD Proxy] Proxying [POST /wd/hub/session/2c1f4fb9-6c00-4ad8-80cf-f4381a8c0ad2/element] to [POST http://127.0.0.1:4724/wd/hub/session/83806B86-14AF-49F9-9AEC-567C5E5EAB27/element] with body: {"using":"accessibility id","value":"LoginPage_Username","sessionId":"2c1f4fb9-6c00-4ad8-80cf-f4381a8c0ad2"}
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT] ==========================================
		[WinAppDriver] [STDOUT] POST /wd/hub/session/83806B86-14AF-49F9-9AEC-567C5E5EAB27/element HTTP/1.1
		[WinAppDriver] [STDOUT] Accept: application/json, */*
		[WinAppDriver] [STDOUT] Connection: close
		[WinAppDriver] [STDOUT] Content-Length: 108
		[WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
		[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
		[WinAppDriver] [STDOUT] User-Agent: appium
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT] {"using":"accessibility id","value":"LoginPage_Username","sessionId":"2c1f4fb9-6c00-4ad8-80cf-f4381a8c0ad2"}
		[WinAppDriver] [STDOUT] HTTP/1.1 404 Not Found
		[WinAppDriver] [STDOUT] Content-Length: 139
		[WinAppDriver] [STDOUT] Content-Type: application/json
		[WinAppDriver] [STDOUT]
		[WinAppDriver] [STDOUT] {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
		[WD Proxy] Got an unexpected response with status 404: {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
		[debug] [MJSONWP (2c1f4fb9)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 404 - {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
		[debug] [MJSONWP (2c1f4fb9)]     at JWProxy.proxy (C:\Users\.....\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:222:13)
		[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
		[HTTP] <-- POST /wd/hub/session/2c1f4fb9-6c00-4ad8-80cf-f4381a8c0ad2/element 500 278 ms - 164
		[HTTP]
```

**Comment by anunay1** [comment]
If your application has a splash screen then you need to create a session with root and then create a session with the top level window. Check the wiki for more info.

**Comment by naeemakram** [comment]
Why is your WinAppDriver starting in hub mode? I can see the following line in your log files: 
http://127.0.0.1:4724/wd/hub

I believe WinAppDriver must start without the hub.

**Comment by krevathi1912** [comment]
> If your application has a splash screen then you need to create a session with root and then create a session with the top level window. Check the wiki for more info.
> 
> Check the link:
> https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#attaching-to-an-existing-app-window

@anunay1  
I was trying the example given in the link. I am using appium with python for automation.
I am unable to convert below two line of code to python. 
I was trying Keyboard class 

```
desired_caps = {}
desired_caps['platformName'] = 'Windows'
desired_caps['app'] = 'Root'
driver = Keyboard('http://localhost:4723/wd/hub', desired_caps)
driver.press_keycode(....)
```

Really appreciate any help. 
```
DesktopSession.Keyboard.PressKey(OpenQA.Selenium.Keys.Command + "a" + OpenQA.Selenium.Keys.Command)
DesktopSession.Keyboard.SendKeys(Keys.Meta + "s" + Keys.Meta);
```

**Comment by krevathi1912** [comment]
> Why is your WinAppDriver starting in hub mode? I can see the following line in your log files:
> http://127.0.0.1:4724/wd/hub
> 
> I believe WinAppDriver must start without the hub.

Hi Sir,
I started appium server and sent the capabilities. Same issue occurs when winappdriver is used instead of appium. Below is the code and winappdriver log

```
subprocess.Popen(['powershell.exe', 'Start-Process -FilePath "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe" -WindowStyle Minimized'])
time.sleep(5)

desired_caps = {}
desired_caps['platformName'] = 'Windows'
desired_caps['deviceName'] = 'WindowsPC'
desired_caps['app'] = '.........!App'
desired_caps['ms:waitForAppLaunch'] = 50
driver = webdriver.Remote('http://localhost:4723', desired_caps)
driver.find_element_by_accessibility_id('LoginPage_Username').send_keys('testusername')
time.sleep(5)
driver.quit()
```


Windows Application Driver listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.


==========================================
POST /session HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 319
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 0.46 (selenium/3.141.0 (python windows))

{"capabilities": {"firstMatch": [{"platformName": "Windows", "appium:deviceName": "WindowsPC", "appium:app": ".......!App", "ms:waitForAppLaunch": 50}]}, "desiredCapabilities": {"platformName": "Windows", "deviceName": "WindowsPC", "app": ".......!App", "ms:waitForAppLaunch": 50}}
HTTP/1.1 200 OK
Content-Length: 162
Content-Type: application/json

{"sessionId":"89E0E2AE-A79F-40E3-A19A-0D65AE933509","status":0,"value":{"app":".......!App","ms:waitForAppLaunch":50,"platformName":"Windows"}}


==========================================
POST /session/89E0E2AE-A79F-40E3-A19A-0D65AE933509/element HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 113
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 0.46 (selenium/3.141.0 (python windows))

{"using": "accessibility id", "value": "LoginPage_Username", "sessionId": "89E0E2AE-A79F-40E3-A19A-0D65AE933509"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

**Comment by anunay1** [comment]
> > If your application has a splash screen then you need to create a session with root and then create a session with the top level window. Check the wiki for more info.
> > Check the link:
> > https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#attaching-to-an-existing-app-window
> 
> @anunay1
> I was trying the example given in the link. I am using appium with python for automation.
> I am unable to convert below two line of code to python.
> I was trying Keyboard class
> 
> ```
> desired_caps = {}
> desired_caps['platformName'] = 'Windows'
> desired_caps['app'] = 'Root'
> driver = Keyboard('http://localhost:4723/wd/hub', desired_caps)
> driver.press_keycode(....)
> ```
> 
> Really appreciate any help.
> 
> ```
> DesktopSession.Keyboard.PressKey(OpenQA.Selenium.Keys.Command + "a" + OpenQA.Selenium.Keys.Command)
> DesktopSession.Keyboard.SendKeys(Keys.Meta + "s" + Keys.Meta);
> ```

You are using it in a wrong way, the below code should work: 
```
    def setUpClass(self):
        #set up appium
        try:

            desired_caps = {}
            desired_caps["app"] = "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"
            desired_caps["ms:waitForAppLauch"] = 50
            self.driver = webdriver.Remote(
                command_executor='http://127.0.0.1:4723/wd/hub',
                desired_capabilities= desired_caps)
            self.driver.find_element_by_accessibility_id('LoginPage_Username') # this line with throw an exception if there is a splash screen
        except:
            desired_caps = {}
            desired_caps["app"] = "Root"
            self.driver = webdriver.Remote(
                command_executor='htttp://127.0.0.1:4723/wd/hub',
                desired_capabilities = desired_caps
            )

            main_window = self.driver.find_element_by_name("Main window title of your application")
            nativeWindowHandle = main_window.get_attribute("NativeWindowHandle").encode().hex()
            desired_caps = {}
            desired_caps["appTopLevelWindow"] = nativeWindowHandle
            self.driver = webdriver.Remote(
                command_executor='http:127.0.0.1:4723/wd/hub',
                desired_capabilities = desired_caps
            )
```

**Comment by krevathi1912** [comment]
> from codecs import encode, decode

@anunay1  
The code throws below error in the line "nativeWindowHandle = main_window.get_attribute("NativeWindowHandle").encode().hex()"

```
Traceback (most recent call last):
  File "d:/Automation/Mobile/Practice/CompassAttachToExisting.py", line 33, in <module>
    desired_capabilities=desired_caps3
  File "D:\Python37\lib\site-packages\appium\webdriver\webdriver.py", line 144, in __init__
    proxy
  File "D:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\Python37\lib\site-packages\appium\webdriver\webdriver.py", line 219, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "D:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Value was either too large or too small for a UInt32.
```

I understand that the attribute "NativeWindowHandle" gives value in string, which is encoded to bytes and converted to hexadecimal value. Hex value is passed to capability appTopLevelWindow. 
When i ran the code, the value i got for "nativeWindowHandle " is 393835343638. I tried few options of converting the string to hex value, but it doesn't work out. 

```
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"Windows","appTopLevelWindow":"393835343638"}}
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: application/json, */*
[WinAppDriver] [STDOUT] Connection: close
[WinAppDriver] [STDOUT] Content-Length: 85
[WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"desiredCapabilities":{"platformName":"Windows","appTopLevelWindow":"393835343638"}}
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT] Content-Length: 113
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"Value was either too large or too small for a UInt32."}}
[WD Proxy] Got an unexpected response with status 500: {"status":13,"value":{"error":"unknown error","message":"Value was either too large or too small for a UInt32."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[WinAppDriver] Could not start WinAppDriver session error = 'An unknown server-side error occurred while processing the command. Original error: Value was either too large or too small for a UInt32.', attempt = '39' from 'undefined'
```

**Comment by anunay1** [comment]
> > from codecs import encode, decode
> 
> @anunay1
> The code throws below error in the line "nativeWindowHandle = main_window.get_attribute("NativeWindowHandle").encode().hex()"
> 
> ```
> Traceback (most recent call last):
>   File "d:/Automation/Mobile/Practice/CompassAttachToExisting.py", line 33, in <module>
>     desired_capabilities=desired_caps3
>   File "D:\Python37\lib\site-packages\appium\webdriver\webdriver.py", line 144, in __init__
>     proxy
>   File "D:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "D:\Python37\lib\site-packages\appium\webdriver\webdriver.py", line 219, in start_session
>     response = self.execute(RemoteCommand.NEW_SESSION, parameters)
>   File "D:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "D:\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Value was either too large or too small for a UInt32.
> ```
> 
> I understand that the attribute "NativeWindowHandle" gives value in string, which is encoded to bytes and converted to hexadecimal value. Hex value is passed to capability appTopLevelWindow.
> When i ran the code, the value i got for "nativeWindowHandle " is 393835343638. I tried few options of converting the string to hex value, but it doesn't work out.
> 
> ```
> [debug] [WD Proxy] Matched '/session' to command name 'createSession'
> [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"Windows","appTopLevelWindow":"393835343638"}}
> [WinAppDriver] [STDOUT]
> [WinAppDriver] [STDOUT]
> [WinAppDriver] [STDOUT] ==========================================
> [WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
> [WinAppDriver] [STDOUT] Accept: application/json, */*
> [WinAppDriver] [STDOUT] Connection: close
> [WinAppDriver] [STDOUT] Content-Length: 85
> [WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
> [WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
> [WinAppDriver] [STDOUT] User-Agent: appium
> [WinAppDriver] [STDOUT]
> [WinAppDriver] [STDOUT] {"desiredCapabilities":{"platformName":"Windows","appTopLevelWindow":"393835343638"}}
> [WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
> [WinAppDriver] [STDOUT] Content-Length: 113
> [WinAppDriver] [STDOUT] Content-Type: application/json
> [WinAppDriver] [STDOUT]
> [WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"Value was either too large or too small for a UInt32."}}
> [WD Proxy] Got an unexpected response with status 500: {"status":13,"value":{"error":"unknown error","message":"Value was either too large or too small for a UInt32."}}
> [debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
> [WinAppDriver] Could not start WinAppDriver session error = 'An unknown server-side error occurred while processing the command. Original error: Value was either too large or too small for a UInt32.', attempt = '39' from 'undefined'
> ```

In the except block use the below code:
```
 desired_caps = {}
        desired_caps["app"] = "Root"
        desktop = webdriver.Remote(
            command_executor='http://127.0.0.1:4723',
            desired_capabilities=desired_caps
        )



        main_window = desktop.find_element_by_name("YourAppMainWidowTitle")
        nativeWindowHandle = main_window.get_attribute("NativeWindowHandle")
        winHandle = format(int(nativeWindowHandle),'x')

        desired_caps = {}
        desired_caps["appTopLevelWindow"] = winHandle
        self.driver = webdriver.Remote(
            command_executor='http://127.0.0.1:4723',
            desired_capabilities=desired_caps
        )

        self.driver.switch_to.window(winHandle)
```

**Comment by anunay1** [comment]
Did it work?

**Comment by krevathi1912** [comment]
> Did it work?

@anunay1  Yes, its working, i did some changes to work for my issue. Really thanks a lot.
Just analysed that elements in our app is not loading, only when it is opened through appium/winappdriver. 
So i opened our app, using subprocess.popen, created appium driver session using 'Root', got our app native handle, created appium driver session with appTopLevelWindow.  Below is the code

```
subprocess.Popen(['powershell.exe', 'App to opened'])
desired_caps = {}
desired_caps["platformName"] = "Windows"
desired_caps["app"] = "Root"
driver = webdriver.Remote(
    command_executor='http://127.0.0.1:4723/wd/hub',
    desired_capabilities=desired_caps)
print('Appium handles ', driver.window_handles)
appWindow = driver.find_element_by_name('Our app title')
appWindowHandle = appWindow.get_attribute("NativeWindowHandle")
winHandle = format(int(appWindowHandle), 'x')
desired_caps3 = {}
desired_caps3["platformName"] = "Windows"
desired_caps3["appTopLevelWindow"] = winHandle
driver3 = webdriver.Remote(
    command_executor='http://127.0.0.1:4723/wd/hub',
    desired_capabilities=desired_caps3
)
driver3.switch_to.window(winHandle)
driver3.find_element_by_accessibility_id('LoginPage_Username').send_keys('test11111')
driver3.close_app()
```

Again really thanks a lot
