### ISSUE TITLE
Launching application using application parameters

### ISSUE THREAD

**Issue by siddhantjainibi** [microsoft/WinAppDriver#1323]
I have an application which we launch manually using some parameters. We first create a shortcut of the .exe application and then under properties -> target we add " /MANUAL /VERBOSE" in the end. Is it possible to launch in this particular way using WinAppDriver setCapabilities?

I have tried:
cap.setCapability("appArguments", "/MANUAL /VERBOSE"); 

but it does not seem to launch the application.

**Comment by anunay1** [comment]
Launch the application using Process.Start and start the session with the opened application, that should work.

**Comment by siddhantjainibi** [comment]
Thank you for your reply.

Any idea how can I do that using Selenium + Java?

**Comment by anunay1** [comment]
start the exe using the below
 Process process = new ProcessBuilder("Your exe with arguments").start();

then create a session with the opened application: 

```
DesiredCapabilities capabilities = new DesiredCapabilities();
					capabilities.setCapability("app", "Root");
					desktopsession = new WindowsDriver<WindowsElement>(new
					URL(WindowsApplicationDriverUrl),capabilities);


					String topWindow = desktopsession.findElementByClassName("Your application").getAttribute("NativeWindowHandle");
					int MAWinHandleInt = Integer.parseInt(topWindow);
					String MAWinHandleHex = Integer.toHexString(MAWinHandleInt);

					DesiredCapabilities caps = new DesiredCapabilities();
					caps.setCapability("appTopLevelWindow", MAWinHandleHex);
					session = new WindowsDriver<WindowsElement>(new URL(WindowsApplicationDriverUrl), caps);
```

**Comment by bwomsm1** [comment]
@anunay1 @siddhantjainibi I am trying to launch my Appium test with multiple arguments, but its just not working:
```
from appium.webdriver import Remote
from time import sleep

def main():
    dc = {
        'app': 'C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Rte\\EngineManager.exe',
        'platformName': 'Windows',
        'platformVersion': '10',
        'automationName': 'Windows',
        'appArguments': "C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Config\\ShellLayout.xml C:\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Config\\ShellCnf.xml",
    }
    driver = Remote('127.0.0.1:4723', dc)
    sleep(5)

    print(driver.page_source)

if __name__ == '__main__':
    main()
```

Any idea how I can solve it?

**Comment by Shakevg** [comment]
As proposed by @anunay1 Launch the application using Process.Start and start the session with the opened application using [the title or process name](https://github.com/microsoft/WinAppDriver/issues/1656#issuecomment-999872116), that should work.
c# https://stackoverflow.com/questions/7008647/running-exe-with-parameters/7008741
java https://stackoverflow.com/questions/7134486/how-to-execute-command-with-parameters

**Comment by liljohnak** [comment]
@bwomsm1 did it this morning.  Your path argument needs th be in quotes.

`"\"c:\\somePath\""`

**Comment by bwomsm1** [comment]
> @bwomsm1 did it this morning. Your path argument needs to be in quotes.
> 
> `"\"c:\\somePath\""`

Thanks @liljohnak, but I also tried this convention with the quotes, did not work either.
I am really stuck here.

**Comment by bwomsm1** [comment]
> @bwomsm1 did it this morning. Your path argument needs th be in quotes.
> 
> `"\"c:\\somePath\""`

I tried adding quotes for each of the params, and for both of them too.
`"appArguments" = "\"c:\\file_1\"" "\"c:\\file_2\""`
Or 
`"appArguments" = "\"c:\\file_1 c:\\file_2\""`

Nothing worked.

**Comment by liljohnak** [comment]
@bwomsm1 did you try it this way?  Double quotes around each file path, and a space between each argument.
`"appArguments" = "\"c:\\file_1\" \"c:\\file_2\""`

**Comment by bwomsm1** [comment]
> @bwomsm1 did you try it this way? Double quotes around each file path, and a space between each argument. `"appArguments" = "\"c:\\file_1\" \"c:\\file_2\""`

Thanks @liljohnak , 
I also tried this option, the app did launch but the arguments did not pass correctly to the launch. 
The app was launched like there were no arguments passing.

**Comment by bwomsm1** [comment]
@liljohnak @Shakevg @anunay1,
I think we have a real issue here, I can't find a workarounds also. (tried launching a shortcut link with the needed params but it did not help)

**Comment by bwomsm1** [comment]
@liljohnak @Shakevg @anunay1 after gathering all your comments and advices, I left with the following error:
```
Content-Length: 659
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 1.2.0 (selenium/3.141.0 (python windows))
X-Idempotency-Key: 67b13839-4b51-4e74-a777-2c2e81fe8c19

{"capabilities": {"firstMatch": [{"appium:app": "C:\\AeroScoutEngineManager\\bin\\Rte\\EngineManager.exe", "platformName": "Windows", "appium:platformVersion": "10", "appium:automationName": "Windows", "appium:appArguments": "\"c:\\AeroScoutEngineManager\\bin\\Config\\ShellLayout.xml\" \"c:\\AeroScoutEngineManager\\bin\\Config\\ShellCnf.xml\""}]}, "desiredCapabilities": {"app": "C:\\AeroScoutEngineManager\\bin\\Rte\\EngineManager.exe", "platformName": "Windows", "platformVersion": "10", "automationName": "Windows", "appArguments": "\"c:\\AeroScoutEngineManager\\bin\\Config\\ShellLayout.xml\" \"c:\\AeroScoutEngineManager\\bin\\Config\\ShellCnf.xml\""}}
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at AeroScout.Utils.XmlConfig.LoadConfFile(String fileName)
   at AeroScout.Utils.XmlConfig.SetFile(String fileName)System.NullReferenceException: Object reference not set to an instance of an object.
   at AeroScout.Shell.ShellHostsDataModel.ShellCnf.SetAppsCnf()System.NullReferenceException: Object reference not set to an instance of an object.
   at AeroScout.Shell.ShellHostsDataModel.ShellCnf.SetAppsCnf()HTTP/1.1 200 OK
Content-Length: 321
Content-Type: application/json

{"sessionId":"C8AC04F9-F5E4-489D-875F-CE415D88869B","status":0,"value":{"app":"C:\\AeroScoutEngineManager\\bin\\Rte\\EngineManager.exe","appArguments":"\"c:\\AeroScoutEngineManager\\bin\\Config\\ShellLayout.xml\" \"c:\\AeroScoutEngineManager\\bin\\Config\\ShellCnf.xml\"","platformName":"Windows","platformVersion":"10"}}


==========================================
GET /session/C8AC04F9-F5E4-489D-875F-CE415D88869B/source HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 1.2.0 (selenium/3.141.0 (python windows))


HTTP/1.1 200 OK
Content-Length: 604
Content-Type: application/json

{"sessionId":"C8AC04F9-F5E4-489D-875F-CE415D88869B","status":0,"value":"<?xml version=\"1.0\" encoding=\"utf-16\"?><Pane AcceleratorKey=\"\" AccessKey=\"\" AutomationId=\"\" ClassName=\"\" FrameworkId=\"Win32\" HasKeyboardFocus=\"False\" HelpText=\"\" IsContentElement=\"False\" IsControlElement=\"False\" IsEnabled=\"False\" IsKeyboardFocusable=\"False\" IsOffscreen=\"False\" IsPassword=\"False\" IsRequiredForForm=\"False\" ItemStatus=\" [...]
```

**Comment by bwomsm1** [comment]
@liljohnak @anunay1 @Shakevg 
I managed to solved it bit differently, that by using `appWordkingDir`:
```
    dc = {
        'app': App,
        'platformName': 'Windows',
        'platformVersion': '10',
        'automationName': 'Windows',
        "appArguments": "ShellLayout.xml ShellCnf.xml",
        'appWorkingDir': "c:\\AeroScoutEngineManager\\bin\\Config\\"
    }
```
