### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by MikimotoH** [microsoft/WinAppDriver#1331]
I git clone microsoft/WinAppDriver, and then open WinAppDriver/Samples/C#/AlarmClockTestAlarmClockTest.sln;
I got this error in this line:
```
session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
```

| Severity | Code | Description | Project | File | Line | Suppression State|
|----------|-------|--------------|---------|------|-----|---------------------|
| Error      |CS1503 | Argument 1: cannot convert from 'System.Uri' to 'OpenQA.Selenium.Appium.AppiumOptions' | 	AlarmClockTest | C:\work\WinAppDriver\Samples\C#\AlarmClockTest\AlarmClockSession.cs | 53 | Active |

My Nuget Packages and versions are:

 * Appium.WebDriver 4.2.1
 * Castle.Core 4.4.1
 * Selenium.Support 3.141.0
 * Selenium.WebDriver 3.141.0
 * Newtonsoft.Json 12.0.3

WinAppDriver git version is  a6f3d7b.

**Comment by MikimotoH** [comment]
After I modified DesiredCapabilities to AppiumOptions, then there is no compile error.
```
                var appOpts = new OpenQA.Selenium.Appium.AppiumOptions();
                appOpts.AddAdditionalCapability("app", AlarmClockAppId);
                session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appOpts);
```

However, I encounter OpenQA.Selenium.WebDriverException during run Debug All Tests.
```
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=An unknown error occurred in the remote end while processing the command.
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteTouchScreen.Scroll(ICoordinates where, Int32 offsetX, Int32 offsetY)
   at AlarmClockTest.ScenarioStopwatch.StopwatchLap() in C:\work\WinAppDriver\Samples\C#\AlarmClockTest\ScenarioStopwatch.cs:line 62
```

**Comment by anunay1** [comment]
In the file ScenarioAlarm.cs change line 123 to 

 // Navigate to Alarm tab
            session.FindElementByAccessibilityId("AlarmPivotItem").Click();
