### ISSUE TITLE
Cannot start a session even after succeeding a few times before

### ISSUE THREAD

**Issue by manu-st** [microsoft/WinAppDriver#1373]
It might be related to #1372 but I wanted to provide something I've also discovered. First, I must say I had wished to have access to the source code, I could probably have helped figuring out what the issue is. But without this, I can only provide an analysis of what I observed.

I'm running UI testing using xunit. I've made a collection of tests so that all the UI tests run one after the other. Each UI test always starts the same. Here is the C# code:

```
            var appCapabilities = new DesiredCapabilities ();
            appCapabilities.SetCapability ("app", KnownPaths.GetScoutExecutablePath ());
            appCapabilities.SetCapability ("appArguments", "--some_arguments");
            appCapabilities.SetCapability ("appWorkingDir", "somePath");
            // It would be nice to use the new experimental web driver however it doesn't work when trying to find elementS.
            // See https://github.com/microsoft/WinAppDriver/issues/1284
            appCapabilities.SetCapability ("ms:experimental-webdriver", false);
            appCapabilities.SetCapability ("ms:waitForAppLaunch", 3); // Changing this line change the behavior

            Helpers.ExecuteNoException (() =>
            {
                Session = new WindowsDriver<WindowsElement> (new Uri (WinAppDriverUri), appCapabilities);
            });
            ...
            // Code here to fine the Main Window Handle of my application
            ...
            Session.SwitchTo ().Window (MainWindowHandle);

```

The above code works usually for 2 or 3 times, but on the 4th times, it fails. However it fails differently based on whether or not I'm including the `ms:waitForAppLaunch` or not:

-  if included, my application does not start at all and I get Session set to null and this my call to SwitchTo fails. On the output of WinAppDriver I'm getting the following:
```==========================================

POST /session HTTP/1.1
Accept: application/json, image/png
Content-Length: 241
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"desiredCapabilities":{"app":"c:\\someApps.exe","appArguments":"--some_arguments","appWorkingDir":"C:\\someDir","ms:waitForAppLaunch":"3","platformName":"Windows"}}
HTTP/1.1 500 Internal Error
Content-Length: 195
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: c:\\someApps.exe, and processId: 47452"}}
```
- if not included, my application starts and I get a session but then the call to `Session.SwitchTo ().window` fails for a different reason:
```System.InvalidOperationException : An unknown error occurred in the remote end while processing the command.
      Stack Trace:
           at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
           at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteTargetLocator.Window(String windowHandleOrName)
```
and the winAppDriver outputs this:
```
==========================================

POST /session/16626FB2-892B-44F2-B57F-4B2FF5F5E8E7/window HTTP/1.1
Accept: application/json, image/png
Content-Length: 13
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"name":null}
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}

```

Now here is something else I found. Since my app was not starting, I wondered if it was somehow crashing very early on. So to spy on the launch, I decided to start running `procmon.exe` from SysInternals. And here I was very surprised, I could run my complete test suite without a hickup when using `ms:waitForAppLaunch`. So somehow `procmon.exe` make WinAppDriver works better. This is very bizarre and I could definitely reproduce this consistently.

**Comment by anunay1** [comment]
The maximum timeout for ms:waitForAppLaunch" is only 50 sec.

**Comment by anunay1** [comment]
One usually gets this message if the application has a splash screen: 

{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: c:\\someApps.exe, and processId: 47452"}}

**Comment by manu-st** [comment]
I'm well aware of the splashscreen issue but that's not it. As far as I can tell the app doesn't even launch. This is why I wanted to use `procmon` to confirm my hypothesis it was not launching the app, unfortunately when using procmon it worked. Is there a way to add more tracing/logging to winappdriver to see what is going on?

**Comment by anunay1** [comment]
Unfortunately there isn't any tracing/logging .
