### ISSUE TITLE
"element could not be located" exception in case of application start from code (notepad++)

### ISSUE THREAD

**Issue by sjanisz** [microsoft/WinAppDriver#1404]
Hello,

I am experiencing exception:
```
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=An element could not be located on the page using the given search parameters.
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElement(String by, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElementByAccessibilityId(String selector)
   at Notepad__Test.Program.Main(String[] args) in C:\Users\Szymon\source\repos\Notepad++Test\Program.cs:line 23
```
when starting notepad++.exe application (https://notepad-plus-plus.org/downloads/) from code, if appliction is started before test execution then test is using already opened instance (only one instance can be present) and everything works fine.

Code snippet which im using:
```
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Windows;
using System.Threading;

...

AppiumOptions capabilities = new AppiumOptions();
capabilities.AddAdditionalCapability("app", @"C:\Program Files (x86)\Notepad++\notepad++.exe");
capabilities.AddAdditionalCapability("platformName", "Windows");
WindowsDriver<WindowsElement> session = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723/"), capabilities);
Thread.Sleep(5000);

// This throws exception when notepad++ is started from code, no matters how much time is waited before
session.FindElementByAccessibilityId("TitleBar").Click();

Console.ReadKey();
```

Logs from WinAppDriver.exe server console:

Execution with ERROR logs:
```
==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 167
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{"desiredCapabilities":{"app":"C:\\Program Files (x86)\\Notepad++\\notepad++.exe","platformName":"Windows"},"capabilities":{"firstMatch":[{"platformName":"Windows"}]}}
HTTP/1.1 200 OK
Content-Length: 156
Content-Type: application/json

{"sessionId":"8A5AB88D-B518-441E-8306-F1C5FD0080CF","status":0,"value":{"app":"C:\\Program Files (x86)\\Notepad++\\notepad++.exe","platformName":"Windows"}}


==========================================
POST /session/8A5AB88D-B518-441E-8306-F1C5FD0080CF/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 47
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{"using":"accessibility id","value":"TitleBar"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
```

Execution w/o error logs (additional HTTP POST request for click present at the end):
```
==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 167
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{"desiredCapabilities":{"app":"C:\\Program Files (x86)\\Notepad++\\notepad++.exe","platformName":"Windows"},"capabilities":{"firstMatch":[{"platformName":"Windows"}]}}
HTTP/1.1 200 OK
Content-Length: 156
Content-Type: application/json

{"sessionId":"8F726E27-448A-4335-ACFC-EB021C30507C","status":0,"value":{"app":"C:\\Program Files (x86)\\Notepad++\\notepad++.exe","platformName":"Windows"}}


==========================================
POST /session/8F726E27-448A-4335-ACFC-EB021C30507C/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 47
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{"using":"accessibility id","value":"TitleBar"}
HTTP/1.1 200 OK
Content-Length: 123
Content-Type: application/json

{"sessionId":"8F726E27-448A-4335-ACFC-EB021C30507C","status":0,"value":{"ELEMENT":"42.1509008.3.-2147483647.1509008.-2.0"}}

==========================================

POST /session/8F726E27-448A-4335-ACFC-EB021C30507C/element/42.1509008.3.-2147483647.1509008.-2.0/click HTTP/1.1
Accept: application/json, image/png
Content-Length: 2
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"8F726E27-448A-4335-ACFC-EB021C30507C","status":0}
```

Attached project which ive used for reproduction (console application, only Appium reference added + snippet present before):
[Notepad++Test.zip](https://github.com/microsoft/WinAppDriver/files/5745100/Notepad%2B%2BTest.zip)

I have tried to test UWP Windows 10 Calculator app and i did not experience any issues:
```
AppiumOptions capabilitiesTemp = new AppiumOptions();
capabilitiesTemp.AddAdditionalCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
capabilitiesTemp.AddAdditionalCapability("platformName", "Windows");
WindowsDriver<WindowsElement> sessionTemp = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723/"), capabilitiesTemp);
//Thread.Sleep(2000);
sessionTemp.FindElementByAccessibilityId("num7Button").Click();
```

**Comment by naeemakram** [comment]
Have you tried using the AppiumOption "ms:waitForAppLaunch"?

**Comment by sjanisz** [comment]
I have added:
`capabilities.AddAdditionalCapability("ms:waitForAppLaunch", "25");`

I can see that 25 seconds wait time is being waited and the exception is still thrown after that

**Comment by ahmeterturkmennn** [comment]
Were you able to solve this problem, I have exact the same problem but could not find answer yet.

**Comment by Shakevg** [comment]
[ahmeterturkmennn](https://github.com/ahmeterturkmennn) I will suggest:
- User another locator
- Use WebDriverWait https://www.selenium.dev/documentation/webdriver/waits/
