### ISSUE TITLE
Appium cannot find Infragistics  controls and does not load  application source.

### ISSUE THREAD

**Issue by shivaallani7** [microsoft/WinAppDriver#1414]
```
`from appium import webdriver
import time
desired_caps = {}
desired_caps["app"] = "app.exe"
desired_caps["platformName"] ="Windows"
desired_caps["deviceName"] ="WindowsPC"
driver = webdriver.Remote("http://127.0.0.1:4723", desired_caps)
driver.implicitly_wait(20)
line  10:pane = driver.find_elements_by_xpath("//*")
line 11:pane = driver.find_element_by_xpath("//Pane[@AutomationId='MainCenterPanel']/Pane[@AutomationId='ToolbarParentPanel']/Pane[starts-with(@ClassName,'WindowsForms10')]/Pane[@Name='Search'][@AutomationId='CRMButton']")`
```

line 10 and line 11 in the above gives me the error "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters."

I am able to find the controls with inspect.exe but the Appium cannot load those controls.
Please find the stack trace below:

```
Traceback (most recent call last):
  File "C:\Users\xuser\TST\WindowsAppAutomation\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Users\xuser\TST\WindowsAppAutomation\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\xuser\TST\WindowsAppAutomation\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.
```

**Comment by anunay1** [comment]
does your application have splash screen.

**Comment by shivaallani7** [comment]
> does your application have splash screen.

Yes. It has.

**Comment by anunay1** [comment]
Then you need to create a root session and switch to the opened window check #1296

**Comment by anunay1** [comment]
I have given the solution
