### ISSUE TITLE
WPF Application main screen doesn't open & locating element is failing

### ISSUE THREAD

**Issue by menyp** [Microsoft/WinAppDriver#142]
We are trying to start our WPF application.

1. See below the code we are running I am running:
DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setCapability("app",	genMeth.getValueFromPropFile("appPath"));
			capabilities.setCapability("platformName",	"Windows");
			capabilities.setCapability("deviceName",	"WindowsPC");
			driver = new RemoteWebDriver(new URL("http://0.0.0.0:4723/wd/hub"),capabilities);
			driver.findElementById("BtnSignIn").click();

**2 possible issues here:**
First- our app is open on the bottom task bar instead of displaying on the main view.
Second-
2. Once the code attempts to find the signin button in order to click it **it fails** (see below log).

The button id was taken from the inspector & it is a valid automation id:
![screen shot 2017-02-08 at 15 41 37](https://cloud.githubusercontent.com/assets/8288593/22741450/f4791170-ee1b-11e6-982a-ce6f1ea5c2fd.png)

Is this a known issue for WPF applications or are we doing something wrong?

Thanks!

See full log:
===================================
C:\Windows\system32>appium
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows","deviceName":"WindowsPC"},{},{"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}},null,null]
[Appium] Creating new WindowsDriver (v0.3.0) session
[Appium] Capabilities:
[Appium]   app: 'C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe'
[Appium]   platformName: 'Windows'
[Appium]   deviceName: 'WindowsPC'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
[BaseDriver] Session created with session id: db152559-f312-438e-8035-4403186ff726
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[debug] [WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4823 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: undefined 4823/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver Beta listening for requests at: http://127.0.0.1:4823/wd/hub
[debug] [WinAppDriver] WinAppDriver changed state to 'online'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4823/wd/hub/session] with body: {"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows","deviceName":"WindowsPC"}}
[WinAppDriver] [STDOUT] Press ENTER to exit.
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 139
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4823
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] SessionManager - Creating session
[WinAppDriver] [STDOUT] SessionManager - WinAppDriver succeeded loading MitaBroker
[WinAppDriver] [STDOUT] SessionManager - Application launched
[WinAppDriver] [STDOUT] SessionManager - Session successfully created: 14F647CB-46FF-4861-B155-45F693C18580
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 162
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"sessionId":"14F647CB-46FF-4861-B155-45F693C18580","status":0,"value":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows"}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"14F647CB-46FF-4861-B155-45F693C18580","status":0,"value":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows"}}
[Appium] New WindowsDriver session created successfully, session db152559-f312-438e-8035-4403186ff726 added to master session list
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows","deviceName":"WindowsPC"}
[HTTP] <-- POST /wd/hub/session 200 6115 ms - 187
[HTTP] --> POST /wd/hub/session/db152559-f312-438e-8035-4403186ff726/element {"using":"id","value":"BtnSignIn"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/db152559-f312-438e-8035-4403186ff726/element] to [POST http://127.0.0.1:4823/wd/hub/session/14F647CB-46FF-4861-B155-45F693C18580/element] with body: {"using":"id","value":"BtnSignIn"}
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/14F647CB-46FF-4861-B155-45F693C18580/element HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 34
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4823
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] HTTP/1.1 404 Not Found
[WinAppDriver] [STDOUT] Content-Length: 139
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}} ProxyRequestError: Could not proxy command to remote server. Original error: 404 - {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:127:13)
    at tryCatch (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/db152559-f312-438e-8035-4403186ff726/element 500 107 ms - 202

**Comment by yodurr** [comment]
First place to look is double check you're finding by AccessibilityID and not ID.  

| Locator Strategy 	| Client API                   	| Matched Attribute                      	|
|------------------	|------------------------------	|----------------------------------------	|
| accessibility id 	| FindElementByAccessibilityId 	| AutomationId                           	|
| class name       	| FindElementByClassName       	| ClassName                              	|
| id               	| FindElementById              	| RuntimeId (decimal)                    	|
| name             	| FindElementByName            	| Name                                   	|
| tag name         	| FindElementByTagName         	| LocalizedControlType (upper camel case)	|

**Comment by menyp** [comment]
Thanks Y,
I will check it tomorrow.
Any solution regard the fact that the app doesn't prompt to foreground?

**Comment by yodurr** [comment]
A couple questions
1) if you open the app by traditional launching of it on that same machine (with no ui test involved) is it opening in the size and position you desire?
2) does your app expect any command line parameters to get passed to it?  Do you typically launch with a shortcut that contains parameters?

**Comment by menyp** [comment]
1. Launching our app manually opens it on the login screen & it will open in full size of the screen.
2. No, it will just open on login as mention.
Do notice that on the past when I gave winium a test drive & it did opened in full screen manner as desired.

**Comment by menyp** [comment]
Hi Y,
Wanted to use the FindElementByAccessibilityId as suggested however RemoteWebDriver class lack this method.
So I tried to use the iOSDriver class which includes the FindElementByAccessibilityId  however since I am running on Windows with no xcode, the initiate of the driver fails with the "Error: Command 'xcode-select' not found". (see below log)

Any assistant that will help us to jump start our windows automation will be most appreciated.
========================================================
Log . with IOSDriver

(c) 2015 Microsoft Corporation. All rights reserved.

C:\Windows\system32>appium &
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"iOS","deviceName":"WindowsPC"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"iOS","deviceName":"WindowsPC"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"iOS","deviceName":"WindowsPC"},{},{"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"iOS","deviceName":"WindowsPC"},"requiredCapabilities":{}},null,null]
[Appium] Creating new IosDriver (v1.15.3) session
[Appium] Capabilities:
[Appium]   app: 'C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'WindowsPC'
[debug] [iOS] IosDriver version: 1.15.3
[BaseDriver] Session created with session id: 9d90832e-41ce-4978-96e9-b15e033980cb
[Xcode] Finding XcodePath by symlink because Error: Command 'xcode-select' not found. Is it installed?
[Xcode] Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
[debug] [iOS] Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (lib/xcode.js:79:9)
    at tryCatch (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (lib/xcode.js:79:9)
    at tryCatch (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[iOS] Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
[MJSONWP] Encountered internal error running command: Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (lib/xcode.js:79:9)
    at tryCatch (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 386 ms - 257
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"iOS","deviceName":"WindowsPC"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"iOS","deviceName":"WindowsPC"},{},null,null,null]
[Appium] Creating new IosDriver (v1.15.3) session
[Appium] Capabilities:
[Appium]   app: 'C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'WindowsPC'
[debug] [iOS] IosDriver version: 1.15.3
[BaseDriver] Session created with session id: 260618fd-a4d8-4656-bb87-f0b25456889c
[debug] [iOS] Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (lib/xcode.js:79:9)
    at tryCatch (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (lib/xcode.js:79:9)
    at tryCatch (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[iOS] Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
[MJSONWP] Encountered internal error running command: Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
    at getPathFromSymlink$ (lib/xcode.js:79:9)
    at tryCatch (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\VMUser\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 92 ms - 257
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"iOS","deviceName":"WindowsPC"},"requiredCapabilities":{}}}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["capabilities"]
[HTTP] <-- POST /wd/hub/session 400 8 ms - 171

**Comment by khouzam** [comment]
Can you try the WindowsDriver class. Appium and the .NETDriver have been updated to know about Windows.

**Comment by yodurr** [comment]
@menyp I don't know why your app would not open the same way as launching it from the start menu.  Please switch to the WindowsDriver class as Gilles mentioned, then we can investigate whatever bugs remain.

Here's an example using the WindowsDriver:
https://github.com/Microsoft/WinAppDriver/blob/master/Samples/C%23/NotepadTest/AdvancedScenario.cs
