### ISSUE TITLE
"OpenQA.Selenium.WebDriverException" exception thrown sometimes when trying to locate elements by WinAppDriver 

### ISSUE THREAD

**Issue by zahraazezo** [microsoft/WinAppDriver#1467]
Sometimes my automated application runs fast and sometimes it takes very long time to locate elements and at the end it throws this exception :
 
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session/C31E5E62-EB73-4392-A659-063F46FE1F11/element timed out after 60 seconds.
  Source=Appium.Net
  StackTrace:
   at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElement(String by, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElementByAccessibilityId(String selector)
   at ...

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
WebException: The request was aborted: The operation has timed out.
---------------------

private WindowsDriver<WindowsElement> GetCurrentDriver()
        {
            var appiumOptions = new AppiumOptions();

            appiumOptions.AddAdditionalCapability("app", "Root"); // use root to gain access to the entire desktop
            appiumOptions.AddAdditionalCapability("deviceName", "WindowsPC");

            string appSetting = _configurationDriver.Configuration["WindowsApplicationDriverUrl"];
            var remoteAddress = new Uri(appSetting);

            var driver = new WindowsDriver<WindowsElement>(remoteAddress, appiumOptions);

            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(30);

            return driver;
        }

**Comment by zahraazezo** [comment]
I found the answer here 

https://github.com/microsoft/WinAppDriver/issues/196
