### ISSUE TITLE
WAD UI tests pass when running locally and fail when running on Azure VM 

### ISSUE THREAD

**Issue by zahraazezo** [microsoft/WinAppDriver#1506]
When I'm running tests locally using the command > vstest.console.exe project.UITest.dll
**all the tests pass**
  , but when I'm running the tests generated in the build agent path 
   C:\AZDAgent\_work\3\s\project.UITest\bin\Debug
   using the same command > vstest.console.exe project.UITest.dll 
   all the tests fail and the below exception thrown , any explanation ?

OpenQA.Selenium.WebDriverException: An element could not be located on the page using the given search parameters.
TestCleanup method project.UITest.Features.CarePathwaysFeature.TestTearDown threw exception. OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: An element could not be located on the page using the given search parameters..
  Stack Trace:
      at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElement(String by, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElementByAccessibilityId(String selector)

**Comment by zahraazezo** [comment]
I found that my installed App on VM is corrupted
