### ISSUE TITLE
Using .perform() on Actions in Node.js causes "Unrecognized command: actions"

### ISSUE THREAD

**Issue by JohnnyMnemonick** [microsoft/WinAppDriver#1509]
I’m trying to automate MS Word with WinAppDriver, so far I’ve been able to proceed with the most of the test flow but double clicking just doesn’t seem to work.
I’m using Node.js with Appium and trying to Double Click with Actions:

> let e = await driver.findElement(By2.nativeName("This PC"));
> await driver.actions().doubleClick(e).perform();

..but it produces error: _**(node:21168) UnhandledPromiseRejectionWarning: UnknownCommandError: Unrecognized command: actions**_

Which is odd because Actions object is obtained ok with this line:
>let a = driver.actions();
![unnamed](https://user-images.githubusercontent.com/83398816/116530188-1833e080-a921-11eb-9b74-37d029b5dc42.png)

**However trying to actually perform the action**:
>await a. doubleClick (e).perform();

**causes the error**:
(node:4232) UnhandledPromiseRejectionWarning: UnknownCommandError: Unrecognized command: actions

    at buildRequest (c:\Testing\WinApp\node_modules\selenium-webdriver\lib\http.js:477:9)

    at Executor.execute (c:\Testing\WinApp\node_modules\selenium-webdriver\lib\http.js:555:19)

    at WebDriver.execute (c:\Testing\WinApp\node_modules\selenium-webdriver\lib\webdriver.js:731:38)

    at processTicksAndRejections (internal/process/task_queues.js:93:5)

    at async Actions.perform (c:\Testing\WinApp\node_modules\selenium-webdriver\lib\input.js:886:7)

    at async c:\Testing\WinApp\Test.js:33:5

**Comment by Tree55Topz** [comment]
Try without using actions.

```
session.Mouse.MouseMove(element.Coordinates);
session.Mouse.DoubleClick(null);
```

**Comment by JohnnyMnemonick** [comment]
Thank you, Tree55Topz, however the code you provided is in **C#** and as I stated before I'm using **Node.js**
I don't even have **session**, but anyway I tried this:
> let e = await driver.findElement(By2.nativeName("This PC"));
>driver.Mouse.MouseMove(e.coordinates);
>driver.Mouse.DoubleClick(null);

**and it gave me**:
>(node:26508) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'MouseMove' of undefined

So my question still remains: how can I achieve this with **Node.js** and **selenium-appium** ?
>const { driver, By2, windowsAppDriverCapabilities } = require("selenium-appium");
How can I import this **session** ?
...and what I was doing wrong in my original code that it complained about 
>(node:4232) UnhandledPromiseRejectionWarning: UnknownCommandError: Unrecognized command: actions

**Comment by chuchaustad** [comment]
We automated a Legacy Win32 app successfully using C# and Windriver App. Everything was ok till we had to port our solution to Node.js using Typescript. Initial setup was ok but at this point we are also stuck.

`await driver.actions({ async: true, bridge: true }).move({ x: 10, y: 10, origin: element }).perform();`

The exeption we are facing is 

`C:\workspace\node_modules\selenium-webdriver\lib\http.js:477
  throw new error.UnknownCommandError(
        ^
UnknownCommandError: Unrecognized command: actions
    at buildRequest (C:\workspace\node_modules\selenium-webdriver\lib\http.js:477:9)
    at Executor.execute (C:\workspace\node_modules\selenium-webdriver\lib\http.js:556:19)
    at WebDriver.execute (C:\workspace\node_modules\selenium-webdriver\lib\webdriver.js:731:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Actions.perform (C:\workspace\node_modules\selenium-webdriver\lib\input.js:878:5)
    at async Test.mainFormWindow (C:\workspace\src\Test.ts:49:11)
    at async Test.test (C:\workspace\src\Test.ts:27:7) {
  remoteStacktrace: '''`


our package.json looks like this 

`{
  "name": "workspace",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.15.7",
    "@babel/core": "^7.15.5",
    "@babel/preset-env": "^7.15.6",
    "@types/node": "^16.10.1",
    "@types/selenium-webdriver": "^4.0.15",
    "@typescript-eslint/parser": "^4.32.0",
    "eslint": "^7.32.0",
    "selenium-appium": "^1.0.2",
    "selenium-webdriver": "^4.0.0-rc-1",
    "ts-node": "^10.2.1",
    "tslib": "^2.3.1",
    "typescript": "^4.4.3"
  }
}`


any suggestion? pls.
