### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app="location", platformName=Windows, deviceName=WindowsPC}]

### ISSUE THREAD

**Issue by nabilalakhani** [microsoft/WinAppDriver#1524]
hi
i am trying to automate a windows app its a .rdp file
even its launching the rdp window but then it throws an error

below is code

`public class TestM {

	private static WindowsDriver jailtrackerapp = null;

	public static String getDate() {
		LocalDate date = LocalDate.now();
		return date.toString();
	}

	@Test
	public static void setUp() {
		try {
			DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setCapability("app", "C:\\Users\\Gamer\\Downloads\\jtrack.rdp");
			capabilities.setCapability("platformName", "Windows");
			capabilities.setCapability("deviceName", "WindowsPC");

			WindowsDriver jailtrackerapp = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
			jailtrackerapp.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	
	public void cleanApp() {
		jailtrackerapp.quit();
		setUp();
	}

	
	public void tearDown() {
		jailtrackerapp.quit();
	}
`

below is the error

[RemoteTestNG] detected TestNG version 6.14.3
[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=C:\Users\Gamer\Downloads\jtrack.rdp, platformName=Windows, deviceName=WindowsPC}], required capabilities = Capabilities [{}]
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-HN5IFF8', ip: '192.168.225.193', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: WindowsDriver
	at io.appium.java_client.remote.AppiumProtocolHandShake.lambda$1(AppiumProtocolHandShake.java:96)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:96)
	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:111)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.windows.WindowsDriver.<init>(WindowsDriver.java:43)
	at jtracer.TestM.setUp(TestM.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

[poms.txt](https://github.com/microsoft/WinAppDriver/files/6487467/poms.txt)

**Comment by anunay1** [comment]
@nabilalakhani again you are making the same mistake for, your application has a splash screen you need to switch to the opened window.

**Comment by nabilalakhani** [comment]
> @nabilalakhani again you are making the same mistake for, your application has a splash screen you need to switch to the opened window.

ok where can i find code for java for that

**Comment by nabilalakhani** [comment]
> @nabilalakhani again you are making the same mistake for, your application has a splash screen you need to switch to the opened window.

i changed my code to below still same error

`	@Test
	public static void setUp() {
		try {
			DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setCapability("app", "C:\\Users\\Gamer\\Downloads\\jtrack.rdp");
			capabilities.setCapability("platformName", "Windows");
			capabilities.setCapability("deviceName", "WindowsPC");

			WindowsDriver jailtrackerapp = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
			jailtrackerapp.switchTo().window(jailtrackerapp.getWindowHandle());
			jailtrackerapp.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}`

**Comment by anunay1** [comment]
What exactly are you trying to achieve, first you started with python and then moved on to java? 
Convert the same logic of python to java.

**Comment by nabilalakhani** [comment]
> What exactly are you trying to achieve, first you started with python and then moved on to java?
> Convert the same logic of python to java.

can i please get ur skype or something where i can show this to u and u suggest me something how can i achieve
i am really begging for help to automate this desktop app
please

**Comment by anunay1** [comment]
we can have a google hangout call anunayathakur1@gmail.com

**Comment by nabilalakhani** [comment]
> we can have a google hangout call [anunayathakur1@gmail.com](mailto:anunayathakur1@gmail.com)

i sent u the hangout from nabilalakhani0@gmail.com
can you please accept

**Comment by nabilalakhani** [comment]
> we can have a google hangout call [anunayathakur1@gmail.com](mailto:anunayathakur1@gmail.com)

helpful person
my doubts resolved
thanks
