### ISSUE TITLE
Unknown Error Status 13 displayed when launching WinAppDriver and Session is not created

### ISSUE THREAD

**Issue by YenikeRaghuRam** [microsoft/WinAppDriver#1564]
Unknown Error Status 13 displayed when launching WinAppDriver and Session is not created

When winApp Driver starts and about to launch application
Unknown Error Status 13 displayed when launching WinAppDriver and Session is not created

WinAppDriver v1.2.1 in use
Windows 10 OS
Windows PC

DesiredCapabilities capabilities = new DesiredCapabilities();

			capabilities.setCapability("app", "CarrierTransicold.ContainerLINK_f951ntetreypt!App");
			capabilities.setCapability("noReset", true);
			capabilities.setCapability("clearSystemFiles", true);
			capabilities.setCapability(MobileCapabilityType.CLEAR_SYSTEM_FILES, true);
			capabilities.setCapability("platformName", "Windows");
			capabilities.setCapability("deviceName", "WindowsPC");
			capabilities.setCapability("platformVersion", "10");
			uwpDriver = new WindowsDriver<WindowsElement>(new URL("http://localhost:" + port), capabilities);

Capabilities

Attaching screenshots as unable to copy from console
![1](https://user-images.githubusercontent.com/81166452/127273001-8bb24c77-4aab-410e-af38-95de7b436fd3.PNG)
![2](https://user-images.githubusercontent.com/81166452/127273007-461521bd-be10-4bfb-a05c-0ac6d6e71a35.PNG)
![3](https://user-images.githubusercontent.com/81166452/127273010-53db6597-fb68-459b-a8a3-7f39d945241a.PNG)
![4](https://user-images.githubusercontent.com/81166452/127273013-aa3d3175-8686-4dae-a8c4-eec82431a501.PNG)

**Comment by anunay1** [comment]
Your application has a splash screen. Read the [FAQ](https://github.com/microsoft/WinAppDriver/blob/master/Docs/FAQ.md)

**Comment by YenikeRaghuRam** [comment]
As in FAQ added thread.sleep(5000) after line
		uwpDriver = new WindowsDriver<WindowsElement>(new URL("http://localhost:" + port), capabilities);

but exception is thrown 

at line
		uwpDriver = new WindowsDriver<WindowsElement>(new URL("http://localhost:" + port), capabilities);


Caused by: org.openqa.selenium.WebDriverException: Failed to locate opened application window with appId: CarrierTransicold.ContainerLINK_f951ntetreypt!App, and processId: 24440 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 16.41 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'IM-LP-951', ip: '192.168.7.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: driver.version: WindowsDriver
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

**Comment by anunay1** [comment]
You have not read the FAQ fully. if your application has a splash screen, then you need to create a root session and switch to the opened window.
