### ISSUE TITLE
WinAppDriver Console Window host doesn't open, but in task manager only WinAppDriver.exe(32 bit) running it shows

### ISSUE THREAD

**Issue by vishnuprakash9845** [microsoft/WinAppDriver#1575]
Automated the UWP application, followed the below steps, In my local its working fine, but in the VM the WinAppDriver is not launching Console Window host and in task manager only WinAppDriver.exe(32 bit) running. So while running the tests it fails giving below error

**Exception Message:**
Error in launching WD Application by method-1 : The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session timed out after 30 seconds. :    at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.Windows.WindowsDriver`1..ctor(Uri remoteAddress, AppiumOptions AppiumOptions, TimeSpan commandTimeout)

Indicates that a command that should have executed properly cannot be supported for some reason. (104)

**_In the Task Manager this how WinAppDriver shows its running without Console Window host._**

![image](https://user-images.githubusercontent.com/24207575/129477440-9af277ee-e2ef-41e1-b812-251671bd8075.png)

=============================================================================

_**But this is how is should have opened the Win App Driver Console Window host when its opened in normal conditions.**_

![image](https://user-images.githubusercontent.com/24207575/129477553-0cbf2d4e-ecd1-4e8c-bf33-f823e00c1430.png)

Please let me know any work around required.
Waiting for responses from winappdriver team. Thank you.

**Comment by Shakevg** [comment]
@vishnuprakash9845 Try to run WinAppDriver from cmd (maybe some error there), also you can check logs in EventViewer.
