### ISSUE TITLE
Getting "Unimplemented Command: xpath locator strategy is not supported" while using XPath locator

### ISSUE THREAD

**Issue by VarunSundaram** [microsoft/WinAppDriver#1606]
The same code when my colleagues are executing in their systems., FindElementByXPath is working as expected on our AUT. However When I am running the same script in my local, I get this below exception. Kindly do the needful. It is working for others But i get this error.

However, when FindElementByName or ID or Link, that is working in my laptop. only XPAth locator has issues.

This works:
windowsDriverUtils.Driver.FindElementByName("MainWindow");

This is not working:
_windowsDriverUtils.Driver.FindElementByXPath($"//Header[@Name='MainWindow']");

Below are something that may be useful for you.
------------------------------------------------------------------------------------------
POST /session/CBFE18D8-0AB2-43A9-A1BB-FB24882C5546/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 56
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{"using":"xpath","value":"//Window[@Name='MainWindow']"}
HTTP/1.1 501 Not Implemented
Content-Length: 62
Content-Type: text/plain; charset=utf-8

Unimplemented Command: xpath locator strategy is not supported
----------------------------------------------------------------------------

stack trace :
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElementByXPath(String xpath)
   at BimElectrical.AdvancedElectricalDesign.Test.UserInterface.Windows.Utilities.WindowsDriverUtils.<>c__DisplayClass5_0.<GetElementByXPath>b__0(WindowsDriver`1 d) in C:\REPOS\Test.UI.Windows\Utilities\WindowsDriverUtils.cs:line 86
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)

Repeating : This xpath locator code is working for my colleagues. not working only for me. All the remaining locators like FindElementByName are working for me.

**Comment by anunay1** [comment]
Which version of windows application driver are you using?

**Comment by VarunSundaram** [comment]
When I checked, I was using ver 1.0.1 in my machine.
Thanks for asking, yes it is not latest. Now I have installed ver 1.2.1 (last release) and it is working as expected.

closing this support ticket. Thank you once again.
