### ISSUE TITLE
WinAppDriver::CommandHandler::Appium::HandleCommandAsMidPoint - Command  is not recognized

### ISSUE THREAD

**Issue by forconz** [microsoft/WinAppDriver#1626]
`_driver.TryFindElementByName("Edit")?.SetImmediateValue("Hello");`

throw a exception:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumWebElement.Execute(String commandName, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumWebElement.SetImmediateValue(String value)

OpenQA.Selenium.WebDriverException:“**Command not recognized: POST: /session/68B3CF86-77AB-4AEF-BF5A-F5C788F57DD1/appium/element/42.23594896.4.54/value**”

Command not recognized: POST: /session/68B3CF86-77AB-4AEF-BF5A-F5C788F57DD1/appium/element/42.23594896.4.54/value

I got a log from WinAppDriver console:
```
POST /session/68B3CF86-77AB-4AEF-BF5A-F5C788F57DD1/appium/element/42.23594896.4.54/value HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 36
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{"value":"Hello"}
### WinAppDriver::CommandHandler::Appium::HandleCommandAsMidPoint - Command  is not recognized
HTTP/1.1 404 Not Found
Content-Length: 174
Content-Type: application/json

{"status":9,"value":{"error":"unknown command","message":"Command not recognized: POST: /session/68B3CF86-77AB-4AEF-BF5A-F5C788F57DD1/appium/element/42.23594896.4.54/value"}}
```

**Comment by anunay1** [comment]
Set Immediate value is not supported. As a workaround you can use check #829
