### ISSUE TITLE
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session/.../element timed out after 60 seconds in Azure DevOps

### ISSUE THREAD

**Issue by dhq-boiler** [microsoft/WinAppDriver#1640]
Hi.

I'm developing a WPF application in C #. And I also made a test project.
I heard that UI testing can be done with WinAppDriver, so I installed WinAppDriver on this project as well.

It works fine locally and passes the test.

However, when I run the test in the Azure DevOps pipeline, there is a 100% chance that the FindElementByAccessibilityId method will time out.

Is there any solution?

This is an extracted test log.
```
2021-11-25 14:52:08.1972|INFO|boilersGraphics.Test.UITests.ExportTest|A
2021-11-25 14:52:08.1972|INFO|boilersGraphics.Test.UITests.ExportTest|B
2021-11-25 14:52:09.5380|INFO|boilersGraphics.Test.UITests.ExportTest|C
2021-11-25 14:52:11.4336|INFO|boilersGraphics.Test.UITests.ExportTest|D
2021-11-25 14:52:13.6268|INFO|boilersGraphics.Test.UITests.ExportTest|E
2021-11-25 14:52:13.8345|INFO|boilersGraphics.Test.UITests.ExportTest|F
2021-11-25 14:52:16.7298|INFO|boilersGraphics.Test.UITests.ExportTest|G
2021-11-25 14:52:17.0813|INFO|boilersGraphics.Test.UITests.ExportTest|H
2021-11-25 14:52:18.8384|INFO|boilersGraphics.Test.UITests.ExportTest|I
OpenQA.Selenium.WebDriverTimeoutException: Timed out after 30 seconds ---> OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session/A88982C5-10D2-4E9B-B501-6284E04F2F96/element timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElement(String by, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElementByAccessibilityId(String selector)
   at boilersGraphics.Test.UITests.ExportTest.<>c.<チェッカーパターンを読み込んでエクスポートする>b__1_0() in D:\a\1\s\boilersGraphics.Test\UITests\ExportTest.cs:line 64
   at boilersGraphics.Test.UITests.AppSession.<>c__DisplayClass5_0.<WaitForObject>b__0(WindowsDriver`1 driver) in D:\a\1\s\boilersGraphics.Test\UITests\AppSession.cs:line 78
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at boilersGraphics.Test.UITests.AppSession.WaitForObject(Func`1 element, Int32 timeout) in D:\a\1\s\boilersGraphics.Test\UITests\AppSession.cs:line 76
2021-11-25 14:53:19.9561|INFO|boilersGraphics.Test.UITests.ExportTest|N
2021-11-25 14:53:19.9561|INFO|boilersGraphics.Test.UITests.ExportTest|O
2021-11-25 14:53:34.6821|INFO|boilersGraphics.Test.UITests.ExportTest|D:\a\1\s\boilersGraphics.Test\bin\Release\ExportTest.jpg
```

Below is the Windows Application Driver log.

```
{"sessionId":"A88982C5-10D2-4E9B-B501-6284E04F2F96","status":0,"value":{"app":"D:\\a\\1\\s\\boilersGraphics.Test\\bin\\Release\\boilersGraphics.exe","platformName":"Windows"}}


==========================================
POST /session/A88982C5-10D2-4E9B-B501-6284E04F2F96/timeouts HTTP/1.1

Accept: application/json, image/png

Content-Length: 32

Content-Type: application/json;charset=utf-8

Host: 127.0.0.1:4723



{"type":"implicit","ms":60000.0}
HTTP/1.1 200 OK

Content-Length: 63

Content-Type: application/json
```

The test code looks like this:

```csharp
using NLog;
using NUnit.Framework;
using OpenQA.Selenium;
using System.IO;
using System.Reflection;
using System.Threading;

namespace boilersGraphics.Test.UITests
{
    [TestFixture]
    public class ExportTest : AppSession
    {
        [Test]
        public void 真っ白なキャンパスをエクスポートする()
        {
            var dir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var exportFilePath = $"{dir}\\ExportTest.jpg";

            try
            {
                session.FindElementByAccessibilityId("Export").Click();
                session.FindElementByAccessibilityId("ExportFileName").SendKeys(exportFilePath);
                session.FindElementByAccessibilityId("PerformExport").Click();
                Thread.Sleep(1000);
                LogManager.GetCurrentClassLogger().Info(exportFilePath);
                Assert.That(File.Exists(exportFilePath), Is.EqualTo(true));
            }
            finally
            {
                File.Delete(exportFilePath);
            }
        }

        [Test]
        public void チェッカーパターンを読み込んでエクスポートする()
        {
            LogManager.GetCurrentClassLogger().Info("A");
            var dir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var loadFilePath = $"{dir}\\XmlFiles\\checker_pattern.xml";
            var exportFilePath = $"{dir}\\ExportTest2.jpg";

            try
            {
                LogManager.GetCurrentClassLogger().Info("B");
                session.FindElementByAccessibilityId("Load").Click();
                LogManager.GetCurrentClassLogger().Info("C");
                session.FindElementByAccessibilityId("1").Click();
                LogManager.GetCurrentClassLogger().Info("D");
                session.Keyboard.SendKeys(Keys.Alt + "N" + Keys.Alt);
                LogManager.GetCurrentClassLogger().Info("E");
                session.Keyboard.SendKeys(Keys.Alt + "N" + Keys.Alt);
                LogManager.GetCurrentClassLogger().Info("F");
                session.FindElementByAccessibilityId("1148").SendKeys(loadFilePath);
                LogManager.GetCurrentClassLogger().Info("G");
                session.FindElementByAccessibilityId("1").Click();

                LogManager.GetCurrentClassLogger().Info("H");
                Thread.Sleep(1000);


                session.FindElementByAccessibilityId("Export").Click();
                LogManager.GetCurrentClassLogger().Info("I");
                Thread.Sleep(1000);
　　　　  //session.FindElementByAccessibilityId("ExportFileName").SendKeys(exportFilePath); will timeout
                this.WaitForObject(() => session.FindElementByAccessibilityId("ExportFileName"), 30).SendKeys(exportFilePath); // will timeout

                // JKLM: not reachable
                LogManager.GetCurrentClassLogger().Info("J");
                session.FindElementByAccessibilityId("PerformExport").Click();
                LogManager.GetCurrentClassLogger().Info("K");
                Thread.Sleep(1000);
                LogManager.GetCurrentClassLogger().Info("L");
                Assert.That(File.Exists(exportFilePath), Is.EqualTo(true));
                LogManager.GetCurrentClassLogger().Info("M");
            }
            finally
            {
                LogManager.GetCurrentClassLogger().Info("N");
                File.Delete(exportFilePath);
                LogManager.GetCurrentClassLogger().Info("O");
            }
        }
    }
}

```

```csharp
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Appium.Windows;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using System;
using System.IO;
using System.Net;
using System.Reflection;

namespace boilersGraphics.Test.UITests
{
    public class AppSession
    {
        // Note: append /wd/hub to the URL if you're directing the test at Appium
        private const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723";
        private static readonly string AppPath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "boilersGraphics.exe");//"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App";

        protected static WindowsDriver<WindowsElement> session;

        [SetUp]
        public static void Setup()
        {
            // Launch Calculator application if it is not yet launched
            if (session == null)
            {
                // Create a new session to bring up an instance of the Calculator application
                // Note: Multiple calculator windows (instances) share the same process Id
                DesiredCapabilities appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("app", AppPath);
                appCapabilities.SetCapability("deviceName", "WindowsPC");
                session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
                Assert.That(session, Is.Not.Null);

                // Set implicit timeout to 1.5 seconds to make element search to retry every 500 ms for at most three times

                session.Manage().Timeouts().ImplicitWait = TimeSpan.FromMinutes(1);

                session.Manage().Window.Maximize();
            }
        }

        [TearDown]
        public static void TearDown()
        {
            // Close the application and delete the session
            if (session != null)
            {
                session.Quit();
                session = null;
            }
        }

        // Wait for an Object to be accessible, use a custom timeout
        public WindowsElement WaitForObject(Func<WindowsElement> element, int timeout)
        {

            WindowsElement waitElement = null;

            try
            {
                var wait = new DefaultWait<WindowsDriver<WindowsElement>>(session)
                {
                    Timeout = TimeSpan.FromSeconds(timeout),
                    PollingInterval = TimeSpan.FromSeconds(1)
                };

                wait.IgnoreExceptionTypes(typeof(WebDriverException));
                wait.IgnoreExceptionTypes(typeof(InvalidOperationException));
                wait.IgnoreExceptionTypes(typeof(StaleElementReferenceException));
                wait.IgnoreExceptionTypes(typeof(NoSuchElementException));
                wait.IgnoreExceptionTypes(typeof(NotFoundException));
                wait.IgnoreExceptionTypes(typeof(WebException));
                wait.IgnoreExceptionTypes(typeof(WebDriverTimeoutException));

                wait.Until(driver =>
                {
                    waitElement = element();

                    return waitElement != null && waitElement.Enabled && waitElement.Displayed;
                });

                return waitElement;

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                Assert.Fail("Failed to WaitForObject.. Check screenshots");
                return waitElement;
            }
        }
    }
}

```

The Azure DevOps pipeline is below.

https://dev.azure.com/dhq-boiler/boiler_s%20Graphics/_build/results?buildId=211&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=b43e2f1a-7264-5403-3201-b91a4dd50274

The source code of this project is below.

https://github.com/dhq-boiler/boiler-s-Graphics

branch is develop.

**Comment by wafnetcore** [comment]
Assuming nothing is wrong on the Azure side, the solution could be a simple finding a way to use the 3rd option of creating the Edge or Chrome driver.  That option tells Selenium how long to wait before timing out.  Is there a way to implement that here?  I'm not sure, but in our environment we got it to work successfully on another unrelated project.

**Comment by dhq-boiler** [comment]
I would like to try the third option of creating an Edge or Chrome driver, can you provide sample code? I googled how to do it, but I didn't understand.

**Comment by wafnetcore** [comment]
I searched for it yesterday (in this framework). Unfortunately I couldn't find any exposed Constructors for either the Edge or Chrome drivers.  I'm new to this framework too, and am not an expert.  Sorry, but for now I don't have a solid answer for you.

**Comment by dhq-boiler** [comment]
I'll just explain what happened!
I added the code to take a screenshot for each process and the test passed.
I don't even know what happened.
The test code is presented below.

```csharp:ExportTest.cs
    [TestFixture]
    public class ExportTest : AppSession
    {
        [Test]
        public void 真っ白なキャンパスをエクスポートする()
        {
            var dir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var exportFilePath = $"{dir}\\ExportTest.jpg";

            try
            {
                GetElementByAutomationID("Export").Click();
                GetElementByAutomationID("filename").SendKeys(exportFilePath);
                GetElementByAutomationID("PerformExport").Click();
                Thread.Sleep(1000);
                LogManager.GetCurrentClassLogger().Info(exportFilePath);
                Assert.That(File.Exists(exportFilePath), Is.EqualTo(true));
            }
            finally
            {
                File.Delete(exportFilePath);
            }
        }

        [Test]
        public void チェッカーパターンを読み込んでエクスポートする()
        {
            LogManager.GetCurrentClassLogger().Info("A");
            var dir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var loadFilePath = $"{dir}\\XmlFiles\\checker_pattern.xml";
            var exportFilePath = $"{dir}\\ExportTest2.jpg";

            try
            {
                try
                {
                    LogManager.GetCurrentClassLogger().Info("B");
                    TakeScreenShot("SCREENSHOT_B.png");
                    session.FindElementByAccessibilityId("Load").Click();
                    LogManager.GetCurrentClassLogger().Info("C");
                    TakeScreenShot("SCREENSHOT_C.png");
                    //「現在のキャンパスは破棄されますが、よろしいですか？」→OK（"1"）
                    session.FindElementByAccessibilityId("1").Click();
                    LogManager.GetCurrentClassLogger().Info("D");
                    TakeScreenShot("SCREENSHOT_D.png");
                    var action = new Actions(session);
                    action.SendKeys(Keys.Alt + "N" + Keys.Alt);
                    action.Perform();
                    LogManager.GetCurrentClassLogger().Info("F");
                    TakeScreenShot("SCREENSHOT_F.png");
                    //ファイル名（コンボボックス、"1148"）に入力
                    GetElementByAutomationID("1148").SendKeys(loadFilePath);
                    LogManager.GetCurrentClassLogger().Info("G");
                    TakeScreenShot("SCREENSHOT_G.png");
                    //開く（O)ボタン（"1")をクリック
                    session.FindElementByAccessibilityId("1").Click(); //ファイル名が全選択状態になる
                    session.FindElementByAccessibilityId("1").Click(); //もう一度クリックが必要
                                                                       //キャンセルボタン("2")をクリック
                                                                       //session.FindElementByAccessibilityId("2").Click();
                }
                finally
                {
                    if (IsElementPresent(By.Name("開く")))
                    {
                        session.FindElementByName("開く").FindElementByAccessibilityId("Close").Click();
                    }
                }

                LogManager.GetCurrentClassLogger().Info("H");
                TakeScreenShot("SCREENSHOT_H.png");
                GetElementByAutomationID("Export").Click();

                Thread.Sleep(5000);

                LogManager.GetCurrentClassLogger().Info("I");
                TakeScreenShot("SCREENSHOT_I.png");
                
                GetElementByAutomationID("filename").SendKeys(exportFilePath);
                
                LogManager.GetCurrentClassLogger().Info("J");
                TakeScreenShot("SCREENSHOT_J.png");
                GetElementByAutomationID("PerformExport").Click();

                LogManager.GetCurrentClassLogger().Info("K");
                TakeScreenShot("SCREENSHOT_K.png");
                Thread.Sleep(1000);
                LogManager.GetCurrentClassLogger().Info("L");
                TakeScreenShot("SCREENSHOT_L.png");
                Assert.That(File.Exists(exportFilePath), Is.EqualTo(true));
                LogManager.GetCurrentClassLogger().Info("M");
                TakeScreenShot("SCREENSHOT_M.png");
            }
            finally
            {
                LogManager.GetCurrentClassLogger().Info("N");
                File.Delete(exportFilePath);
                LogManager.GetCurrentClassLogger().Info("O");
            }
        }
    }
```

```csharp:AppSession.cs
    public class AppSession
    {
        // Note: append /wd/hub to the URL if you're directing the test at Appium
        private const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723";
        private static readonly string AppPath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "boilersGraphics.exe");//"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App";

        protected static WindowsDriver<WindowsElement> session;

        [SetUp]
        public static void Setup()
        {
            // Launch Calculator application if it is not yet launched
            if (session == null)
            {
                // Create a new session to bring up an instance of the Calculator application
                // Note: Multiple calculator windows (instances) share the same process Id
                var options = new AppiumOptions();
                options.AddAdditionalCapability("app", AppPath);
                session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), options);
                Assert.That(session, Is.Not.Null);

                // Set implicit timeout to 1.5 seconds to make element search to retry every 500 ms for at most three times

                //session.Manage().Timeouts().ImplicitWait = TimeSpan.FromMinutes(1);

                session.Manage().Window.Maximize();
            }
        }

        [TearDown]
        public static void TearDown()
        {
            // Close the application and delete the session
            if (session != null)
            {
                session.Quit();
                session = null;
            }
        }

        // Wait for an Object to be accessible, use a custom timeout
        public WindowsElement WaitForObject(Func<WindowsElement> element, int timeout)
        {

            WindowsElement waitElement = null;

            try
            {
                var wait = new DefaultWait<WindowsDriver<WindowsElement>>(session)
                {
                    Timeout = TimeSpan.FromSeconds(timeout),
                    PollingInterval = TimeSpan.FromSeconds(1)
                };

                wait.IgnoreExceptionTypes(typeof(WebDriverException));
                wait.IgnoreExceptionTypes(typeof(InvalidOperationException));
                wait.IgnoreExceptionTypes(typeof(StaleElementReferenceException));
                wait.IgnoreExceptionTypes(typeof(NoSuchElementException));
                wait.IgnoreExceptionTypes(typeof(NotFoundException));
                wait.IgnoreExceptionTypes(typeof(WebException));
                wait.IgnoreExceptionTypes(typeof(WebDriverTimeoutException));

                wait.Until(driver =>
                {
                    waitElement = element();

                    return waitElement != null && waitElement.Enabled && waitElement.Displayed;
                });

                return waitElement;

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                Assert.Fail("Failed to WaitForObject.. Check screenshots");
                return waitElement;
            }
        }

        public WindowsElement GetElementByAutomationID(string automationId, int timeOut = 10000)
        {
            WindowsElement element = null;

            var wait = new DefaultWait<WindowsDriver<WindowsElement>>(session)
            {
                Timeout = TimeSpan.FromMilliseconds(timeOut),
                Message = $"Element with automationId \"{automationId}\" not found."
            };

            wait.IgnoreExceptionTypes(typeof(WebDriverException));

            try
            {
                wait.Until(Driver =>
                {
                    element = Driver.FindElementByAccessibilityId(automationId);
                    return element != null;
                });
            }
            catch (WebDriverTimeoutException ex)
            {
                LogManager.GetCurrentClassLogger().Error(ex);
                LogManager.GetCurrentClassLogger().Error($"automationId:{automationId}");
                Assert.Fail(ex.Message);
            }

            return element;
        }

        public bool IsElementPresent(By by)
        {
            try
            {
                session.FindElement(by);
                return true;
            }
            catch (NoSuchElementException)
            {
                return false;
            }
            catch (WebDriverException)
            {
                return false;
            }
        }

        public void TakeScreenShot(string filename)
        {
            session.GetScreenshot().SaveAsFile($"{AppDomain.CurrentDomain.BaseDirectory}\\{filename}");
            TestContext.AddTestAttachment($"{AppDomain.CurrentDomain.BaseDirectory}\\{filename}");
        }
    }
```

**Comment by wafnetcore** [comment]
That's odd.  But congratulations on finding a circumvention.
