### ISSUE TITLE
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/elements timed out after 60 seconds

### ISSUE THREAD

**Issue by AndriesBoshoff** [microsoft/WinAppDriver#1657]
Using a C# framework to access WinAppDriver to test a dotnet application. A method that is highly used has an intermittent issue that throws the exception in the title. The method usually succeeds, and very seldom it throws this exception, seemingly at random. I was unable to see whether some other process generated a exception around the same time. The WinAppDriver.exe appeared to still be running after the exception.
I've added the **stack trace** of the error and also the **WinAppDriver log** below stack trace.
The line in my code throwing the exception:  AppiumDriver<WindowsElement>.FindElements(By.Xpath(*/*))

2021-12-24 03:50:11.714 +02:00 [ERR] Error in [CloseAnyOpenDialogWindows()] - [OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/elements timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElements(String mechanism, String value)
   at Framework.Harnesses.HarnessBase.CloseAnyOpenDialogWindows() in E:\Framework\Harnesses\HarnessBase.cs:line 79][The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/elements timed out after 60 seconds.]

==========================================
POST /session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/element HTTP/1.1

Accept: application/json, image/png

Content-Length: 32

Content-Type: application/json;charset=utf-8

Host: 127.0.0.1:4723

User-Agent: selenium/3.141.0 (.net windows)

{"using":"name","value":"Error"}
HTTP/1.1 404 Not Found

Content-Length: 139

Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

==========================================
POST /session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/elements HTTP/1.1

Accept: application/json, image/png

Content-Length: 31

Content-Type: application/json;charset=utf-8

Host: 127.0.0.1:4723

User-Agent: selenium/3.141.0 (.net windows)

==========================================
GET /session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/element/42.3343832/text HTTP/1.1

Accept: application/json, image/png

Cache-Control: no-cache

Host: 127.0.0.1:4723

User-Agent: selenium/3.141.0 (.net windows)

HTTP/1.1 200 OK

Content-Length: 101

Content-Type: application/json

{"sessionId":"2494B701-DD35-4CE9-80DF-06B82D2B6C1D","status":0,"value":"Pricing AGMF on 04 Jan 2021"}

==========================================
POST /session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/keys HTTP/1.1

Accept: application/json, image/png

Content-Length: 17

Content-Type: application/json;charset=utf-8

Host: 127.0.0.1:4723

User-Agent: selenium/3.141.0 (.net windows)

==========================================
GET /session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/screenshot HTTP/1.1

Accept: application/json, image/png

Cache-Control: no-cache

Host: 127.0.0.1:4723

User-Agent: selenium/3.141.0 (.net windows)

HTTP/1.1 200 OK

Content-Length: 169738

Content-Type: application/json

gNVq4ZRnnFUNAFXFXjeMrxi24fPVtLV8oa45ln4bNee36Dm9cyaF8K7AZ0sYoa6byReqxa/2UVCq+T4CAAAAAIBAtCw9c2L8GNKweTjt1JJrWAPUFZd6kOwrhAgToloNAL4zecUQLo9Qh+Fnz5bxxcIDMZ232pyJWXqKdNpnVrQdS7+hq+444NBn8MNIIcyJyA0AAAAAAIAZFKwh2KjWXCFEKFWjWg0APvL4KiRcHqEOwzkXI9rlFPdVaa7SLjSxN7mwLHZe36xxrF2yYM5JpXdEwep2kfoMfhgphDkRuQEAAAAAADCDgjUEJ2NNWTgzuqqMm6NUDQDVYP66IRTv6jLsUsXleo/jX7tt4dtt4d9N/YKs4P2xL16xqPfJqYP2pCltsz5o49fVahIphDkRuQEAAAAAADCDgjUEM2ORqBpla2ETlKoBo [...]

==========================================
POST /session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/elements HTTP/1.1

Accept: application/json, image/png

Content-Length: 31

Content-Type: application/json;charset=utf-8

Host: 127.0.0.1:4723

User-Agent: selenium/3.141.0 (.net windows)

{"using":"xpath","value":"*/*"}
HTTP/1.1 200 OK

Content-Length: 63

Content-Type: application/json

{"sessionId":"2494B701-DD35-4CE9-80DF-06B82D2B6C1D","status":0}
HTTP/1.1 200 OK

Content-Length: 195

Content-Type: application/json

{"sessionId":"2494B701-DD35-4CE9-80DF-06B82D2B6C1D","status":0,"value":[{"ELEMENT":"42.394076"},{"ELEMENT":"42.721060"},{"ELEMENT":"42.262778"},{"ELEMENT":"42.262248.2.-2147483647.262248.-2.0"}]}
HTTP/1.1 200 OK

Content-Length: 195

Content-Type: application/json

{"sessionId":"2494B701-DD35-4CE9-80DF-06B82D2B6C1D","status":0,"value":[{"ELEMENT":"42.394076"},{"ELEMENT":"42.721060"},{"ELEMENT":"42.262778"},{"ELEMENT":"42.262248.2.-2147483647.262248.-2.0"}]}

==========================================
GET /session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/element/42.394076/name HTTP/1.1

Accept: application/json, image/png

Cache-Control: no-cache

Host: 127.0.0.1:4723

User-Agent: selenium/3.141.0 (.net windows)

HTTP/1.1 200 OK

Content-Length: 90

Content-Type: application/json

{"sessionId":"2494B701-DD35-4CE9-80DF-06B82D2B6C1D","status":0,"value":"ControlType.Pane"}

==========================================
GET /session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/element/42.721060/name HTTP/1.1

Accept: application/json, image/png

Cache-Control: no-cache

Host: 127.0.0.1:4723

User-Agent: selenium/3.141.0 (.net windows)

HTTP/1.1 200 OK

Content-Length: 90

Content-Type: application/json

{"sessionId":"2494B701-DD35-4CE9-80DF-06B82D2B6C1D","status":0,"value":"ControlType.Pane"}

==========================================
GET /session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/element/42.262778/name HTTP/1.1

Accept: application/json, image/png

Cache-Control: no-cache

Host: 127.0.0.1:4723

User-Agent: selenium/3.141.0 (.net windows)

HTTP/1.1 200 OK

Content-Length: 90

Content-Type: application/json

{"sessionId":"2494B701-DD35-4CE9-80DF-06B82D2B6C1D","status":0,"value":"ControlType.Pane"}

==========================================
GET /session/2494B701-DD35-4CE9-80DF-06B82D2B6C1D/element/42.262248.2.-2147483647.262248.-2.0/name HTTP/1.1

Accept: application/json, image/png

Cache-Control: no-cache

Host: 127.0.0.1:4723

User-Agent: selenium/3.141.0 (.net windows)

HTTP/1.1 200 OK

Content-Length: 94

Content-Type: application/json

{"sessionId":"2494B701-DD35-4CE9-80DF-06B82D2B6C1D","status":0,"value":"ControlType.TitleBar"}

**Comment by Tree55Topz** [comment]
If its intermittent it just means your test code needs some stability improvements. Whatever method you are using to perform this action, just try wrapping it in a while loop that waits for some conditions and include a try catch in there to handle this and retry. 

Also, why not just do

`AppiumDriver.FindElementsByXPath("[xpath code here]")`
