### ISSUE TITLE
Launching WinAppDriver with multiple appArguments not working from appium script

### ISSUE THREAD

**Issue by bwomsm1** [microsoft/WinAppDriver#1673]
My windows application is being launched with 2 arguments files.
I am adding them to the appArguments field in the capabilities, but the app won't launch with them.

**Appium version: 2.0.0-beta.24**
Running appium from CLI.

This is the code which I am trying to execute: 
```
from appium.webdriver import Remote
from time import sleep


def main():
    dc = {
        'app': 'C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Rte\\EngineManager.exe',
        'platformName': 'Windows',
        'platformVersion': '10',
        'automationName': 'Windows',
        'appArguments': "C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Config\\ShellLayout.xml C:\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Config\\ShellCnf.xml",
    }
    driver = Remote('127.0.0.1:4723', dc)
    sleep(5)

    print(driver.page_source)


if __name__ == '__main__':
    main()

```

Appium Logs: 
https://github.com/bwomsm1/AppiumLogs/blob/master/win_app_appium.log

**Comment by anunay1** [comment]
the error shows "Failed to locate opened application window with appId: C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Rte\\EngineManager.exe, and processId: 16796"}}
[35m[WD Proxy][39m Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Rte\\EngineManager.exe, and processId: 16796"}}
[debug] [35m[W3C][39m Matched W3C error code 'unknown error' to UnknownError"

Does your application have a splash screen?

**Comment by bwomsm1** [comment]
Thanks,
No, I don't have a splash screen as far as I understand,
Question,
Do I sends the 2 params to `appArguments` correctly?

**Comment by bwomsm1** [comment]
What I used `appArguments` as follow:
`'appArguments': "\"C://Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Config\\ShellLayout.xml\" \"C:\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Config\\ShellCnf.xml\"",
`
I did not get the error at all, but my application could not be launched because it was missing the arguments.

**Comment by anunay1** [comment]
Can you try with this snippet

```
subprocess.Popen(['powershell.exe', 'App to opened'])
desired_caps = {}
desired_caps["platformName"] = "Windows"
desired_caps["app"] = "Root"
driver = webdriver.Remote(
    command_executor='http://127.0.0.1:4723/wd/hub',
    desired_capabilities=desired_caps)
print('Appium handles ', driver.window_handles)
appWindow = driver.find_element_by_name('Our app title')
appWindowHandle = appWindow.get_attribute("NativeWindowHandle")
winHandle = format(int(appWindowHandle), 'x')
desired_caps3 = {}
desired_caps3["platformName"] = "Windows"
desired_caps3["appTopLevelWindow"] = winHandle
driver3 = webdriver.Remote(
    command_executor='http://127.0.0.1:4723/wd/hub',
    desired_capabilities=desired_caps3
)
driver3.switch_to.window(winHandle)
driver3.find_element_by_accessibility_id('LoginPage_Username').send_keys('test11111')
driver3.close_app()
```

**Comment by bwomsm1** [comment]
@anunay1 I am getting this error:
`selenium.common.exceptions.InvalidArgumentException: Message: 'automationName' can't be blank`

**Comment by bwomsm1** [comment]
When I was running this code:
```
subprocess.Popen(['powershell.exe', 'C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Rte\\EngineManager.exe']) desired_caps = {} desired_caps["platformName"] = "Windows" desired_caps["app"] = "Root" desired_caps["automationName"] = 'Windows' driver = Remote(     command_executor='http://127.0.0.1:4723',     desired_capabilities=desired_caps) print('Appium handles ', driver.window_handles) appWindow = driver.find_element_by_name('Our app title') appWindowHandle = appWindow.get_attribute("NativeWindowHandle") winHandle = format(int(appWindowHandle), 'x') desired_caps3 = {} desired_caps3["platformName"] = "Windows" desired_caps3["appTopLevelWindow"] = winHandle driver3 = Remote(     command_executor='http://127.0.0.1:4723',     desired_capabilities=desired_caps3 ) driver3.switch_to.window(winHandle) driver3.find_element_by_accessibility_id('LoginPage_Username').send_keys('test11111') driver3.close_app()
```
My app did not launch and I was getting that error:
```
"C:\Program Files\Python39\python.exe" C:/workspace/products-automation-framework/test.py
x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:19
+ C:\Program Files (x86)\AeroScout\AeroScout Engine Manager\bin\Rte\Eng ...
+                   ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Appium handles  []
Traceback (most recent call last):
  File "C:\workspace\products-automation-framework\test.py", line 49, in <module>
    test_support()
  File "C:\workspace\products-automation-framework\test.py", line 32, in test_support
    appWindow = driver.find_element_by_name('Our app title')
  File "C:\Users\qahw\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "C:\Users\qahw\AppData\Roaming\Python\Python39\site-packages\appium\webdriver\webdriver.py", line 283, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']
  File "C:\Users\qahw\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\qahw\AppData\Roaming\Python\Python39\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Users\qahw\AppData\Roaming\Python\Python39\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\qahw\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.


Process finished with exit code 1

```

**Comment by anunay1** [comment]
subprocess.Popen(['powershell.exe', '"C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Rte\\EngineManager.exe"'])
