### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'click'

### ISSUE THREAD

**Issue by Anas966** [microsoft/WinAppDriver#1712]
Hello,

While running the python example available here, the following error popup:

`
test_addition (__main__.SimpleCalculatorTests) ... ERROR
test_combination (__main__.SimpleCalculatorTests) ... ERROR
test_division (__main__.SimpleCalculatorTests) ... C:\Users\anas9\PycharmProjects\winappdrivertest\main.py:70: DeprecationWarning: find_element_by_name is deprecated. Please use find_element(by=By.NAME, value=name) instead
  self.driver.find_element_by_name("Eight").click()
ERROR
test_initialize (__main__.SimpleCalculatorTests) ... ERROR
test_multiplication (__main__.SimpleCalculatorTests) ... C:\Users\anas9\PycharmProjects\winappdrivertest\main.py:79: DeprecationWarning: find_element_by_name is deprecated. Please use find_element(by=By.NAME, value=name) instead
  self.driver.find_element_by_name("Nine").click()
ERROR
test_subtraction (__main__.SimpleCalculatorTests) ... C:\Users\anas9\PycharmProjects\winappdrivertest\main.py:86: DeprecationWarning: find_element_by_name is deprecated. Please use find_element(by=By.NAME, value=name) instead
  self.driver.find_element_by_name("Nine").click()
ERROR

======================================================================
ERROR: test_addition (__main__.SimpleCalculatorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\anas9\PycharmProjects\winappdrivertest\main.py", line 51, in test_addition
    self.driver.find_element(By.NAME, "One").click()
AttributeError: 'dict' object has no attribute 'click'

======================================================================
ERROR: test_combination (__main__.SimpleCalculatorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\anas9\PycharmProjects\winappdrivertest\main.py", line 58, in test_combination
    self.driver.find_element(By.NAME, "Seven").click()
AttributeError: 'dict' object has no attribute 'click'

======================================================================
ERROR: test_division (__main__.SimpleCalculatorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\anas9\PycharmProjects\winappdrivertest\main.py", line 70, in test_division
    self.driver.find_element_by_name("Eight").click()
AttributeError: 'dict' object has no attribute 'click'

======================================================================
ERROR: test_initialize (__main__.SimpleCalculatorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\anas9\PycharmProjects\winappdrivertest\main.py", line 45, in test_initialize
    self.driver.find_element(by=By.NAME, value="Clear").click()
AttributeError: 'dict' object has no attribute 'click'

======================================================================
ERROR: test_multiplication (__main__.SimpleCalculatorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\anas9\PycharmProjects\winappdrivertest\main.py", line 79, in test_multiplication
    self.driver.find_element_by_name("Nine").click()
AttributeError: 'dict' object has no attribute 'click'

======================================================================
ERROR: test_subtraction (__main__.SimpleCalculatorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\anas9\PycharmProjects\winappdrivertest\main.py", line 86, in test_subtraction
    self.driver.find_element_by_name("Nine").click()
AttributeError: 'dict' object has no attribute 'click'

----------------------------------------------------------------------
Ran 6 tests in 1.291s

FAILED (errors=6)

`

**Comment by anunay1** [comment]
Did you update the selenium package to version4? Then all the API's in the sample code will not work you need to use Appium.By

**Comment by Anas966** [comment]
> Did you update the selenium package to version4? Then all the API's in the sample code will not work you need to use Appium.By

Thanks, could you please help with an example or link.

**Comment by anunay1** [comment]
Just change all the API of find_element to Appium.By

**Comment by anunay1** [comment]
Check
https://github.com/anunay1/SampleWADPython/tree/master

**Comment by Anas966** [comment]
Thank you 👍

**Comment by chengermu** [comment]
winappdriver didnt work with w3c

**Comment by HelenMMiao** [comment]
I have the same error when using Selenium4, but Selenium3 works fine for me. BTW, I am using Selenium 3.14.0 for WinAppDriver.

**Comment by michalgarcarz** [comment]
Hello Team,

I have exactly same issue. Can not downgrade to Selenium 3.x anymore because i am using appium-python-client 2.2.0 (requiring Selenium 4.x).

I've tried to use Appium.By but it does not help. Code snippet:

```
self.driver.find_element(AppiumBy.NAME, "Clear").click()
```

Returning the error:
```
self.driver.find_element(AppiumBy.NAME, "Clear").click()
AttributeError: 'dict' object has no attribite 'click'
```

Using selenium 4.7.2 now but tested multiple 4.x versions with the same result.

Any hints how to solve this problem ?

Thanks,
Michal
