### ISSUE TITLE
Timeout when starting a session

### ISSUE THREAD

**Issue by yuqizhou77** [microsoft/WinAppDriver#1717]
Hi, 
I got an exception when launch an app saying 
OpenQA.Selenium.WebDriverException: Operation timed out. (Exception from HRESULT: 0x80131505).

at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)

I launched the app using this way 
 AppiumOptions options = new AppiumOptions();
options.AddAdditionalCapability("app", Path.Combine(latestVSPath, DevenvPath));
Session = new WindowsDriver<WindowsElement>(new Uri(ConfigConstants.WindowsApplicationDriverUrl), options)

This error does not always happen, so I am guessing this is probably due to slow performance sometime? 
May I know what the default timeout is and is there any way to reset this timeout? Or is there any better solutions for cases like this?
Thanks!

**Comment by anunay1** [comment]
The default time is 60 seconds.you can use ms experimental wait as capability but the maximum wait for that is 50 Seconds.

**Comment by yuqizhou77** [comment]
> The default time is 60 seconds.you can use ms experimental wait as capability but the maximum wait for that is 50 Seconds.

For the 60 seconds timeout you mentioned above, do you mean the server will wait up to 60 seconds after sending the POST request to create a session before returning a response? What's the difference between this timeout and the ms experimental wait?
