### ISSUE TITLE
Webdriver Exception occured with V1.2.99 but it's working fine V1.22.1

### ISSUE THREAD

**Issue by AmitTiwari094** [microsoft/WinAppDriver#1849]
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(AppiumLocalService service, ICapabilities appiumOptions)
   at OpenQA.Selenium.Appium.Windows.WindowsDriver`1..ctor(AppiumLocalService service, AppiumOptions AppiumOptions)

I was trying to run the Winapp driver server with AppiumServiceBuilder and I got the above exception 

I have used the below code, where the exception occurred:-

 var LocalService = new AppiumServiceBuilder().WithIPAddress("127.0.0.1").UsingPort(4723).WithLogFile(new System.IO.FileInfo(@"D:\C#\LogFile\Trace.txt")).Build();
 LocalService.Start();
 AppiumOptions capp = new AppiumOptions();
 capp.AddAdditionalCapability("app", "app path");
 WindowsDriver<WindowsElement> T1 = new WindowsDriver<WindowsElement>(LocalService, capp);

**Comment by anunay1** [comment]
are you able to start it manually 
"Message=An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually"

**Comment by AmitTiwari094** [comment]
yes, I am able to start it manually.

**Comment by mariakrol** [comment]
The same situation for me.
