### ISSUE TITLE
OpenQA.Selenium.WebDriverException: 'An unknown server-side error occurred while processing the command. Original error: The system cannot find the file specified'

### ISSUE THREAD

**Issue by AmitTiwari094** [microsoft/WinAppDriver#1855]
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=An unknown server-side error occurred while processing the command. Original error: The system cannot find the file specified
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(AppiumLocalService service, ICapabilities appiumOptions)
   at OpenQA.Selenium.Appium.Windows.WindowsDriver`1..ctor(AppiumLocalService service, AppiumOptions AppiumOptions)
   at Test1.Program.Main(String[] args) in D:\C#\Learn\Test1\Program.cs:line 23

**Comment by anunay1** [comment]
Can you share the code?

**Comment by liljohnak** [comment]
Also what Appium libraries are you using?
