### ISSUE TITLE
Unable to connect to Root Desktop session

### ISSUE THREAD

**Issue by vrumvrumich** [microsoft/WinAppDriver#1896]
I'm trying to connect to Desktop Session using this sample of code:
` val appCapabilities = DesiredCapabilities()
  appCapabilities.setCapability("app", "Root");
  val ses = WindowsDriver(URL("http://127.0.0.1:4723"), appCapabilities)`
  
But, as a result I have such log:
`Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: Bad capabilities. Specify either app or appTopLevelWindow to create a session 
Driver info: io.appium.java_client.windows.WindowsDriver
Command: [null, newSession {capabilities=[{appium:app=Root, appium:automationName=Windows, appium:deviceName=WindowsPC, platformName=WINDOWS}], desiredCapabilities=Capabilities {app: Root, appium:automationName: Windows, deviceName: WindowsPC, platformName: WINDOWS}}]
Capabilities {app: Root, appium:automationName: Windows, deviceName: WindowsPC, platformName: WINDOWS}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:182)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:274)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at io.appium.java_client.windows.WindowsDriver.<init>(WindowsDriver.java:50)
	at MainKt.launchOsDriver(Main.kt:46)
	at MainKt.main(Main.kt:18)
`

**Comment by Shakevg** [comment]
[vrumvrumich](https://github.com/vrumvrumich) Try https://github.com/microsoft/WinAppDriver/issues/1866#issue-1584702726

**Comment by vrumvrumich** [comment]
> [vrumvrumich](https://github.com/vrumvrumich) Try [#1866 (comment)](https://github.com/microsoft/WinAppDriver/issues/1866#issue-1584702726)

Downgrading version of dependencies resolve this issue, however it's pretty difficult to do when you have already use features from new version across your application

**Comment by vrumvrumich** [comment]
@Shakevg I was able to connect to root desktop session, however I faced another issue:
I'm able to get all child elements of driver by using `driver.findElementsByXPath("*/*")`,
But I'm not able to get child elements using `driver.getWindowHandles()`
Moreover I want to switch window, but I not able to do it with rootDriver `driver.switchTo().window(id)`, I need firstly create driver with such capabilities:
`val cap = DesiredCapabilities()
    cap.setCapability("appTopLevelWindow", id)`

**Comment by Shakevg** [comment]
[vrumvrumich](https://github.com/vrumvrumich) You should first create app session using [root session](https://github.com/microsoft/WinAppDriver/blob/master/Docs/FAQ.md#when-and-how-to-attach-to-an-existing-app-window) or [process](https://github.com/microsoft/WinAppDriver/issues/534#issuecomment-562030077).
And then use driver.getWindowHandles() and driver.switchTo().window(id)

**Comment by vrumvrumich** [comment]
@Shakevg I've created session using such snippet of code
``` val appCapabilities = DesiredCapabilities()
        appCapabilities.setCapability("app", "Root");
        val session = WindowsDriver<WebElement>(URL("http://127.0.0.1:4723"), appCapabilities)```
However when I call `session.windowHandles` I get empty list

**Comment by Shakevg** [comment]
Why do you need windowHandles for the Desktop session? I suppose it is not supported for Desktop session.
You should first create an app session and call windowHandles for it.
