### ISSUE TITLE
Calculator getting launched but tests are not Executing - java

### ISSUE THREAD

**Issue by vijay44** [Microsoft/WinAppDriver#200]
Hi,

When I run the test using [calculator sample](https://github.com/Microsoft/WinAppDriver/tree/master/Samples/Java/CalculatorTest) **_calculator application getting launched but no tests are getting executed._**  Could you please help me to solve it...
## **Dev Environment** 

- Windows 10 (Enterprise)

- Java -1.8 

- Selenium Java: 3.4.0

- appium -1.6.6-beta (install using node)

- eclipse 

## **Steps I did**

1.Manually run the winAppDriver.exe using CMD in administrator mode
2.Changed **WindowsDriver** instead of IOSDriver 
3.Run the java class test using JUnit
--> Then, App getting launched, but tests are not executed.

## **WinAppDriver Log**
```
C:\Program Files (x86)\Windows Application Driver>WinAppDriver.exe
Windows Application Driver Beta listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.


==========================================
POST /session HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 330
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_131)

{"capabilities":[{"desiredCapabilities":{"app":"microsoft.windowscalculator_8wekyb3d8bbwe!app","platformName":"Windows","deviceName":"WindowsPC"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"microsoft.windowscalculator_8wekyb3d8bbwe!app","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}
SessionManager - Creating session for microsoft.windowscalculator_8wekyb3d8bbwe!app
SessionManager - WinAppDriver succeeded loading MitaBroker
SessionManager - Application launched
SessionManager - Session successfully created: 8955D6B6-3E43-46B0-8F61-93AA9B38E05F
HTTP/1.1 200 OK
Content-Length: 127
Content-Type: application/json

{"sessionId":"8955D6B6-3E43-46B0-8F61-93AA9B38E05F","status":0,"value":{"app":"microsoft.windowscalculator_8wekyb3d8bbwe!app"}}


==========================================
GET /session/8955D6B6-3E43-46B0-8F61-93AA9B38E05F HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_131)


HTTP/1.1 404 Not Found

```
## **Console Log**
```
org.openqa.selenium.UnsupportedCommandException: Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'LKCONVSELVARA01', ip: '10.83.68.58', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: io.appium.java_client.windows.WindowsDriver
Capabilities [{app=microsoft.windowscalculator_8wekyb3d8bbwe!app, javascriptEnabled=true, platform=ANY}]
Session ID: 3097CDD5-C282-4523-8917-3EC0F4FC67E2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:36)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:42)
	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:46)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:100)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.windows.WindowsDriver.<init>(WindowsDriver.java:43)
	at CalculatorTest.setup(CalculatorTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

## **My Code**
```
import org.junit.*;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;

import java.util.concurrent.TimeUnit;
import java.net.URL;
import io.appium.java_client.windows.WindowsDriver;

public class CalculatorTest {

    private static WindowsDriver CalculatorSession = null;
    private static WebElement CalculatorResult = null;

    @BeforeClass
    public static void setup() {
        try {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("app", "microsoft.windowscalculator_8wekyb3d8bbwe!app");
            capabilities.setCapability("platformName", "Windows");
            capabilities.setCapability("deviceName", "WindowsPC");
            CalculatorSession = new WindowsDriver (new URL("http://127.0.0.1:4723"), capabilities);
            CalculatorSession.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

            CalculatorSession.findElementByName("Clear").click();
            CalculatorSession.findElementByName("Seven").click();
            CalculatorResult = CalculatorSession.findElementByName("Display is 7");
            Assert.assertNotNull(CalculatorResult);

        }catch(Exception e){
            e.printStackTrace();
        } finally {
        }
    }

    @Before
    public void Clear()
    {
        CalculatorSession.findElementByName("Clear").click();
        Assert.assertEquals("Display is 0", CalculatorResult.getText());
    }

    @AfterClass
    public static void TearDown()
    {
        CalculatorResult = null;
        if (CalculatorSession != null) {
            CalculatorSession.quit();
        }
        CalculatorSession = null;
    }

    @Test
    public void Addition()
    {
        CalculatorSession.findElementByName("One").click();
        CalculatorSession.findElementByName("Plus").click();
        CalculatorSession.findElementByName("Seven").click();
        CalculatorSession.findElementByName("Equals").click();
        Assert.assertEquals("Display is 8", CalculatorResult.getText());
    }

    @Test
    public void Combination()
    {
        CalculatorSession.findElementByName("Seven").click();
        CalculatorSession.findElementByName("Multiply by").click();
        CalculatorSession.findElementByName("Nine").click();
        CalculatorSession.findElementByName("Plus").click();
        CalculatorSession.findElementByName("One").click();
        CalculatorSession.findElementByName("Equals").click();
        CalculatorSession.findElementByName("Divide by").click();
        CalculatorSession.findElementByName("Eight").click();
        CalculatorSession.findElementByName("Equals").click();
        Assert.assertEquals("Display is 8", CalculatorResult.getText());
    }

    @Test
    public void Division()
    {
        CalculatorSession.findElementByName("Eight").click();
        CalculatorSession.findElementByName("Eight").click();
        CalculatorSession.findElementByName("Divide by").click();
        CalculatorSession.findElementByName("One").click();
        CalculatorSession.findElementByName("One").click();
        CalculatorSession.findElementByName("Equals").click();
        Assert.assertEquals("Display is 8", CalculatorResult.getText());
    }

    @Test
    public void Multiplication()
    {
        CalculatorSession.findElementByName("Nine").click();
        CalculatorSession.findElementByName("Multiply by").click();
        CalculatorSession.findElementByName("Nine").click();
        CalculatorSession.findElementByName("Equals").click();
        Assert.assertEquals("Display is 81", CalculatorResult.getText());
    }

    @Test
    public void Subtraction()
    {
        CalculatorSession.findElementByName("Nine").click();
        CalculatorSession.findElementByName("Minus").click();
        CalculatorSession.findElementByName("One").click();
        CalculatorSession.findElementByName("Equals").click();
        Assert.assertEquals("Display is 8", CalculatorResult.getText());
    }
}
```

@yodurr

**Comment by yodurr** [comment]
Hi @vijay44 the Java sample is now updated.  Could you try the updated sample?  Thanks.

**Comment by vijay44** [comment]
Thanks @yodurr . It's  working fine.

**Comment by phipgn** [comment]
@vijay44 i tried running this sample yesterday but got the exact same issue. What did you do to make it work?

**Comment by phipgn** [comment]
![2017-09-07_8-50-35](https://user-images.githubusercontent.com/22786385/30172421-a8b737ec-93a9-11e7-9123-1fd7fbcbffc3.jpg)

**Comment by phipgn** [comment]
![2017-09-07_8-51-14](https://user-images.githubusercontent.com/22786385/30172462-bda5b386-93a9-11e7-806d-dee78a15de4f.jpg)

**Comment by phipgn** [comment]
@yodurr the CalculatorSession always null, seems like it cannot be created.

**Comment by ShailendraPrSingh** [comment]
facing issue same as @phipgn . Please help

**Comment by phipgn** [comment]
@ShailendraPrSingh it failed on a laptop (windows 10 64 bit), then i tried running this sample on a desktop (windows 10 64 bit also) and it worked. i dont know why.

**Comment by vijay44** [comment]
Hi @phipgn & @ShailendraPrSingh  sorry for the  delay in response. Please refer [this](https://stackoverflow.com/questions/44410681/the-url-session-did-not-map-to-a-valid-resource-how-to-run-desktop-applicat/44492165#44492165). Hope it will solve your problem.

**Comment by vikramca06** [comment]
No. Still having the same issue.

Please help me to fix the below issue. I am using windows 10 in laptop.

1. Session getting created
2. App is launched
3. Then eclipse throws following error
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=Microsoft.WindowsCalculator_8wekyb3d8bbwe!App, platformName=Windows, deviceName=WindowsPC}], required capabilities = Capabilities [{}]
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-FA32PAC', ip: '192.168.177.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: WindowsDriver
	at io.appium.java_client.remote.AppiumProtocolHandShake.lambda$1(AppiumProtocolHandShake.java:95)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:95)
	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:111)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.windows.WindowsDriver.<init>(WindowsDriver.java:43)
	at CalculatorTest.setup(CalculatorTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by umadevisk89** [comment]
I am facing same issue. Need help in fixing it.

**Comment by janmejay2792** [comment]
I am facing same issue. Need help in fixing it.
Session App getting launched, but tests are not executed.
