### ISSUE TITLE
SendKeys() throwing an error message System.InvalidOperationException

### ISSUE THREAD

**Issue by dhapolapankaj** [Microsoft/WinAppDriver#201]
Hello Team,

I am trying to run code in VM and while execution I minimized the VM.
I got the Exception System.InvalidOperationException for SendKeys() method, but its working fine for Clear() function

![system invalidoperationexception_while_vm_minimize](https://user-images.githubusercontent.com/29034223/26976591-12d67998-4d42-11e7-93be-564b81f398d0.png)

Below is the exception details.

System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=An unknown error occurred in the remote end while processing the command.
  Source=WebDriver
  StackTrace:
       at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
       at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
       at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
       at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
       at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
       at AuthenticationPopupHandler.Program.HandlePopUp(String browser, String executionmode, String uid, String pwd) in c:\Users\myuser\Documents\Visual Studio 2012\Projects\AuthenticationPopupHandler\AuthenticationPopupHandler\Program.cs:line 117
       at AuthenticationPopupHandler.Program.Main(String[] args) in c:\Users\myuser\Documents\Visual Studio 2012\Projects\AuthenticationPopupHandler\AuthenticationPopupHandler\Program.cs:line 352
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by yodurr** [comment]
when the interactive session is closed the input injection will fail, which is what is happening here.  Enabling this would be an enhancement.

**Comment by fman028** [comment]
Ran into the same issue for the `Click()` method while running tests on a VM.

When I remote into the VM and watch the tests run everything works fine.  When my remote session is minimized I get the above error.

Does this mean that currently there is no way to automatically run UI tests on a VM?

**Comment by tsekhmeistruk** [comment]
[Running Tests in Minimized Remote Desktop Windows](https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/in-minimized-window.html)

[Disconnecting From Remote Desktop While Running Automated Tests](https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html)

**Comment by dhapolapankaj** [comment]
Hey @yodurr 

Using above solution from @tsekhmeistruk we are able to resolve this.
Are we planning to add this in WinAppDriver?

Regards
PD
