### ISSUE TITLE
Tap overload with coordinates fails with 400 Bad Request

### ISSUE THREAD

**Issue by hartez** [Microsoft/WinAppDriver#229]
I'm attempting to execute a Tap with the `Tap(int fingers, int x, int y, int duration)` overload. The method fails with a 400 Bad Request:

```
{"actions":[{"action":"press","options":{"x":341,"y":152}},{"action":"wait","options":{"ms":10}},{"action":"release"}]}
HTTP/1.1 400 Bad Request
Content-Length: 98
Content-Type: application/json

{"status":100,"value":{"error":"invalid argument","message":"Missing Command Parameter: element"}}
```

This seems similar to issue #226.

**Comment by yodurr** [comment]
we're working on actions for a future release

**Comment by yodurr** [comment]
FYI actions support is included in WAD 1.1

**Comment by cosminstirbu** [comment]
Hello,

The issue still reproduces in WAD 1.1

These are the logs:

```
[Appium] Welcome to Appium v1.9.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"platformName":"Windows","newCommandTimeout":120,"app":"com.test.App_x4f170a5xjzjc!App","deviceName":"WindowsPC"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Windows","newCommandTimeout":120,"app":"com.test.App_x4f170a5xjzjc!App","deviceName":"WindowsPC"},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1540134905312 (18:15:05 GMT+0300 (GTB Daylight Time))
[Appium] Creating new WindowsDriver (v1.4.0) session
[Appium] Capabilities:
[Appium]   platformName: Windows
[Appium]   newCommandTimeout: 120
[Appium]   app: com.test.App_x4f170a5xjzjc!App
[Appium]   deviceName: WindowsPC
[BaseDriver] Creating session with MJSONWP desired capabilities: {"platformName":"Windows","...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
[BaseDriver] Session created with session id: 3080ef9a-ac18-433a-9f90-9cd712525f55
[WinAppDriver] You must use WinAppDriver version 1.1
[WinAppDriver] Verifying WinAppDriver version 1.1 is installed via comparing the checksum.
[WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: 4724/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[WinAppDriver] [STDOUT] Press ENTER to exit.
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] GET /wd/hub/status HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 147
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"build":{"revision":"18001","time":"Tue Sep 18 18:35:38 2018","version":"1.1.1809"},"os":{"arch":"amd64","name":"windows","version":"10.0.17763"}}
[JSONWP Proxy] Got response with status 200: "{\"build\":{\"revision\":\"18001\",\"time\":\"Tue Sep 18 18:35:38 2018\",\"version\":\"1.1.1809\"},\"os\":{\"arch\":\"amd64\",\"name\":\"windows\",\"version\":\"10.0.17763\"}}"
[WinAppDriver] Status call returned 200. we're online and ready to run tests
[WinAppDriver] WinAppDriver changed state to 'online'
[JSONWP Proxy] Matched '/session' to command name 'createSession'
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"Windows","newCommandTimeout":120,"app":"com.test.App_x4f170a5xjzjc!App","deviceName":"WindowsPC"}}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 146
[WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"desiredCapabilities":{"platformName":"Windows","newCommandTimeout":120,"app":"com.test.App_x4f170a5xjzjc!App","deviceName":"WindowsPC"}}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 145
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"9E930738-9A0A-4D5A-A674-FE8690D1C33D","status":0,"value":{"app":"com.test.App_x4f170a5xjzjc!App","platformName":"Windows"}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"9E930738-9A0A-4D5A-A674-FE8690D1C33D","status":0,"value":{"app":"com.test.App_x4f170a5xjzjc!App","platformName":"Windows"}}
[Appium] New WindowsDriver session created successfully, session 3080ef9a-ac18-433a-9f90-9cd712525f55 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1540134907961 (18:15:07 GMT+0300 (GTB Daylight Time))
[MJSONWP] Cached the protocol value 'MJSONWP' for the new session 3080ef9a-ac18-433a-9f90-9cd712525f55
[MJSONWP] Responding to client with driver.createSession() result: {"platformName":"Windows","newCommandTimeout":120,"app":"com.test.App_x4f170a5xjzjc!App","deviceName":"WindowsPC"}
[HTTP] <-- POST /wd/hub/session 200 2660 ms - 194
[HTTP] 
[HTTP] --> POST /wd/hub/session/3080ef9a-ac18-433a-9f90-9cd712525f55/touch/perform
[HTTP] {"actions":[{"action":"tap","options":{"x":379,"y":408}}]}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/3080ef9a-ac18-433a-9f90-9cd712525f55/touch/perform' to command name 'performTouch'
[JSONWP Proxy] Proxying [POST /wd/hub/session/3080ef9a-ac18-433a-9f90-9cd712525f55/touch/perform] to [POST http://127.0.0.1:4724/wd/hub/session/9E930738-9A0A-4D5A-A674-FE8690D1C33D/touch/perform] with body: {"actions":[{"action":"tap","options":{"x":379,"y":408}}]}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/9E930738-9A0A-4D5A-A674-FE8690D1C33D/touch/perform HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 58
[WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"actions":[{"action":"tap","options":{"x":379,"y":408}}]}
[WinAppDriver] [STDOUT] HTTP/1.1 400 Bad Request
[WinAppDriver] [STDOUT] Content-Length: 98
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"status":100,"value":{"error":"invalid argument","message":"Missing Command Parameter: element"}}
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 400 - {"status":100,"value":{"error":"invalid argument","message":"Missing Command Parameter: element"}}
[MJSONWP]     at JWProxy.proxy$ (C:\Users\stirb\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:182:13)
[MJSONWP]     at tryCatch (C:\Users\stirb\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\stirb\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\stirb\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\stirb\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at 
[W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
[HTTP] <-- POST /wd/hub/session/3080ef9a-ac18-433a-9f90-9cd712525f55/touch/perform 500 29 ms - 121
[HTTP] 
[HTTP] --> GET /wd/hub/session/3080ef9a-ac18-433a-9f90-9cd712525f55/screenshot
[HTTP] {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/3080ef9a-ac18-433a-9f90-9cd712525f55/screenshot' to command name 'getScreenshot'
[JSONWP Proxy] Proxying [GET /wd/hub/session/3080ef9a-ac18-433a-9f90-9cd712525f55/screenshot] to [GET http://127.0.0.1:4724/wd/hub/session/9E930738-9A0A-4D5A-A674-FE8690D1C33D/screenshot] with body: {}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] GET /wd/hub/session/9E930738-9A0A-4D5A-A674-FE8690D1C33D/screenshot HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"9E930738-9A0A-4D5A-A674-FE8690D1C33D\",\"status\":0,\"value\":\"iVBORw0KGgoAAAANSUhEUgAACWQAAAdLCAIAAAC3kLXrAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAP+6SURBVHhe7N0JnBxlnT/gdPfcuTO575CDhHCGU24EBRTvVfBYr/VYPFZQPNYLcNfdVVT+6rre4oG7oIsKigqLIorImZAQCIQrdybJTDKZJHPP9L+66804JplkjmTSM/U801Pz/qqqq7uraviQfPO+b+rt77h8yJAha9esamlpjhoAAAAAAADA4FZcXDJt+syoEcLCO+/4VVtra34TAAAAAAAAMJi1tra+7BV/FzVCWPine+56+umn85sAAAAAAACAQS5OCdNxAQAAAAAAACSNsBAAAAAAAAASp6GxIXoICwEAAAAAACChhIUAAAAAAACQOOMrR0YPYSEAAAAAAAAklLAQAAAAAAAAEkpYCAAAAAAAAAklLAQAAAAAAICEEhYCAAAAAABAQgkLAQAAAAAAIKGEhQAAAAAAAJBQwkIAAAAAAABIKGEhAAAAAAAAJJSwEAAAAAAAABJKWAgAAAAAAAAJJSwEAAAAAACAhBIWAgAAAAAAQEIJCwEAAAAAACChhIUAAAAAAACQUMJCAAAAAAAASChhIQAAAAAAAL2U7YNwiEFn1KhRN9xwQ7QMdTf04ikHi7AQAAAAAAAADprrr7/+rW996913393N8C/aLdo5ekr0xLCqHyUrLJw/f/72vKgRVsF+uWcAAAAAAOCAUj0UnjZIXXnllY8++ujxxx/fnbwwTgqjnaOnRE8Ma/vRwQ8LKysrn3nmmdB9dLeqqqqbbrop2hR22q/58+evXr26vr7+0ksvDau60P09+yJ621dfffXKlSvDh8lmo1e8//77L7744rDHwfPQQw9Fx4+Woe53/XNKe2Sfd1Rk1apVt95666G4CodUnD6Gz7B...
[JSONWP Proxy] Replacing sessionId 9E930738-9A0A-4D5A-A674-FE8690D1C33D with 3080ef9a-ac18-433a-9f90-9cd712525f55
[HTTP] <-- GET /wd/hub/session/3080ef9a-ac18-433a-9f90-9cd712525f55/screenshot 200 511 ms - 1629130
[HTTP] 
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 1629130
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] rNXKZO00G3+SJAFxZBiGIeQca4GuQlBQvHooyEKBm1u52HrvkCwEwBtLumBBFMWcKMoIissnD3gWzN5c14U9zNsgDdCzQzJ4GPfV6srcpXZtXuDFJIkCdGR4zL7WngNpmri+vT/cHM4O/MDleUGWVEghpLkI8YyIcWE94FU9H8MESZr1DqKw+NgNykfW9EqrnSuhZEny1fVb++NpfvVRgIkBKhTixmZQqkzGcxzUsSLJ775xoVGrWI63359IkpwThMdBeT4Z8IxvFFkIcD2/WauWS8Q5M8FgOLm+sWvabpok8BR0LUYqQBSFaqVUq5TgTWQysvofJ8sLHVVFO+PwUoxGk5nl5JE8B47IwvHESFK0hgoPlkUx93uH+c2y56YMX1OyEBrk0nxb19AlNbR+CapAVzq1SqeOFu6hUPKXAnpD+PsY5UII [...]
```

Can you please look into this?

Thanks,
Cosmin

**Comment by cosminstirbu** [comment]
Hello.

Any news on this?

We have quite a few tests that need to tap on an image at different points.
Is there any workaround for this, if there isn't any plan to fix this soon?

Thank you,
Cosmin

**Comment by hassanuz** [comment]
Hi @cosminstirbu,

Thanks for reporting this bug. In the meantime, would it be possible for you to adapt towards the Actions framework? 

We have a couple of examples on our repo, one being [here](https://github.com/Microsoft/WinAppDriver/blob/35a659232060a6e436cbb8393ae9a09bab12bc89/Tests/WebDriverAPI/ActionsTouch.cs#L49). 

For touch interaction, Actions is the way to move forward.

**Comment by cosminstirbu** [comment]
In the meanwhile, I've opened a PR on the main `appium-dotnet-driver` repo https://github.com/appium/appium-dotnet-driver/pull/315.

I'm not too familiar with the overall design of the Actions feature, so if there will be questions, maybe you guys can jump in and clarify any remarks from the Appium maintainers.
