### ISSUE TITLE
CalculatorTest should preset the mode to avoid test failing.

### ISSUE THREAD

**Issue by xied75** [Microsoft/WinAppDriver#3]
First of all, Great work! :100: 

My Calc is set in "Programmer" mode, when I run the test, it fails like this

```
Test Name:	Combination
Test FullName:	CalculatorTest.BasicScenarios.Combination
Test Source:	C:\git\WinAppDriver\Samples\CalculatorTest\BasicScenarios.cs : line 76
Test Outcome:	Failed
Test Duration:	0:00:01.1552979

Result StackTrace:	at CalculatorTest.BasicScenarios.Combination() in C:\git\WinAppDriver\Samples\CalculatorTest\BasicScenarios.cs:line 85
Result Message:	Assert.AreEqual failed. Expected:<Display is  8 >. Actual:<Display is  63 >.

```

If it's on default mode, then all pass ok.

**Comment by yodurr** [comment]
Hi, we're glad you like the service!  I'll update this test.

**Comment by timotiusmargo** [comment]
Fix #7 is great and should address the issue with **Scientific **and **Programmer **calculator mode. However, it will not fix the issue if the calculator mode is set to **Date Calculation** or other **Coverters**. So it still requires more change to set the mode to **Standard**

**Comment by xied75** [comment]
Just curious, why don't we click the menu button and choose the mode we want?

**Comment by xied75** [comment]
Sorry to report that AlarmClockTest also got an error on my laptop:

```
Test Name:	FullScenario
Test FullName:	AlarmClockTest.Scenario.FullScenario
Test Source:	C:\git\WinAppDriver\Samples\AlarmClockTest\Scenario.cs : line 73
Test Outcome:	Failed
Test Duration:	0:00:00.321031

Result StackTrace:	
at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
   at AlarmClockTest.Scenario.AddAlarm(String timeText) in C:\git\WinAppDriver\Samples\AlarmClockTest\Scenario.cs:line 126
   at AlarmClockTest.Scenario.FullScenario() in C:\git\WinAppDriver\Samples\AlarmClockTest\Scenario.cs:line 81
Result Message:	
Test method AlarmClockTest.Scenario.FullScenario threw exception: 
System.FormatException: String was not recognized as a valid DateTime.
```

At the time the string look like this: "Local time, 20 April 2016, 13:01, "

**Comment by timotiusmargo** [comment]
Hi @xied75! Could you please try Pull Request #14 to see if this fix the AlarmClockTest issue in your laptop?

**Comment by xied75** [comment]
Hi @timotiusmargo tried it. It past time parsing ok. Now stuck here:

```csharp
AlarmClockSession.FindElementByAccessibilityId("PeriodSelector").FindElementByName(period).Click();
```

The error msg from test runner:

```
Test Name:	FullScenario
Test FullName:	AlarmClockTest.Scenario.FullScenario
Test Source:	C:\git\WinAppDriver\Samples\AlarmClockTest\Scenario.cs : line 73
Test Outcome:	Failed
Test Duration:	0:00:05.6928374

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElementByAccessibilityId(String selector)
   at AlarmClockTest.Scenario.AddAlarm(String timeText) in C:\git\WinAppDriver\Samples\AlarmClockTest\Scenario.cs:line 140
   at AlarmClockTest.Scenario.FullScenario() in C:\git\WinAppDriver\Samples\AlarmClockTest\Scenario.cs:line 81
Result Message:	
Test method AlarmClockTest.Scenario.FullScenario threw exception: 
OpenQA.Selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.

```

My screen shot:

![image](https://cloud.githubusercontent.com/assets/1682456/14781864/3b65e946-0add-11e6-9792-8b8e817da9c9.png)

**Comment by alakshmi1030** [comment]
Please check out the latest samples in C# for CalculatorTest and AlarmClockTest as this issue should be fixed with those updates.
