### ISSUE TITLE
Unable to create a session

### ISSUE THREAD

**Issue by lixiaoyudakeke** [Microsoft/WinAppDriver#305]
After the command line started appium, domo, which runs the downloaded calculator, reported the following error`[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /session {"capabilities":{"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /session 404 9 ms - 50
[HTTP] --> POST /session {"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /session 404 3 ms - 50
[HTTP] --> POST /session {"capabilities":{"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /session 404 2 ms - 50`

**Comment by yodurr** [comment]
Hi @lixiaoyudakeke what version of Windows are you running this on?  It looks like Appium is unable to run WinAppDriver - can you confirm WinAppDriver is installed?  It should be here: 
C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe

**Comment by lixiaoyudakeke** [comment]
@yodurr Thanks for your answer,The version I run is win10, The WinAppDriver i was installed,but I installed the D:\Program\winDriver, And set the environment variable,After modification, the following error occurred today,Looking forward to your reply
`2017-11-22 05:59:44:872 - info: [Appium] Creating new WindowsDriver (v0.5.0) session
2017-11-22 05:59:44:872 - info: [Appium] Capabilities:
2017-11-22 05:59:44:876 - info: [Appium]   app: 'Microsoft.WindowsCalculator_8wekyb3d8bbwe!App'
2017-11-22 05:59:44:877 - info: [Appium]   platformName: 'Windows'
2017-11-22 05:59:44:877 - info: [Appium]   deviceName: 'WindowsPC'
2017-11-22 05:59:44:887 - warn: [BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
2017-11-22 05:59:44:889 - info: [BaseDriver] Session created with session id: 40882272-09e1-4205-8c28-34593aa6d1ab
2017-11-22 05:59:44:892 - info: [WinAppDriver] Verifying WinAppDriver is installed with correct checksum
2017-11-22 05:59:44:937 - info: [debug] [WinAppDriver] Deleting WinAppDriver session
2017-11-22 05:59:44:949 - error: [MJSONWP] Encountered internal error running command: Error: Could not verify WinAppDriver install; re-run install
    at WinAppDriver.start$ (../../lib/winappdriver.js:35:13)
    at tryCatch (C:\Users\tianyu\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\tianyu\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\tianyu\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\tianyu\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)`

**Comment by lixiaoyudakeke** [comment]
@yodurr I'm trying to put WinAppDriver  under C:\Program Files (x86)\Windows Application Driver\，The question remains

**Comment by lixiaoyudakeke** [comment]
When I change my WinAppDrive to V0.9,All the problems have been solved,I hope I can help others
