### ISSUE TITLE
using Page Factory Design gives error: java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field com.test.pages.HomePage.txtTitle to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4

### ISSUE THREAD

**Issue by aeroclee** [Microsoft/WinAppDriver#316]
Hello,
I am trying to use Page Factory (Page Object) Design Pattern for Window App.
For iOSDriver, i was able to use Page Object Pattern without any error.
However, I encountered problem using WinAppDriver.  Wonder if WinAppDriver support Page Factory (Page Object) design pattern implementation.

Looks like this might be related to https://github.com/Microsoft/WinAppDriver/issues/257.
just in case.  i am posting this.....

Page Code:
Case:
	@WindowsBy(accessibility="title")
	private MobileElement txtTitle;

	public String getTxtTitle() {
		return txtTitle.getText();
	}

Comment: earlier, I use WebElement as variable type like below:
Case:
	@WindowsBy(accessibility="title")
	private MobileElement txtTitle;

	public String getTxtTitle() {
		return txtTitle.getText();
	}

I encounter following error:
org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: Locator map: 
- native content: "By.id: txtTitle" 
- html content: "by id or name "txtTitle""
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:102)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:61)
	at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.getText(<generated>)
	at com.test.pages.HomePage.getTxtTitleBar(HomePage.java:30)
	at com.test.TestV1.initialTest(DVATTestV1.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction@107ed6fc (tried for 1 second(s) with 500 MILLISECONDS interval)
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:263)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:76)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:95)
	... 29 more
Caused by: org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'WLITL91', ip: '172.16.42.80', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: io.appium.java_client.windows.WindowsDriver
Capabilities [{app=Test_007tshxnsa8!App, javascriptEnabled=true, platformName=WINDOWS, platform=WINDOWS}]
Session ID: 60E513E3-415E-43DE-9D13-55ED41C4A2D6
*** Element info: {Using=id, value=txtTitleBar}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:356)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElement(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:402)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:70)
	at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElementById(WindowsDriver.java:1)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:348)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:58)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElement(WindowsDriver.java:1)
	at io.appium.java_client.pagefactory.bys.ContentMappedBy.findElement(ContentMappedBy.java:36)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:348)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:58)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElement(WindowsDriver.java:1)
	at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:96)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:150)
	at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	... 31 more

Test Code:
@Test(priority=1)
	public void initialTest (){
		getPrintHelper().print("Initial HomePage Test!");
		getPrintHelper().print("Title Bar: "+homepage.getTxtTitle());		
	}

Failure Exception:
java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field com.test.pages.HomePage.txtTitle to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
	at java.lang.reflect.Field.set(Unknown Source)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at com.test.pages.AbstractBasePage.loadPage(AbstractBasePage.java:25)
	at com.test.pages.HomePage.<init>(HomePage.java:22)
	at com.test.TestV1.beforeClass(TestV1.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

Eclipse Console:
[RemoteTestNG] detected TestNG version 6.11.0
Thread# 1: Abstact:  Test
[main] INFO org.springframework.context.support.ClassPathXmlApplicationContext - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@6c372fe6: startup date [Fri Dec 01 14:44:14 PST 2017]; root of context hierarchy
[main] INFO org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [SpringConfig.xml]
[main] INFO org.springframework.jdbc.datasource.DriverManagerDataSource - Loaded JDBC driver: org.postgresql.Driver
Thread# 1: Before Suite: 
Thread# 1: Set Up Appium Properties
Thread# 1: WinAppDriver Configuration
Thread# 1: Load Environment Config File
Thread# 1: Config File: properties/environment/DVAT-Win.properties
Thread# 1: Platform App: Test_007tshxnsa8!App
Thread# 1: Setting up WinApp Driver
Thread# 1: Initialize Capabilities and Windows Driver
Thread# 1: Found URL
Dec 01, 2017 2:44:19 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Thread# 1: Instantiate HomePage!
Thread# 1: Abstract BasePage: Initialize PageFactory.
Thread# 1: Load Page!
Thread# 1: After Class!
FAILED CONFIGURATION: @BeforeClass beforeClass
java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field com.test.pages.HomePage.txtTitle to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
	at java.lang.reflect.Field.set(Unknown Source)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at com.test.pages.AbstractBasePage.loadPage(AbstractBasePage.java:25)
	at com.test.pages.HomePage.<init>(HomePage.java:22)
	at com.test.TestV1.beforeClass(DVATTestV1.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

SKIPPED: initialTest
java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field com.test.pages.HomePage.txtTitleBar to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
	at java.lang.reflect.Field.set(Unknown Source)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at com.test.pages.AbstractBasePage.loadPage(AbstractBasePage.java:25)
	at com.test.pages.HomePage.<init>(HomePage.java:22)
	at com.test.TestV1.beforeClass(DVATTestV1.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 1
===============================================

Log: 
==========================================
POST /session/1AB37170-A85D-470C-BDD0-3426DD20A603/element HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 36
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_144)

{"using":"id","value":"txtTitle"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

==========================================
GET /session/1AB37170-A85D-470C-BDD0-3426DD20A603/screenshot HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_144)

HTTP/1.1 200 OK
Content-Length: 14510
Content-Type: application/json

==========================================
DELETE /session/1AB37170-A85D-470C-BDD0-3426DD20A603 HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_144)

HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"1AB37170-A85D-470C-BDD0-3426DD20A603","status":0}

==========================================
POST /session HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 404
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_144)

{
  "desiredCapabilities": {
    "app": "Test_007tshxnsa8!App",
    "platformName": "Windows"
  },
  "requiredCapabilities": {},
  "capabilities": {
    "desiredCapabilities": {
      "app": "Test_007tshxnsa8!App",
      "platformName": "Windows"
    },
    "requiredCapabilities": {},
    "alwaysMatch": {
      "platformName": "Windows"
    },
    "firstMatch": []
  }
}
HTTP/1.1 200 OK
Content-Length: 143
Content-Type: application/json

{"sessionId":"0185BF3C-F61D-4ADF-A7B3-3B6FC521D49B","status":0,"value":{"app":"Test_007tshxnsa8!App","platformName":"Windows"}}

==========================================
GET /session/0185BF3C-F61D-4ADF-A7B3-3B6FC521D49B HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_144)

HTTP/1.1 200 OK
Content-Length: 143
Content-Type: application/json

{"sessionId":"0185BF3C-F61D-4ADF-A7B3-3B6FC521D49B","status":0,"value":{"app":"Test_007tshxnsa8!App","platformName":"Windows"}}

==========================================
GET /session/0185BF3C-F61D-4ADF-A7B3-3B6FC521D49B HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_144)

HTTP/1.1 200 OK
Content-Length: 143
Content-Type: application/json

{"sessionId":"0185BF3C-F61D-4ADF-A7B3-3B6FC521D49B","status":0,"value":{"app":"Test_007tshxnsa8!App","platformName":"Windows"}}

==========================================
GET /session/0185BF3C-F61D-4ADF-A7B3-3B6FC521D49B HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_144)

HTTP/1.1 200 OK
Content-Length: 143
Content-Type: application/json

{"sessionId":"0185BF3C-F61D-4ADF-A7B3-3B6FC521D49B","status":0,"value":{"app":"Test_007tshxnsa8!App","platformName":"Windows"}}

==========================================
GET /session/0185BF3C-F61D-4ADF-A7B3-3B6FC521D49B HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_144)

HTTP/1.1 200 OK
Content-Length: 143
Content-Type: application/json

{"sessionId":"0185BF3C-F61D-4ADF-A7B3-3B6FC521D49B","status":0,"value":{"app":"Test_007tshxnsa8!App","platformName":"Windows"}}

**Comment by hassanuz** [comment]
Hi @aeroclee ,
In this payload
```
{"using":"id","value":"txtTitle"}
```
The problem appears to be in the payload. When using `id` locator, we expect element-id to be passed as a value. When you are passing `txtTitle` you may have intended to use the accessibilityID locator. 

Let us know if this was the issue. 

Thanks

**Comment by hassanuz** [comment]
Marking issue as closed due to no additional comments.
