### ISSUE TITLE
Could not verify WinAppDriver install  (Appium): 

### ISSUE THREAD

**Issue by raghubhoje** [Microsoft/WinAppDriver#320]
I am trying to run a Calculator app – on windows 10. I have started appium from command prompt (V1.7.1); I am getting below message in eclipse when I run

“Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not verify WinAppDriver install; re-run install”

My code is below

 DesiredCapabilities capabilities = new DesiredCapabilities();
           capabilities.setCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");         
           capabilities.setCapability("platformName", "Windows");
           capabilities.setCapability("deviceName", "WindowsPC");           
           CalculatorSession = new WindowsDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);   	   
                   
            CalculatorSession.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

           // CalculatorSession.findElementByName("Clear").click();
            CalculatorSession.findElementByName("Seven").click(); 
            CalculatorSession.findElementByName("one").click();

**Comment by 1Arhangel** [comment]
I had a similar problem which I solved like this:

Uninstalled the WinAppDriver that comes with the Appium installation via Node.js using:
`npm uninstall appium-windows-driver`

Installed a specific version of WinAppDriver (in this case 0.9 version) using:
`npm install appium-windows-driver@0.5.0 -g`

Note:
This requires Appium to be installed via NodeJS. 

Hope it helps.

**Comment by raghubhoje** [comment]
Thanks for the reply - the above issue is resolved now 
but now i am getting below error in eclipse 
"Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: **Could not proxy command to remote server. Original error: 500 - undefined**"

**Comment by timotiusmargo** [comment]
Hi @raghubhoje,

Can you check the log if `WinAppDriver.exe` has indeed be started by Appium? Otherwise, it sounds like it's an Appium setup issue that you can also get help from Appium Github.

**Comment by raghubhoje** [comment]
thanks for the reply - i have below logs from the Appium - can you please take a look once and guide us -

Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","deviceName":"WindowsPC","platformName":"Windows"},"capabilities":{"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","deviceName":"WindowsPC","platformName":"Windows"},"firstMatch":[{"platformName":"windows"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","deviceName":"WindowsPC","platformName":"Windows"},null,{"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","deviceName":"WindowsPC","platformName":"Windows"},"firstMatch":[{"platformName":"windows"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1512675085174 (13:31:25 GMT-0600 (Central Standard Time))
[Appium] Creating new WindowsDriver (v0.5.0) session
[Appium] Capabilities:
[Appium]   app: 'Microsoft.WindowsCalculator_8wekyb3d8bbwe!App'
[Appium]   deviceName: 'WindowsPC'
[Appium]   platformName: 'Windows'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
[BaseDriver] Session created with session id: 7eb10048-31e6-4792-8533-c2f08f8b2170
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[debug] [WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: undefined 4724/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver Beta listening for requests at: http://127.0.0.1:4724/wd/hub
[debug] [WinAppDriver] WinAppDriver changed state to 'online'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","deviceName":"WindowsPC","platformName":"Windows"}}
[WinAppDriver] [STDOUT] Press ENTER to exit.
[JSONWP Proxy] Got unexpected response: <HEAD><TITLE>Connection refused</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black"><H1>Connection refused</H1><HR>
<FONT FACE="Helvetica,Arial"><B>
Description: Connection refused</B></FONT>
<HR>
<!-- default "Connection refused" response (502) -->
</BODY>
                                      ...
[debug] [WinAppDriver] Deleting WinAppDriver session
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 502 - "<HEAD><TITLE>Connection refused</TITLE></HEAD>\n<BODY BGCOLOR=\"white\" FGCOLOR=\"black\"><H1>Connection refused</H1><HR>\n<FONT FACE=\"Helvetica,Arial\"><B>\nDescription: Connection refused</B></FONT>\n<HR>\n<!-- default \"Connection refused\" response (502) -->\n</BODY>\n                                                                                                                                                                                                                                                                                                                                                                                                                      \u0000"
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (C:\Users\a150400\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\a150400\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\a150400\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\a150400\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 457 ms - 915

**Comment by Jazzz42** [comment]
I encountered the described error also with Appium version 1.11.0

**Comment by jnicelap** [comment]
I have the same issue when I updated appium to 1.11.0 and the winappdriver to 1.14.0..
