### ISSUE TITLE
Remote WinAppDriver with Firewall Disabled

### ISSUE THREAD

**Issue by missalinaj** [Microsoft/WinAppDriver#338]
Hi,

I am trying to run WinAppDriver on a remote (windows10) machine that has firewall disabled. I have followed the instructions here (https://github.com/Microsoft/WinAppDriver) for running on a remote machine and even though firewall is disabled, my connection would still get denied. So I've created the TCP rule mentioned in the tutorial but I still get the following message when I try to run it from another machine: 
"ERROR

======================================================================
ERROR: setUpClass (__main__.ZuneTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Python36\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_zune.py", line 30, in setUpClass
    desired_capabilities= desired_caps)
  File "C:\Python36\lib\site-packages\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 528, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "C:\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

----------------------------------------------------------------------
Ran 0 tests in 1.160s

FAILED (errors=1)"

After enabling the Firewall, I am still not able to run my test, but i'm getting the below error message instead: 
  File "C:\Python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

My Questions are:
1. Are there any additional logs that WinAppDriver.exe spits out where I could potentially get more information on the failures?
2. Are there any registry settings that would prevent this connection that I need to change?

Both Machines, test and host are connected to the same LAN network, but this is a secure network as it is company network, so i'm not sure what could be the settings that might be blocking this call. Any help is appreciated.

Thanks!

**Comment by shankarkc** [comment]
can you run telnet <host> <port> and see if it connects?
I opened firewall using
```
netsh advfirewall firewall add rule name="Windows application driver" dir=in action=allow protocol=TCP localport=4723
```
But I still not able to make it work on remote machine (like 10.x.x.x:4723) yet. it works with 127.0.0.1:4723 ONLY 😢 Opened a defect for same . Awaiting response

**Comment by missalinaj** [comment]
Telnet was showing port is open. I realized I was running it incorrectly:
On the remote machine: WinAppDriver.exe 10.x.x.x:4723/wd/hub
On the host machine, i had to write:
self.driver = webdriver.Remote(
            command_executor='http://10.x.x.x:4723/wd/hub',
            desired_capabilities= desired_caps)

This fixed the problem for me, I hope it does the same for you. The instructions they gave weren't necessarily clear to me in specifying that you have to send json to /wd/hub.

**Comment by rapidroamer** [comment]
I didn't need to have wd/hub;
Below worked just fine, the ip and port (be mindful winapp driver needs to be started elevated)
Example:  "c:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe" 192.168.1.103 4723

**Comment by umadevisk89** [comment]
> I didn't need to have wd/hub;
> Below worked just fine, the ip and port (be mindful winapp driver needs to be started elevated)
> Example: "c:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe" 192.168.1.103 4723

this solution works
