### ISSUE TITLE
 Error: "A new session could not be created" when I use TestAgent and TestController 

### ISSUE THREAD

**Issue by AlonyParker** [Microsoft/WinAppDriver#34]
I configured Test Agent and Test Controllers for my test project in Visual Studio. 
  I install WinAppDriver on machine with test agent. 
  I try run this simple code:

[TestClass]
    public class TestWithSelenium 
    {
        private TestContext testContextInstance;
        public TestContext TestContext
        {
            get { return testContextInstance; }
            set { testContextInstance = value; }
        }
        protected const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723";
        protected static RemoteWebDriver NodepadSession;
        protected static RemoteWebElement NodepadResult;

```
    [ClassInitialize]
    public static void Setup(TestContext context)
    {

        DesiredCapabilities appCapabilities = new DesiredCapabilities();
        appCapabilities.SetCapability("app", @"C:\Windows\System32\notepad.exe");
        NodepadSession = new IOSDriver<IOSElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);

        NodepadSession.FindElementByClassName("Edit").SendKeys("This is some text");
    }

    [TestMethod]
    public void Addition()
    {
        Assert.IsNotNull(NodepadSession);
    }
```

}

```
Notepad is running, then test failed whith error:

Result Message: Class Initialization method Test_Progect.TestWithSelenium.Setup threw exception. System.InvalidOperationException: System.InvalidOperationException: A new session could not be created. (33).
```

Result StackTrace:  
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.iOS.IOSDriver`1..ctor(Uri remoteAddress, DesiredCapabilities desiredCapabilities)
   at Test_Progect.TestWithSelenium.Setup(TestContext context) in c:\Users\myuser\Documents\Visual Studio 2013\Projects\Test_Progect\Test_Progect\TestWithSelenium.cs:line 31

![000](https://cloud.githubusercontent.com/assets/19815772/15888246/d1416608-2d6e-11e6-9b79-7889322b74df.png)

**Comment by timotiusmargo** [comment]
HI @AlonyParker, could you please retry the same scenario on the latest [v0.6-beta](https://github.com/Microsoft/WinAppDriver/releases/tag/v0.6-beta) we released last week? The scenario seems to work fine for us when testing the **NotepadTest** sample below:
https://github.com/Microsoft/WinAppDriver/tree/v0.6-beta/Samples/C%23/NotepadTest

**Comment by yodurr** [comment]
closing stale issues, please re-open if this is still an active issue
