### ISSUE TITLE
Unable to run WinAppDriver on a remote machine in a headless fashion

### ISSUE THREAD

**Issue by BenBullock1992** [Microsoft/WinAppDriver#428]
Hello,

My team and I have been writing some automation tests in Java using Appium and WinAppDriver to test our C# .NET Windows desktop application.

We would like to run our automation tests as part of our CI/CD pipeline.

We can successfully run our tests against a remote machine as long as there is an active RDP session open.

If we minimise or close the RDP session we get the below error:
{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}

I understand that if this is to work, WinAppDriver needs to be ran in an "interactive" mode.

To achieve this, I tried running WinAppDriver as a service and setup the log on type to be interactive.

This failed to resolve the issue.

I've had a look through your issues page and can see several others are experiencing the same issue.

Do you have a workaround or any plans to resolve this issue?

Thanks,

Ben :)

**Comment by nmklotas** [comment]
Hi, this started happening to our team as well. For some time it was working, but now it randomly started to fail. When active & visible RDP session is on then tests run fine. We are using WFP app + GitLab CI runner which is started as interactive process. We get these errors:
Stack trace1:
```  Stack Trace:
           at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
           at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebElement.Click()
```
Stack trace2:
```
System.InvalidOperationException : An unknown error occurred in the remote end while processing the command.
      Stack Trace:
           at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
           at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
```
Is there any workarounds??

**Comment by bbullock-microgen** [comment]
Hi Julius,

My colleague posted our workaround on this thread: https://github.com/Microsoft/WinAppDriver/issues/147

Hope it works :)
