### ISSUE TITLE
Remote WinAppDriver testing session stops identifying objects partway through test

### ISSUE THREAD

**Issue by dsaner** [Microsoft/WinAppDriver#433]
After much pain and suffering, I was able to get my tests to open and execute on a remote VM via selenium grid and appium.  The test launches perfectly and begins the run exactly as expected.  Partway through the test execution however, the test fails due to the fact that WinAppDriver is unable to locate a checkbox.  The test is actually marking a series of checkboxes.  Sometimes it will fail on the 3rd.  Sometimes it makes it to 8.  Sometimes it goes to 13.  It fails at some random point, always with the same issue of being unable to locate the next checkbox.  I am using XPath to identify the checkbox.  This test works perfectly and runs to completion every time when run locally.  Does anyone have any ideas?

I'm running Appium 1.8.1

Here's the relevant part of the log shown in the appium command window:

[HTTP] --> POST /wd/hub/session/6066df66-f153-42f1-a9c3-1d8d8f2e25af/element
[HTTP] {"using":"accessibility id","value":"//*[starts-with(@Name,'8.')]/preceding-sibling::CheckBox[1]"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/6066df66-f153-42f1-a9c3-1d8d8f2e25af/element] to [POST http://127.0.0.1:4724/wd/hub/session/BDE8FC8F-EE60-4552-BEBD-788BC17430B4/element] with body: {"using":"accessibility id","value":"//*[starts-with(@Name,'8.')]/preceding-sibling::CheckBox[1]"}
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/BDE8FC8F-EE60-4552-BEBD-788BC17430B4/element HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 98
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"using":"accessibility id","value":"//*[starts-with(@Name,'8.')]/preceding-sibling::CheckBox[1]"}
[WinAppDriver] [STDOUT] HTTP/1.1 404 Not Found
[WinAppDriver] [STDOUT] Content-Length: 139
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
[W3C] Encountered internal error running command:  {"w3cStatus":404,"w3c":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}} ProxyRequestError: Could not proxy command to remote server. Original error: 404 - {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
[W3C]     at JWProxy.proxy$ (C:\Users\segrid\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
[W3C]     at tryCatch (C:\Users\segrid\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\segrid\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\segrid\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (C:\Users\segrid\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at <anonymous>
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[HTTP] <-- POST /wd/hub/session/6066df66-f153-42f1-a9c3-1d8d8f2e25af/element 404 214 ms - 1720

**Comment by hassanuz** [comment]
Hi @dsaner,

Can you provide a short snippet replicating the issue for repro? Another thing to try would be to add delay prior to the element query.

**Comment by dsaner** [comment]
I've tried delays all over the place to no avail.  The application I'm testing is not something I can share freely, so coming up with a test to reproduce the issue is going to take some work.  If I'm able to do so, I will.  Here's a snippet of the test code that's failing though, if that helps any:

answerAdjusterQuestion("1", "y");
answerAdjusterQuestion("2", "y");
answerAdjusterQuestion("3", "y");
.
.
.


public void answerAdjusterQuestion(String questionNumber, String yesOrNo) {
        if (yesOrNo.startsWith("y") || yesOrNo.startsWith("Y")) {
            checkCheckbox(getElement("//*[starts-with(@Name,'" + questionNumber +
                    ".')]/preceding-sibling::CheckBox[2]"), true);
        } else {
            checkCheckbox(getElement("//*[starts-with(@Name,'" + questionNumber +
                    ".')]/preceding-sibling::CheckBox[1]"), true);
        }
    }

**Comment by dsaner** [comment]
So, I was able to reproduce this error with the calculator sample.  It turns out that the issue is caused by creating multiple WinAppDriver sessions on the remote machine and letting one of them time out.  My original test works with my application and also works with a Root app session if certain conditions appear.  I was creating both sessions at the beginning of my script.  The required conditions for interacting with the Root session never occurred, so it eventually timed out (60 seconds is the default timeout) and appium killed the session.  This also then seems to kill the other session that I was actually using.  I was able to reproduce the behavior in the calculator sample by making the addition method run for over a minute after creating a Root app session and a Calculator app session, but never interacting with the Root session.  This doesn't seem like it should be working the way that it is.  If one session is killed, the other session should remain active.  Is this an appium defect, or WinAppDriver defect?  I can't say for certain.

**Comment by jsingh-qualitrol** [comment]
Hello, 
In may case also i was able to run my test script properly. Now i am facing element is not getting located. Though, it is existing in the page and it was clickable.

[JSONWP Proxy] Proxying [POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element] to [POST http://127.0.0.1:4724/wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/element] with body: {"using":"xpath","value":"/Window/Custom[5]/Group/Group/Group/DataGrid/Pane/TreeItem[4]/Custom"}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/element HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 96
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"using":"xpath","value":"/Window/Custom[5]/Group/Group/Group/DataGrid/Pane/TreeItem[4]/Custom"}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 102
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0,"value":{"ELEMENT":"7.26180.17558060"}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0,"value":{"ELEMENT":"7.26180.17558060"}}
[JSONWP Proxy] Replacing sessionId A3C04A39-DA71-4E15-B232-18211BAD7829 with 1ed2c7bc-d275-42fb-aa74-86c798008e04
[HTTP] <-- POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element 200 2379 ms - 102
[HTTP] 
[HTTP] --> POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element/7.26180.17558060/click
[HTTP] {"id":"7.26180.17558060"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element/7.26180.17558060/click] to [POST http://127.0.0.1:4724/wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/element/7.26180.17558060/click] with body: {"id":"7.26180.17558060"}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/element/7.26180.17558060/click HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 25
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"id":"7.26180.17558060"}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Replacing sessionId A3C04A39-DA71-4E15-B232-18211BAD7829 with 1ed2c7bc-d275-42fb-aa74-86c798008e04
[HTTP] <-- POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element/7.26180.17558060/click 200 344 ms - 63
[HTTP] 
[HTTP] --> GET /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element/7.26180.17558060/text
[HTTP] {}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element/7.26180.17558060/text] to [GET http://127.0.0.1:4724/wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/element/7.26180.17558060/text] with body: {}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] GET /wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/element/7.26180.17558060/text HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 82
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0,"value":"QTMSDNP3"}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"A3C04A39-DA71-4E15-B232-18211BAD7829\",\"status\":0,\"value\":\"QTMSDNP3\"}"
[JSONWP Proxy] Replacing sessionId A3C04A39-DA71-4E15-B232-18211BAD7829 with 1ed2c7bc-d275-42fb-aa74-86c798008e04
[HTTP] <-- GET /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element/7.26180.17558060/text 200 202 ms - 82
[HTTP] 
[HTTP] --> POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/moveto
[HTTP] {"element":"7.26180.17558060"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/moveto] to [POST http://127.0.0.1:4724/wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/moveto] with body: {"element":"7.26180.17558060"}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/moveto HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 30
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Replacing sessionId A3C04A39-DA71-4E15-B232-18211BAD7829 with 1ed2c7bc-d275-42fb-aa74-86c798008e04
[HTTP] <-- POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/moveto 200 11 ms - 63
[HTTP] 
[HTTP] --> POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/moveto
[HTTP] {"element":"7.26180.17558060"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/moveto] to [POST http://127.0.0.1:4724/wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/moveto] with body: {"element":"7.26180.17558060"}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/moveto HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 30
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Replacing sessionId A3C04A39-DA71-4E15-B232-18211BAD7829 with 1ed2c7bc-d275-42fb-aa74-86c798008e04
[HTTP] <-- POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/moveto 200 6 ms - 63
[HTTP] 
[HTTP] --> POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/click
[HTTP] {"button":2}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/click] to [POST http://127.0.0.1:4724/wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/click] with body: {"button":2}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/click HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 12
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"button":2}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Replacing sessionId A3C04A39-DA71-4E15-B232-18211BAD7829 with 1ed2c7bc-d275-42fb-aa74-86c798008e04
[HTTP] <-- POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/click 200 11 ms - 63
[HTTP] 
[HTTP] --> POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/keys
[HTTP] {"value":[""]}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/keys] to [POST http://127.0.0.1:4724/wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/keys] with body: {"value":[""]}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/keys HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 17
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"value":[""]}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Replacing sessionId A3C04A39-DA71-4E15-B232-18211BAD7829 with 1ed2c7bc-d275-42fb-aa74-86c798008e04
[HTTP] <-- POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/keys 200 999 ms - 63
[HTTP] 
[HTTP] --> POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/keys
[HTTP] {"value":[""]}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/keys] to [POST http://127.0.0.1:4724/wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/keys] with body: {"value":[""]}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/keys HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 17
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"value":[""]}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Replacing sessionId A3C04A39-DA71-4E15-B232-18211BAD7829 with 1ed2c7bc-d275-42fb-aa74-86c798008e04
[HTTP] <-- POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/keys 200 154 ms - 63
[HTTP] 
[HTTP] --> POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/keys
[HTTP] {"value":[""]}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/keys] to [POST http://127.0.0.1:4724/wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/keys] with body: {"value":[""]}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/keys HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 17
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"value":[""]}
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"A3C04A39-DA71-4E15-B232-18211BAD7829","status":0}
[JSONWP Proxy] Replacing sessionId A3C04A39-DA71-4E15-B232-18211BAD7829 with 1ed2c7bc-d275-42fb-aa74-86c798008e04
[HTTP] <-- POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/keys 200 166 ms - 63
[HTTP] 
[HTTP] --> POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element
[HTTP] {"using":"xpath","value":"/Window/Custom[5]/Group/Group/Group/DataGrid/Pane/TreeItem[2]/Custom"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element] to [POST http://127.0.0.1:4724/wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/element] with body: {"using":"xpath","value":"/Window/Custom[5]/Group/Group/Group/DataGrid/Pane/TreeItem[2]/Custom"}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/A3C04A39-DA71-4E15-B232-18211BAD7829/element HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 96
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"using":"xpath","value":"/Window/Custom[5]/Group/Group/Group/DataGrid/Pane/TreeItem[2]/Custom"}
[WinAppDriver] [STDOUT] HTTP/1.1 404 Not Found
[WinAppDriver] [STDOUT] Content-Length: 139
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
[W3C] Encountered internal error running command:  {"w3cStatus":404,"w3c":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}} ProxyRequestError: Could not proxy command to remote server. Original error: 404 - {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
[W3C]     at JWProxy.proxy$ (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
[W3C]     at tryCatch (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at 
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[HTTP] <-- POST /wd/hub/session/1ed2c7bc-d275-42fb-aa74-86c798008e04/element 404 2345 ms - 1965

**Comment by Chintzz** [comment]
Your issue seems to be due to the default timeout for appium server. We need to override the default timeout of the Appium server for "new Command" to resolve your issue. Try setting up the below capability while creating your session obj. It should solve your problem.

**capabilities.setCapabilities("newCommandTimeout", <your required time out interval in seconds>);**



//Sample code  while creating the session object using Java
**DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("app","Microsoft.WindowsAlarms_8wekyb3d8bbwe!App");
capabilities.setCapability("deviceName","Windos10");
capabilities.setCapability("newCommandTimeout",90);// setting appium servertimeout to 90 secs**

session = new WindowsDriver(new URL ("http://127.0.0.1:4723/wd/hub"),capabilities);

for more details on appium DesiredCapabilities --> [http://appium.io/docs/en/writing-running-appium/caps/]

**Comment by timotiusmargo** [comment]
Hi @dsaner,

As @Chintzz mentioned, the timeout you saw was set and triggers at the client side (e.g. Appium Dot Net Driver). When this timeout takes place, `WinAppDriver.exe` is still running and the sessions remain valid until explicitly terminated. I suggest debugging your test setup and the client library you are using to handle the scenario you are trying to accomplish.

**Comment by jsingh-qualitrol** [comment]
Hi @Chintzz @timotiusmargo  
Thanks for your prompt response.
I added capabilities.setCapabilities("newCommandTimeout", "your required time out interval in seconds"); in my Script but of no luck.
I am still getting exception as Element  was not clickable [Ljava.lang.StackTraceElement;@1f53a5dc.

**Comment by sandeepdroid** [comment]
I was having the same problem. On installing the latest WinAppDriver(v1.1) the issue is happening no more

**Comment by timotiusmargo** [comment]
Hi @jsingh-qualitrol,

Does the problem you saw, go along with the original issue such as it always works locally and somewhat occurs on certain setup configuration? Otherwise, would you please open a new issue and move your report there? What would help is to call and save [https://github.com/Microsoft/WinAppDriver/blob/v1.1-RC/Tests/WebDriverAPI/Source.cs#L41](session PageSource) right before you invoke the failing XPath find element in your test. When you include this XML snippet, it will become much clearer where the issues is at.

**Comment by jsingh-qualitrol** [comment]
Hi @timotiusmargo 
My issue doesn't work even in local. Hence, i had created a new issue #478

**Comment by sahilbin** [comment]
I had a similar issue where a particular button was not clickable on VM using CI but it was working fine locally.I tries with everything including the solutions mentioned in this thread but no luck.
Finally, i found that this was due a resolution problem..when i executed my code on a desktop instead of my laptop it worked fine on VM as well.
@dsaner please try using it on a different screen like one with bigger screen like a desktop

**Comment by timotiusmargo** [comment]
Hi @sahilbin,

Thanks for sharing your observation and finding. Let's see if the original issue reported by @dsaner is indeed screen resolution/dpi issue. Otherwise, would you kindly open a new issue laying out the problem you saw, the repro steps, and other observations?
