### ISSUE TITLE
Unknown command thrown when using FindsByWindowsAutomationAttribute

### ISSUE THREAD

**Issue by cosminstirbu** [Microsoft/WinAppDriver#454]
Hi,

Currently `appium-dotnet-driver` doesn't have support for using Page Objects and decorating them with Windows specific FindBy attributes.

I've added this functionality in this commit - https://github.com/cosminstirbu/appium-dotnet-driver/commit/e46b488a15ef6f7ce2c29a8cde186b777508fc89 (referenced here as well https://github.com/appium/appium-dotnet-driver/issues/237) but now I'm running into a "Unknown command" exception.

This is the log of my error:
```

[JSONWP Proxy] Got response with status 200: "{\"build\":{\"revision\":\"17001\",\"time\":\"Tue Oct 17 18:04:03 2017\",\"version\":\"1.0.1710\"},\"os\":{\"arch\":\"amd64\",\"name\":\"windows\",\"version\":\"10\"}}"
[WinAppDriver] Status call returned 200. we're online and ready to run tests
[WinAppDriver] WinAppDriver changed state to 'online'
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"Windows","newCommandTimeout":120,"app":"com.MyApp_x4f170a5xjzjc!App","deviceName":"WindowsPC"}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"09E7BE39-930F-4140-A36C-7326263E8C00","status":0,"value":{"app":"com.MyApp_x4f170a5xjzjc!App","platformName":"Windows"}}
[Appium] New WindowsDriver session created successfully, session 7e98d2e8-c91a-4b41-870d-4a69caf6c31e added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1531066896623 (19:21:36 GMT+0300 (GTB Daylight Time))
[MJSONWP] Responding to client with driver.createSession() result: {"platformName":"Windows","newCommandTimeout":120,"app":"com.bca.DealerProApp_x4f170a5xjzjc!App","deviceName":"WindowsPC"}
[HTTP] <-- POST /wd/hub/session 200 6052 ms - 194
[HTTP] 
[HTTP] --> POST /wd/hub/session/7e98d2e8-c91a-4b41-870d-4a69caf6c31e/timeouts
[HTTP] {"type":"implicit","ms":0}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/7e98d2e8-c91a-4b41-870d-4a69caf6c31e/timeouts] to [POST http://127.0.0.1:4724/wd/hub/session/09E7BE39-930F-4140-A36C-7326263E8C00/timeouts] with body: {"type":"implicit","ms":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"09E7BE39-930F-4140-A36C-7326263E8C00","status":0}
[JSONWP Proxy] Replacing sessionId 09E7BE39-930F-4140-A36C-7326263E8C00 with 7e98d2e8-c91a-4b41-870d-4a69caf6c31e
[HTTP] <-- POST /wd/hub/session/7e98d2e8-c91a-4b41-870d-4a69caf6c31e/timeouts 200 13 ms - 63
[HTTP] 
[HTTP] --> GET /wd/hub/session/7e98d2e8-c91a-4b41-870d-4a69caf6c31e/context
[HTTP] {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/7e98d2e8-c91a-4b41-870d-4a69caf6c31e/context] to [GET http://127.0.0.1:4724/wd/hub/session/09E7BE39-930F-4140-A36C-7326263E8C00/context] with body: {}
[MJSONWP] Encountered internal error running command:  {"w3cStatus":404,"w3c":{"error":"unknown command","message":"Command not recognized: GET: /session/09E7BE39-930F-4140-A36C-7326263E8C00/context"}} ProxyRequestError: Could not proxy command to remote server. Original error: 404 - "{\"status\":9,\"value\":{\"error\":\"unknown command\",\"message\":\"Command not recognized: GET: /session/09E7BE39-930F-4140-A36C-7326263E8C00/context\"}}"
[MJSONWP]     at JWProxy.proxy$ (C:\Users\stirb\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
[MJSONWP]     at tryCatch (C:\Users\stirb\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\stirb\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\stirb\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\stirb\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at 
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[HTTP] <-- GET /wd/hub/session/7e98d2e8-c91a-4b41-870d-4a69caf6c31e/context 500 20 ms - 333
```

This is how my page looks
```
    public class LoginPage : BasePage
    {
        private const string AddNewUserButton = "+";
        private const string UserNameLabel = "UsernameLabel";
        private const string RemoveUserButton = "CloseButton";

        [FindsByIOSUIAutomation(Accessibility = AddNewUserButton)]
        [FindsByWindowsAutomation(Accessibility = AddNewUserButton)]
        private IMobileElement<AppiumWebElement> _addNewUserButton;

        [FindsByIOSUIAutomation(Accessibility = UserNameLabel)]
        [FindsByWindowsAutomation(Accessibility = UserNameLabel)]
        private List<AppiumWebElement> _userNameList;

        [FindsByIOSUIAutomation(Accessibility = RemoveUserButton)]
        [FindsByWindowsAutomation(Accessibility = UserNameLabel)]
        private List<AppiumWebElement> _removeUserButton;

        public LoginPage()
        {
            PageFactory.InitElements(Driver, this, new AppiumPageObjectMemberDecorator());
        }
    }
```

Any suggestions on how we could work around this?

Thank you,
Cosmin

**Comment by cosminstirbu** [comment]
It's strange however because if I use

        [FindsBy(How = How.Name, Using = AddNewUserButton)]
        private IWebElement _addNewUserButton;

and

        public LoginPage()
        {
            PageFactory.InitElements(Driver, this);
        }

then everything works.

However, this approach doesn't let me use different lookup strategies for iOS and UWP.

**Comment by cosminstirbu** [comment]
It looks that this is the piece of code where the exception is caught / re-thrown

In `SearchingInterceptor`

internal static Func<IElementLocator, ReadOnlyCollection<IWebElement>> ReturnWaitingFunction(IElementLocator locator,
            IEnumerable<By> bys)
        {
            return (IElementLocator) =>
            {
                List<IWebElement> result = new List<IWebElement>();

                foreach (var by in bys)
                {
                    try
                    {
                        List<By> listOfSingleBy = new List<By>();
                        listOfSingleBy.Add(by);
                        result.AddRange(locator.LocateElements(listOfSingleBy));
                    }
                    catch (NoSuchElementException e)
                    {
                        continue;
                    }
                    catch (Exception e)
                    {
                        throw e;
                    }

                }
                if (result.Count > 0)
                    return result.AsReadOnly();

                return null;
            };
        }
