### ISSUE TITLE
Can't run tests: Unable to connect to the remote server

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/WinAppDriver#457]
I downloaded the EXE and also the samples, and launched the C# Calculator Visual Studio solution, and followed the README instructions...

1. Built the solution
2. Opened test explorer
3. Ran a test

It fails with the following exception

```
Message: Class Initialization method CalculatorTest.ScenarioStandard.ClassInitialize threw exception. OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:4723
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters).
```

**Comment by andrewleader** [comment]
Issue was that WinAppDriver wasn't installed nor running. Those instructions should be added to the readme of the project file (right now they're hidden in the lengthy homepage readme)
