### ISSUE TITLE
WinAppDriver could not run Application

### ISSUE THREAD

**Issue by denys-rwd** [Microsoft/WinAppDriver#49]
Suddenly, WinAppDrive could not run Application.
On WinAppDriver console, there is message 'HTTP 404 error'

Need your help.

Thanks in advance

![image](https://cloud.githubusercontent.com/assets/18639833/17207608/07b0710e-54be-11e6-83b0-8d0736be88b5.png)

**Code**
` DesiredCapabilities capabilities = new DesiredCapabilities();
   capabilities.setCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");

 RemoteWebDriver rwd =  new RemoteWebDriver(new URL("http://172.30.201.161:80/wd"), capabilities);`

**Exception**
`com.perfectomobile.web.selenium.executor.surface.CalculatorSurface`
**org.openqa.selenium.UnsupportedCommandException**`: Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
System info: host: 'ws-denyss-7', ip: '172.30.200.115', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
`

**Comment by alakshmi1030** [comment]
The default path for WinAppDriver does not contain "/wd". Can you doublecheck that WinAppDriver is listening on /wd? Also port 80 is reserved for HTTP - try with a different port.

**Comment by denys-rwd** [comment]
You are right, URL contains /wd. Why not to support the URI by default?
