### ISSUE TITLE
Issue:  After upgrading appium to v1.8.1 and Ipad platform version to 11.4 ,  I am not able use driver.findelement  commands 

### ISSUE THREAD

**Issue by raghubhoje** [Microsoft/WinAppDriver#494]
Issue description:  My Ipad version was updated to 11.4 from 11.2,  after that I updated my Xcode to 9.4.1,  next I upgraded appium to v1.8.1 from (v1.7.1 ) – it launches the application but fails to perform any actions like driver.findElement(By.id("pin")).click();
Logs shows:
MJSONWP] Encountered internal error running command: Error: An error occurred
[MJSONWP]     at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)

My code is below
DesiredCapabilities capabilities = new DesiredCapabilities();		
		capabilities.setCapability("platformVersion", "11.4");
		capabilities.setCapability("platformName", "iOS");		
		//capabilities.setCapability("deviceName", " Test iPad Pro");		
		capabilities.setCapability("deviceName", "iPad");		
		capabilities.setCapability("xcodeOrgid", "XX");		
		capabilities.setCapability("xcodeSigningId", "XXX");		
		// iPad 12.9 inch UDID 
		 capabilities.setCapability("udid", "XX");		
		capabilities.setCapability("maxTypeFrequency",5);		
		capabilities.setCapability("automationName", "XCUITest");		
		capabilities.setCapability("noReset", "true");		
		File app = new File("/Users/svc-mac/Desktop/ Quoting.ipa");
		capabilities.setCapability("app", app.getAbsolutePath());
		
		driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);		
		Thread.sleep(5000); //implicit Thread.sleep 		
		      driver.findElement(By.id("pin1")).click();

Environment:
Real device iPad – platform Version: 11.4
Appium Desktop – v1.8.1 
Eclipse:  Version Oxygen.2 Release (4.7.2)

Appium logs:

Appium] Welcome to Appium v1.8.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/svc-mac/Desktop/Appium PM Quoting.ipa","automationName":"XCUITest","deviceName":"Dan'siPad","maxTypeFrequency":5,"noReset":"true","platformName":"iOS","platformVersion":"11.4","udid":"0f3a6bddb004883fb29de4c28b91751190866764","xcodeOrgid":"LEZPAXBKR6","xcodeSigningId":"89371bd9-25cf-4526-bfec-e053517a9838"},"capabilities":{"desiredCapabilities":{"app":"/Users/svc-mac/Desktop/Appium PM Quoting.ipa","automationName":"XCUITest","deviceName":"Dan'siPad","maxTypeFrequency":5,"noReset":"true","platformName":"iOS","platformVersion":"11.4","udid":"0f3a6bddb004883fb29de4c28b91751190866764","xcodeOrgid":"LEZPAXBKR6","xcodeSigningId":"89371bd9-25cf-4526-bfec-e053517a9838"},"firstMatch":[{"platformName":"ios"}]}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/svc-mac/Desktop/Appium PM Quoting.ipa","automationName":"XCUITest","deviceName":"Dan'siPad","maxTypeFrequency":5,"noReset":"true","platformName":"iOS","platformVersion":"11.4","udid":"0f3a6bddb004883fb29de4c28b91751190866764","xcodeOrgid":"LEZPAXBKR6","xcodeSigningId":"89371bd9-25cf-4526-bfec-e053517a9838"},null,{"desiredCapabilities":{"app":"/Users/svc-mac/Desktop/Appium PM Quoting.ipa","automationName":"XCUITest","deviceName":"Dan'siPad","maxTypeFrequency":5,"noReset":"true","platformName":"iOS","platformVersion":"11.4","udid":"0f3a6bddb004883fb29de4c28b91751190866764","xcodeOrgid":"LEZPAXBKR6","xcodeSigningId":"89371bd9-25cf-4526-bfec-e053517a9838"},"firstMatch":[{"platformName":"ios"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1536253645549 (12:07:25 GMT-0500 (CDT))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank. Falling back to JSONWP protocol.
[Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["app","automationName","deviceName","maxTypeFrequency","noReset","platformName","platformVersion","udid","xcodeOrgid","xcodeSigningId"]. Falling back to JSONWP protocol.
[Appium] Creating new XCUITestDriver (v2.84.0) session
[Appium] Capabilities:
[Appium]   app: /Users/svc-mac/Desktop/Appium PM Quoting.ipa
[Appium]   automationName: XCUITest
[Appium]   deviceName: Dan'siPad
[Appium]   maxTypeFrequency: 5
[Appium]   noReset: true
[Appium]   platformName: iOS
[Appium]   platformVersion: 11.4
[Appium]   udid: 0f3a6bddb004883fb29de4c28b91751190866764
[Appium]   xcodeOrgid: LEZPAXBKR6
[Appium]   xcodeSigningId: 89371bd9-25cf-4526-bfec-e053517a9838
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/svc-mac/Desk...
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: maxTypeFrequency, xcodeOrgid.
[BaseDriver] Session created with session id: 799a8b5f-2922-4816-8612-02a64c7239e2
[XCUITest] Current user: 'svc-mac'
[XCUITest] Xcode version set to '9.4.1' 
[XCUITest] iOS SDK Version set to '11.4'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1536253645729 (12:07:25 GMT-0500 (CDT))
[XCUITest] Available devices: 0f3a6bddb004883fb29de4c28b91751190866764
[XCUITest] Creating iDevice object with udid '0f3a6bddb004883fb29de4c28b91751190866764'
[XCUITest] Determining device to run tests on: udid: '0f3a6bddb004883fb29de4c28b91751190866764', real device: true
[BaseDriver] Using local app '/Users/svc-mac/Desktop/Appium PM Quoting.ipa'
[BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping local app '/var/folders/xh/br5ky4ms6n3115k2fmxwgb_1p1g0pb/T/201886-12734-q48t4t.y0x1/appium-app.zip'...
[BaseDriver] Unzipping /var/folders/xh/br5ky4ms6n3115k2fmxwgb_1p1g0pb/T/201886-12734-q48t4t.y0x1/appium-app.zip
[BaseDriver] Testing zip archive: /var/folders/xh/br5ky4ms6n3115k2fmxwgb_1p1g0pb/T/201886-12734-q48t4t.y0x1/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/xh/br5ky4ms6n3115k2fmxwgb_1p1g0pb/T/201886-12734-q48t4t.y0x1/Payload/Appium PM Quoting.app'
[BaseDriver] Event 'appConfigured' logged at 1536253646391 (12:07:26 GMT-0500 (CDT))
[XCUITest] Checking whether app '/var/folders/xh/br5ky4ms6n3115k2fmxwgb_1p1g0pb/T/201886-12734-q48t4t.y0x1/Payload/Appium PM Quoting.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/var/folders/xh/br5ky4ms6n3115k2fmxwgb_1p1g0pb/T/201886-12734-q48t4t.y0x1/Payload/Appium PM Quoting.app': 'com.pmic.mobilequoting.appium'
[BaseDriver] Event 'resetStarted' logged at 1536253646393 (12:07:26 GMT-0500 (CDT))
[XCUITest] Reset: fullReset not set. Leaving as is
[BaseDriver] Event 'resetComplete' logged at 1536253646394 (12:07:26 GMT-0500 (CDT))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[XCUITest] Cannot get the name of the crashes folder for the device with udid '0f3a6bddb004883fb29de4c28b91751190866764'. Original error: Command 'idevicename -u 0f3a6bddb004883fb29de4c28b91751190866764' exited with code 255
[BaseDriver] Event 'logCaptureStarted' logged at 1536253647070 (12:07:27 GMT-0500 (CDT))
[XCUITest] Setting up real device
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] App 'com.pmic.mobilequoting.appium' is already installed. No need to reinstall.
[BaseDriver] Event 'appInstalled' logged at 1536253647344 (12:07:27 GMT-0500 (CDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] WDA is not listening at 'http://localhost:8100/'
[BaseDriver] Event 'wdaStartAttempted' logged at 1536253650421 (12:07:30 GMT-0500 (CDT))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*0f3a6bddb004883fb29de4c28b91751190866764, iproxy 8100' for the device 0f3a6bddb004883fb29de4c28b91751190866764...
[XCUITest] 'pgrep -nif xcodebuild.*0f3a6bddb004883fb29de4c28b91751190866764' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Using Xcode 9.4.1, so fixing WDA codebase
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=0f3a6bddb004883fb29de4c28b91751190866764 IPHONEOS_DEPLOYMENT_TARGET=11.4' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /var/folders/xh/br5ky4ms6n3115k2fmxwgb_1p1g0pb/T/com.apple.dt.XCTest/IDETestRunSession-39A4A00C-D040-437D-8BB7-8411177209CE/WebDriverAgentRunner-13421928-54DC-4202-B7CC-601F3844A401/Session-WebDriverAgentRunner-2018-09-06_120737-gGjqsG.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4.1\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4.1\",\n      \"ip\" : \"10.84.0.66\"\n    },\n    \"build\" : {\n      \"time\" : \"Aug 31 2018 14:25:27\"\n    }\n  },\n  \"sessionId\" : \"8A1E4DF3-E3D4-45D0-9A65-F9B346EA9FF0\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '10.84.0.66'
[XCUITest] WebDriverAgent successfully started after 7669ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1536253663171 (12:07:43 GMT-0500 (CDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.pmic.mobilequoting.appium","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"81518F0C-B7BD-4B68-830C-2181C24E88D5","capabilities":{"device":"ipad","browserName":"Appium PM Quoting","sdkVersion":"11.4.1","CFBundleIdentifier":"com.pmic.mobilequoting.appium"}},"sessionId":"81518F0C-B7BD-4B68-830C-2181C24E88D5","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1536253665304 (12:07:45 GMT-0500 (CDT))
[BaseDriver] Event 'wdaStarted' logged at 1536253665304 (12:07:45 GMT-0500 (CDT))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1536253665305 (12:07:45 GMT-0500 (CDT))
[Appium] New XCUITestDriver session created successfully, session 799a8b5f-2922-4816-8612-02a64c7239e2 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1536253665307 (12:07:45 GMT-0500 (CDT))
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"app":"/Users/svc-mac/Desktop/Appium PM Quoting.ipa","automationName":"XCUITest","deviceName":"Dan'siPad","maxTypeFrequency":5,"noReset":true,"platformName":"iOS","platformVersion":"11.4","udid":"0f3a6bddb004883fb29de4c28b91751190866764","xcodeOrgid":"LEZPAXBKR6","xcodeSigningId":"89371bd9-25cf-4526-bfec-e053517a9838"}
[HTTP] <-- POST /wd/hub/session 200 19764 ms - 589
[HTTP] 
[HTTP] --> POST /wd/hub/session/799a8b5f-2922-4816-8612-02a64c7239e2/element
[HTTP] {"using":"id","value":"pin1"}
[W3C] Calling AppiumDriver.findElement() with args: ["id","pin1","799a8b5f-2922-4816-8612-02a64c7239e2"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/81518F0C-B7BD-4B68-830C-2181C24E88D5/element] with body: {"using":"id","value":"pin1"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"BD749CB0-49D3-437E-A20C-81F5C18870C6"},"sessionId":"81518F0C-B7BD-4B68-830C-2181C24E88D5","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"BD749CB0-49D3-437E-A20C-81F5C18870C6"}
[HTTP] <-- POST /wd/hub/session/799a8b5f-2922-4816-8612-02a64c7239e2/element 200 700 ms - 122
[HTTP] 
[HTTP] --> GET /wd/hub/session/799a8b5f-2922-4816-8612-02a64c7239e2
[HTTP] {}
[W3C] Calling AppiumDriver.getSession() with args: ["799a8b5f-2922-4816-8612-02a64c7239e2"]
[XCUITest] Executing command 'getSession'
[JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8100/session/81518F0C-B7BD-4B68-830C-2181C24E88D5] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"sessionId\" : \"81518F0C-B7BD-4B68-830C-2181C24E88D5\",\n    \"capabilities\" : {\n      \"device\" : \"ipad\",\n      \"browserName\" : \"Appium PM Quoting\",\n      \"sdkVersion\" : \"11.4.1\",\n      \"CFBundleIdentifier\" : \"com.pmic.mobilequoting.appium\"\n    }\n  },\n  \"sessionId\" : \"81518F0C-B7BD-4B68-830C-2181C24E88D5\",\n  \"status\" : 0\n}"
[XCUITest] Merging WDA caps over Appium caps for session detail response
[JSONWP Proxy] Proxying [GET /wda/screen] to [GET http://localhost:8100/session/81518F0C-B7BD-4B68-830C-2181C24E88D5/wda/screen] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/81518F0C-B7BD-4B68-830C-2181C24E88D5\\/wda\\/screen -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/81518F0C-B7BD-4B68-830C-2181C24E88D5\\/wda\\/screen\\\"\\n    );\\n}\",\n  \"sessionId\" : \"81518F0C-B7BD-4B68-830C-2181C24E88D5\",\n  \"status\" : 1\n}"
[MJSONWP] Encountered internal error running command: Error: An error occurred
[MJSONWP]     at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- GET /wd/hub/session/799a8b5f-2922-4816-8612-02a64c7239e2 500 106 ms - 188
[HTTP]

**Comment by timotiusmargo** [comment]
Hi @raghubhoje,

This issue belongs to the Appium project instead of WinAppDriver that specifically enables automation on Windows. You should file the bug in either one of these projects instead.
https://github.com/appium/appium
https://github.com/appium/appium-ios-driver
https://github.com/appium/appium-xcuitest-driver

**Comment by raghubhoje** [comment]
sure - thanks.
