### ISSUE TITLE
Unable to create new remote session

### ISSUE THREAD

**Issue by yanan58** [microsoft/WinAppDriver#557]
I'm trying to start our WPF application.

Here are what I have done:
1. Followed the instruction "Running on a Remote Machine" in 
            https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/289a8b325d3ddab9f08b4398c49163a9a136f607#what-to-do-when-an-application-has-a-splash-screen-or-winappdriver-fails-to-recognize-the-correct-window
       Note: I started WinAppDriver without "/wd/hub" since I want to use WinAppDriver standalone

2. Java code for starting up a WPF app:
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("deviceName", "WindowsPC");
            capabilities.setCapability("app", "C:\\Users\\xyz\\Desktop\\sv14web00041.appref-ms");
            appSession = new WindowsDriver<WindowsElement>(new URL("http://127.0.0.1:4723"), capabilities);
            Assert.assertNotNull(appSession);
            String winHandle = appSession.getWindowHandle();
            Thread.sleep(50000);

      Note: I tried both 127.0.0.1 and local IP 

Log:
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=C:\Users\xyz\Desktop\sv14web00041.appref-ms, platformName=Windows, deviceName=WindowsPC}], required capabilities = Capabilities [{}]
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'xyz', ip: '10.xx.xx.xx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: WindowsDriver
	at io.appium.java_client.remote.AppiumProtocolHandShake.lambda$1(AppiumProtocolHandShake.java:95)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:95)
	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:111)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.windows.WindowsDriver.<init>(WindowsDriver.java:43)
	at src.test.SystemManagementCenter.EagleSystemManagementCenterUiTest.setUp(EagleSystemManagementCenterUiTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
                  
Message from WinAppDriver console:

       POST /session HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 182
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_171)

{"capabilities":[{"desiredCapabilities":{"app":"C:\\Users\\xyz\\Desktop\\sv14web00041.appref-ms","platformName":"Windows","deviceName":"WindowsPC"}},{"requiredCapabilities":{}}]}
HTTP/1.1 400 Bad Request
Content-Length: 141
Content-Type: application/json

{"status":100,"value":{"error":"invalid argument","message":"Bad capabilities. Specify either app or appTopLevelWindow to create a session"}}

Any assistant would be truly appreciated.

**Comment by hassanuz** [comment]
Hi @yanan58,

What kind of app are you trying to automate? It seems that the remote connection with WinAppDriver is successful, but it is unable to locate the desired application. 

Is there a .exe that you can target instead of the .apppref-ms (as this is just a reference and not the executable)?

**Comment by yanan58** [comment]
It's a WPF app. I open it by double clicking on an 'Application Reference' icon on desktop.
There is a splash screen before the app login window. 
When ran the test scripts, I saw the splash screen opened/closed then two login windows were opened before SessionNotCreatedException

**Comment by yanan58** [comment]
From 'Task Manager' I found a .exe. But when I changed appId to the .exe, a app login window opened, but it was not the right app I want to open.

**Comment by hassanuz** [comment]
Is there an appx-recipe for the WPF app? If so, instead of using the URL in the packageID, you should be using the generated `RegisteredUserModeID`

From [ReadMe](https://github.com/Microsoft/WinAppDriver/tree/v1.1):

> You can find the Application Id of your application in the generated AppX\vs.appxrecipe file under RegisteredUserModeAppID node. E.g. c24c8163-548e-4b84-a466-530178fc0580_scyf5npe3hv32!App

**Comment by yanan58** [comment]
I got a standalone app, now I can get a new connection. 
But I'm blocked by new issues.

My  test script in java:
`DesiredCapabilities capabilities = new DesiredCapabilities();`
            `capabilities.setCapability("deviceName", "WindowsPC");`
            `capabilities.setCapability("app", appId);`
            `appSession = new WindowsDriver<WindowsElement>(new URL(winAppDriverUrl), capabilities);`
            `Assert.assertNotNull(appSession);`           
            `appSession.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);`            
            `appSession.findElementByAccessibilityId("EagleLoginUserName").click();`
            `appSession.findElementByAccessibilityId("EagleLoginUserName").setValue("abc");`

Got error:
`Connected to the target VM, address: '127.0.0.1:62993', transport: 'socket'
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.13 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: '460A', ip: '10.80.32.124', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: io.appium.java_client.windows.WindowsDriver
Capabilities [{app=C:\EagleStandaloneO171\Shell.exe, platformName=Windows, platform=ANY}]
Session ID: 30B795F5-CCAA-411C-A18E-61EE4DCCE0D3
*** Element info: {Using=accessibility id, value=EagleLoginUserName}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:371)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElement(WindowsDriver.java:1)
	at io.appium.java_client.FindsByAccessibilityId.findElementByAccessibilityId(FindsByAccessibilityId.java:31)` 

I modified test script as below :
`DesiredCapabilities appCapabilities = new DesiredCapabilities();`
           `appCapabilities.setCapability("deviceName", "WindowsPC");`
            `appCapabilities.setCapability("app", appId);`
            `eagleAppSession = new WindowsDriver<WindowsElement>(new URL(winAppDriverUrl), appCapabilities);`
            `Thread.sleep(2000);`  
            `DesiredCapabilities deskTopCapabilities = new DesiredCapabilities();`
            `deskTopCapabilities.setCapability("platformName", "Windows");`
            `deskTopCapabilities.setCapability("deviceName", "WindowsPC");`
            `deskTopCapabilities.setCapability("app", "Root");`
            `deskTopSession = new WindowsDriver<WindowsElement>(new URL(winAppDriverUrl), deskTopCapabilities);`
            `Assert.assertNotNull(deskTopSession);`
            `List<WindowsElement> eagleWindow = deskTopSession.findElementsByClassName("EagleChildWindow");`
            `String winHandle = eagleWindow.get(0).getAttribute("NativeWindowHandle");`

Got error:
`java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to io.appium.java_client.windows.WindowsElement`

**Comment by prasanna532** [comment]
Start winapp driver like this WinAppDriver.exe **ipaddress** 4723/wd/hub

below is the code which is working fine

private static WindowsDriver<RemoteWebElement> driver = null;
	
	public static void driverInstance() throws Exception 
	{
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("app", "Root");
		capabilities.setCapability("deviceName", "WindowsPC");
		capabilities.setCapability("platformName", "Windows");
		driver = new WindowsDriver<RemoteWebElement>(new URL("http://"+"**ipAddress**:4723/wd/hub"), capabilities);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	}

**Comment by yanan58** [comment]
I made the changes as you mentioned:
> DesiredCapabilities appCapabilities = new DesiredCapabilities();
            appCapabilities.setCapability("deviceName", "WindowsPC");
            appCapabilities.setCapability("app", appId);
            eagleAppSession = new WindowsDriver<RemoteWebElement>(new URL(winAppDriverUrl), appCapabilities);
            Thread.sleep(2000);
            Assert.assertNotNull(eagleAppSession);
            //Desktop root attach
            DesiredCapabilities deskTopCapabilities = new DesiredCapabilities();
            deskTopCapabilities.setCapability("platformName", "Windows");
            deskTopCapabilities.setCapability("deviceName", "WindowsPC");
            deskTopCapabilities.setCapability("app", "Root");
            deskTopSession = new WindowsDriver<RemoteWebElement>(new URL("http://127.0.0.1:4723/wd/hub"), deskTopCapabilities);
>

Got error: when executed the last line:

> org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=Root, platformName=Windows, deviceName=WindowsPC}], required capabilities = Capabilities [{}]

>

**Comment by prasanna532** [comment]
are you executing in remote machine or in local machine...

**Comment by yanan58** [comment]
Local

**Comment by prasanna532** [comment]
Start winapp driver like this WinAppDriver.exe ipaddress of your machine 4723/wd/hub **Have done this Step**

**Comment by prasanna532** [comment]
> Local.
> I changed `"new WindowsDriver<WindowsElement>()" `to `"new WindowsDriver<RemoteWebElement>()"` based on your example

Yes if you you do that you wont get Casting exception as i also faced same issue after doing that way it got resolved...

**Comment by prasanna532** [comment]
If your are running in local you can go with the 127.0.0.1 or You can keep ipaddress also no issues. You need to keep the ipaddress only in case your running in Remote machines. like grid way.

Have you done this step C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe **ipadddress** 4723/wd/hub

**Comment by yanan58** [comment]
WinAppDriver.exe ipadddress 4723/wd/hub fixed the problem

**Comment by prasanna532** [comment]
Cool.......

**Comment by yanan58** [comment]
One more ( I hope this is the last question :)  )
How to switch to the app I want to test? My code is below:
````
DesiredCapabilities appCapabilities = new DesiredCapabilities();
            appCapabilities.setCapability("deviceName", "WindowsPC");
            appCapabilities.setCapability("app", appId);
            eagleAppSession = new WindowsDriver<RemoteWebElement>(new URL(winAppDriverUrl), appCapabilities);
            Thread.sleep(2000);
            Assert.assertNotNull(eagleAppSession);
            //Desktop root attach
            DesiredCapabilities deskTopCapabilities = new DesiredCapabilities();
            deskTopCapabilities.setCapability("platformName", "Windows");
            deskTopCapabilities.setCapability("deviceName", "WindowsPC");
            deskTopCapabilities.setCapability("app", "Root");
            deskTopSession = new WindowsDriver<RemoteWebElement>(new URL(winAppDriverUrl), deskTopCapabilities);
            deskTopSession.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
            RemoteWebElement eagleWindow = deskTopSession.findElement(By.className("EagleChildWindow"));
            String winHandle = eagleWindow.getAttribute("NativeWindowHandle");
            DesiredCapabilities QAappCapabilities = new DesiredCapabilities();
            appCapabilities.setCapability("appTopLevelWindow", winHandle);
            WindowsDriver<WindowsElement> QASession = new WindowsDriver<RemoteWebElement>(new URL(winAppDriverUrl), QAappCapabilities);
            QASession.findElementByName("User Name:").click();
            QASession.findElementByName("User Name:").setValue("UserA");
            QASession.findElementByName("Password:").click();
            QASession.findElementByName("Password:").setValue("sample");
````

It fiailed at `WindowsDriver<RemoteWebElement> QASession = new WindowsDriver<RemoteWebElement>(new URL(winAppDriverUrl), QAappCapabilities);`

with Error `org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{platformName=Windows}], required capabilities = Capabilities [{}]`

**Comment by yanan58** [comment]
Thank you for helped me moved to your stage :)

**Comment by hassanuz** [comment]
Hi @yanan58,

This following should be **QAappCapabilities**, no? 
`            appCapabilities.setCapability("appTopLevelWindow", winHandle);
`

**Comment by pvpoli** [comment]
Hi
I'm having a similar problem. I'm trying to run a test with Maven in Intellij but I keep getting the "Bad capabilities" error message. With python an analogous code work as expected. Below is a simple example code and the logs from both Java and from WinAppDriver. At the end of this message I'll also post the WinAppDriver log from python. Comparing the both WinAppLogs (Java and Python runs), I'm under the impression that the Json is not well formated in Java. Does it make any sense? 
Thank you for any tip.

Java code example:
`import io.appium.java_client.windows.WindowsDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import java.net.URL;


public class Windows {
    private static WindowsDriver driver = null;

    @BeforeMethod
    public static void startSession() {
        try{
        DesiredCapabilities desired_caps = new DesiredCapabilities();
        desired_caps.setCapability("app", "C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE");
        desired_caps.setCapability("platformName", "Windows");
        desired_caps.setCapability("deviceName", "WindowsPC");
        desired_caps.setCapability("automationName", "Windows");

        driver = new WindowsDriver(new URL("http://127.0.0.1:4723"), desired_caps);
        }catch(Exception e){
            e.printStackTrace();
        } finally {
        }
    }

    @Test
    public void thisIsATest(){
        return;
    }
}`

Java Log
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: Bad capabilities. Specify either app or appTopLevelWindow to create a session
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'LFR050334', ip: '192.168.0.18', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15'
Driver info: io.appium.java_client.windows.WindowsDriver
Command: [null, newSession {capabilities=[{appium:app=C:\Program Files (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE, appium:automationName=Windows, appium:deviceName=WindowsPC, platformName=Windows}], desiredCapabilities=Capabilities {app: C:\Program Files (x86)\Micr..., automationName: Windows, deviceName: WindowsPC, platformName: Windows}}]
Capabilities {}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:126)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:146)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:225)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:168)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:79)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:87)
	at io.appium.java_client.windows.WindowsDriver.<init>(WindowsDriver.java:48)
	at Windowst.Windows.startSession(Windows.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)`
	
WinAppDriver Log:
`POST /session HTTP/1.1
Accept: */*
Content-Length: 305
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/4.0.0 (java windows)
X-Idempotency-Key: 42a9a1e7-0ac6-401d-80d1-d6ea9baa5bf1

{
  "capabilities": {
    "firstMatch": [
      {
      }
    ],
    "alwaysMatch": {
      "appium:app": "C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE",
      "appium:automationName": "Windows",
      "appium:deviceName": "WindowsPC",
      "platformName": "windows"
    }
  }
}
HTTP/1.1 400 Bad Request
Content-Length: 141
Content-Type: application/json

{"status":100,"value":{"error":"invalid argument","message":"Bad capabilities. Specify either app or appTopLevelWindow to create a session"}}`

WinAppDriver log from the python run:
`POST /session HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 410
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 1.3.0 (selenium/3.141.0 (python windows))
X-Idempotency-Key: 46f91f28-da2f-4bc7-a5bf-662638f03866

{"capabilities": {"firstMatch": [{"appium:app": "C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE", "platformName": "Windows", "appium:deviceName": "WindowsPC", "appium:automationName": "Windows"}]}, "desiredCapabilities": {"app": "C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE", "platformName": "Windows", "deviceName": "WindowsPC", "automationName": "Windows"}}
HTTP/1.1 200 OK
Content-Length: 177
Content-Type: application/json`

**Comment by IlyaSemenov** [comment]
Make sure you're using Appium-Python-Client==0.24 and selenium==3.5.0 and not the current releases which are not compatible with WinAppDriver API.
