### ISSUE TITLE
Getting error when i run my automation script

### ISSUE THREAD

**Issue by Maohan1989** [Microsoft/WinAppDriver#597]
Exception in thread "main" java.lang.NoSuchMethodError: org.openqa.selenium.remote.http.HttpClient$Factory.createDefault()Lorg/openqa/selenium/remote/http/HttpClient$Factory;
	at io.appium.java_client.remote.AppiumCommandExecutor.<init>(AppiumCommandExecutor.java:93)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.windows.WindowsDriver.<init>(WindowsDriver.java:42)
	at com.desktop.automation.test.Test.main(Test.java:29)

**Comment by Maohan1989** [comment]
Please any one can help me on this to resolve this issue?

**Comment by yodurr** [comment]
can you provide more info on your setup?  The Java libraries will likely need to use a generic class like RemoteWebDriver as you're doing.  Getting the capabilities set up correctly is likely where you're hitting issues.

**Comment by Maohan1989** [comment]
If i add a dependency in pom.xml my scripts are working fine. If i add a jar file i am getting the above error.
