### ISSUE TITLE
Unable to run my automation script by creating instance of WindowsDriver

### ISSUE THREAD

**Issue by Maohan1989** [Microsoft/WinAppDriver#598]
I am unable to run my automation script using 
WindowsDriver<WindowsElement> driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/"), capabilities);

But i am able to do with
RemoteWebDriver driver = new RemoteWebDriver (new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

what is the difference and why am i facing this issue. Missing anything?If i use the first one i will get error as 

Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/remote/JsonException
	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:110)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.windows.WindowsDriver.<init>(WindowsDriver.java:43)
	at com.desktop.automation.pharmacy.Pharmacy.main(Test.java:28)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.JsonException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more

**Comment by timotiusmargo** [comment]
Hi @Maohan1989,

When you run `WinAppDriver.exe` directly by itself without any argument, it will start a web server listening at `http://127.0.0.1:4723/`. When you are using **Appium** however, it will listen to `http://127.0.0.1:4723/wd/hub` as **Appium** internally runs `WinAppDriver.exe` and configures it to have the `wd/hub` prefix.
