### ISSUE TITLE
Getting DLLNotFound Exception

### ISSUE THREAD

**Issue by alienlan** [Microsoft/WinAppDriver#664]
Sorry, newb here. Did I miss something? Inspect works, and generally Winappdriver is working, but cannot get it to run. Any ideas?

Thanks,
Brian

System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'UIXPathLib.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=WinAppDriverUIRecorder
  StackTrace:
   at WinAppDriverUIRecorder.NativeMethods.InitUiTreeWalk()
   at WinAppDriverUIRecorder.App.OnStartup(StartupEventArgs e) in C:\Users\bmint\source\repos\icloud_windows_automation\WinAppDriver\Tools\UIRecorder\UiRecorder\App.xaml.cs:line 90
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WinAppDriverUIRecorder.App.Main()

**Comment by clintmasden** [comment]
If the Dll Exists in the Bin/Debug / wherever the executable is, then you're most likely missing the Visual C++ 2017 Redistribution, otherwise you have to build it first and place it or build it into that directory.

**Comment by JunlinZhu** [comment]
Try change the Solution platform from “Any CPU” to “x86” or ”x64” and see if it works.

**Comment by ianceicys** [comment]
Running in x64 mode fixed the issue for me! 
![image](https://user-images.githubusercontent.com/3976990/59698442-b26f5d00-91bd-11e9-9ad9-66412c4bd49a.png)

**Comment by guxialv** [comment]
My Solution: add vc lib:  vcruntime140.dll, msvcp140.dll
 https://stackoverflow.com/questions/2093485/system-dllnotfoundexception-unable-to-load-dll-on-window-2003

**Comment by byronv5** [comment]
I have the same problem:
win10 && visual studio 2022
