### ISSUE TITLE
Unable to click on any element on the page using WinApp's method (Only in one particular page)- Desktop automation

### ISSUE THREAD

**Issue by PriteshDesai242** [microsoft/WinAppDriver#804]
Hi,

I am trying to automate an desktop app in which I am unable to perform any action for a particular page using any of the winApp driver methods.

Can someone please help me on this or provide any alternative way to do this?

Trying to click an element using 

` StoreSession.findElementByName("Search").click();
  StoreSession.findElementByName("Search").sendKeys("Test");`

Displays the below error message even though element is present and visible.

`org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 187 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'DESKTOP-O530U00', ip: '10.80.103.66', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: io.appium.java_client.windows.WindowsDriver
Capabilities [{app=com.manh.storeui_h35559jr9hy9m!com.manh.storeui, platformName=Windows, platform=ANY}]
Session ID: 3BC0CCA1-68FA-4224-AD9C-C22B9FDE39DE
*** Element info: {Using=name, value=Search}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:371)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElement(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:452)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByName(DefaultGenericMobileDriver.java:110)
	at io.appium.java_client.AppiumDriver.findElementByName(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElementByName(WindowsDriver.java:1)
	at Java.CalculatorTest.src.test.java.CalculatorTest.setup(CalculatorTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)`

Please find the below screenshot of element been identified using inspect.exe 

![element](https://user-images.githubusercontent.com/54055715/62921083-4415d800-bdc5-11e9-8ab4-c384c7a83998.png)

Please let me know if additional information is required.

Thanks in advance.

**Comment by anunay1** [comment]
what kind of application is this, WIN32, WPF or UWP

**Comment by PriteshDesai242** [comment]
Its is an UWP application.

**Comment by anunay1** [comment]
try to get the window handle of that page and then try to switch to that page. and then try clicking the element.

**Comment by PriteshDesai242** [comment]
I tried doing getWindowHandles(), I am getting only one window ID on which I am already present.

**Comment by hassanuz** [comment]
@PriteshDesai242, please reopen if you are still experiencing this issue on the latest v1.2 release.
