### ISSUE TITLE
Issues with Automating with WinAppDriver

### ISSUE THREAD

**Issue by Guvsingh11** [microsoft/WinAppDriver#855]
Tried automating our internal desktop application called SMART tests with WinAppDriver. Used Windows inspect tool to inspect the elements on Smart UI. In visual studio , the winappdriver was able to open the Authentication page of smart but was not able to find any elements on the page.

Using WinAppDriver , I was able to open Calculator application of windows and click on its buttons. But with smart, winappdriver is not able to find the element. 

Result Message: 

Test Name:    TestMethod1
Test FullName:      TestForSmart.UnitTest1.TestMethod1
Test Outcome: Failed
Test Duration:      0:00:10.0453781

Result StackTrace:  
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByClassName(String className)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElementByClassName(String className)
   at TestForSmart.UnitTest1.TestMethod1() in C:\Users\Krishnaja.Koyyalumma\documents\visual studio 2015\Projects\TestForSmart\TestForSmart\UnitTest1.cs:line 32
Result Message:     
Test method TestForSmart.UnitTest1.TestMethod1 threw exception: 
System.InvalidOperationException: An element could not be located on the page using the given search parameters.

Though all the available online resources and locators like AutomationID, Name, ClassName, Xpath were used, the reason why the elements of smart were not detected could not be found. Since even authentication was failing, could not proceed to find out if the tool can be used in future for automation of smart.

Unable to attach a video recording of the issue.

**Comment by hassanuz** [comment]
Inspect is able to pick up elements on the login page, right? 

I would recommend creating a [Desktop Session](https://github.com/microsoft/WinAppDriver/blob/master/Docs/FAQ.md#when-and-how-to-create-a-desktop-session) and see if you are able to interact with the elements through that.

**Comment by Guvsingh11** [comment]
Hi Hassan

There is not enough information on the page as to:
How to create a desktop session
What is supposed to happen once you create this session
At what point do we create it
What is the purpose of creating the desktop session?

The link that you sent just seems to be a brief paragraph with general information.

Is there any further help you can provide?


Thanks




Kind Regards

Guv


GURVINDER RAINO
QA AUTOMATION LEAD
gurvinder.raino@jato.com<mailto:riikka.teikari@jato.com>

T: +44 (0)20 8423 7100 / M: +44 (0)7808 339 775
