### ISSUE TITLE
Unable to perform click action on the web element which is IsOffscreen is true

### ISSUE THREAD

**Issue by Prabu02101983** [microsoft/WinAppDriver#958]
HI

I am trying to automate a Windows app in which I am unable to perform click action for a web element which has IsOffscreen is true

Trying to click an element using
StoreSession.findElementByXPath("//Text[@Name='mpaff@manh.com']").click();

Displays the below error message:
testsadasdsaddorg.openqa.selenium.WebDriverException: An element command could not be completed because the element is not pointer- or keyboard interactable. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.10 seconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'POS-HP', ip: '10.85.21.94', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: io.appium.java_client.windows.WindowsDriver
Capabilities [{app=com.manh.storeui_h35559jr9hy9m!com.manh.storeui, platformName=Windows, platform=ANY}]
Session ID: E024FA67-7683-44A7-8824-7B056704029F
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:274)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at CalculatorTest.setup(CalculatorTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

Please find the below screenshot of element been identified using inspect.exe
![Picture1](https://user-images.githubusercontent.com/56548166/68670256-78d72e00-0572-11ea-9178-a6dbecba3108.png)

Can someone please help me on this or provide any alternative way to do this?

**Comment by PriteshDesai242** [comment]
Hi,

I am have the similar issue but I did not get any feedback.

Can someone please let us know, how can we proceed if isoffScreen = true, is there any way to change it or if there is any alternative approach then please let me know. I am completely blocked with this issue. Awaiting for a quick reply.

This issue is closed without providing an  resolution https://github.com/microsoft/WinAppDriver/issues/804 and I am not able to reopen it, can someone please do it for me.

Thanks.

**Comment by Prabu02101983** [comment]
Any update on this please???

**Comment by hassanuz** [comment]
Hi @PriteshDesai242 and @Prabu02101983, please refer to this [issue](https://github.com/Microsoft/WinAppDriver/issues/281). Is this the same case here? 

Specifically Tim's comment [here](https://github.com/Microsoft/WinAppDriver/issues/281#issuecomment-336986276): 

> When an element is offscreen (not displayed), Windows Application Driver will attempt to scroll it into view when applicable and only click the element if it is onscreen (displayed) then. In other words, Windows Application Driver doesn't click on the element that is not displayed on screen as it does not make sense in most scenario.
> 
> I'm not sure how the JavaScript command look like in Selenium/Appium, but typically an element should have a Displayed property that will be True when IsOffScreen is False and vice versa. Below is a C# snippet taken from the ElementDisplayed sample test.
> 
> WindowsElement addAlarmButton = session.FindElementByAccessibilityId("AddAlarmButton");
> Assert.IsTrue(addAlarmButton.Displayed);
> Alternatively you can access the IsOffScreen attribute directly using element.GetAttribute API. See GetElementAttribute example.
